/**
 * composition — the SECOND direction of a line grammar: given a body line already recognised as
 * one render shape, WHERE does each cell go. PURE: no DOM, no fetch, no clock.
 *
 * ── HOMED IN express/ — THE EXPRESS VERB IS "turn one node into a line of text; glyphs, tags,
 * stamps, cell order" ──
 *
 * `design-the-three-layers.md`'s own words for EXPRESS name "cell order" explicitly — this module
 * is that half, published as `resolution.composition` (`scripts/compile-resolution.mjs`) and read
 * by `resolutiontable.ts`'s `readComposition`. `rendition.ts` beside it is EXPRESS's RECOGNITION
 * half (what a printed line already looks like); this is the COMPOSITION half (what a NEW or
 * recomposed line should look like) — the two directions of one grammar, homed together because one
 * verb owns both.
 *
 * ── WHY THIS IS NOT `newline.ts`, WHICH STAYS THE CALLER ──
 *
 * `newline.ts` answers "what section is this, what does the cascade say a bare line becomes" — an
 * ADDRESSING question. This module answers "given the pieces are already known (a checkbox glyph,
 * some declared tokens), in what ORDER and with what SEPARATOR do they become one string, and where
 * does the operator's own text belong inside it" — never which pieces exist. `newline.ts` supplies
 * the pieces; this orders them.
 *
 * ── NO FIELD NAMES, NO TOKEN NAMES — ONLY THE SEVEN-MEMBER CELL-CLASS ALPHABET ──
 *
 * `CompositionCellClass` (`resolutiontable.ts`) is a closed set — checkbox / title / stamp / date /
 * tags / markers / chrome — and every function here is generic over it: `readCell` does one
 * `record[cellClass]` lookup and nothing branches on which class it got. An operator's own field
 * name (`domain`, `priority`) or vocabulary token (`#work`, `📅`) never appears in this file's
 * control flow — those are ALREADY-RESOLVED CHARACTERS by the time they reach here, carried inside
 * `tags`/`markers`/`chrome`'s string arrays. This is what "the app shouldn't know about anything,
 * only resolution mechanisms" means applied to composition specifically.
 *
 * ── THE ACCEPTANCE TEST THIS MODULE IS BUILT TO PASS ──
 *
 * `tests/composition-agreement.test.mjs` recomposes every fixture in
 * `tests/fixtures/composition-agreement.json` — generated by a LIVE import of the real Python
 * renderer, `scripts/composition-agreement.py` — through `composeLine` below, using ONLY the
 * fixture's own cell values and the declared `resolution.composition` order, and asserts
 * byte-identity against the engine's own committed output.
 */

import type { ChromeShape, Composition, CompositionCellClass } from "../resolutiontable.js";

/** The pieces a line is composed FROM — one optional field per cell class. `title` is the
 * operator's own words and is REQUIRED for `composeLine` (a full, committed line always has one,
 * even if it is the empty string); `composeSeed` below never takes a title at all, because a seed
 * exists BEFORE the operator has typed one. */
export interface LineCells {
  readonly checkbox?: string;
  readonly title: string;
  readonly stamp?: string;
  readonly date?: string;
  readonly tags?: readonly string[];
  readonly markers?: readonly string[];
  readonly chrome?: readonly string[];
}

/** The pieces already known when a line does not exist yet — everything `LineCells` carries
 * except `title`, which is what the operator is about to supply. */
export type KnownCells = Omit<LineCells, "title">;

function readCell(
  cellClass: CompositionCellClass,
  cells: Readonly<Partial<Record<CompositionCellClass, string | readonly string[]>>>,
): readonly string[] {
  const value = cells[cellClass];
  if (value === undefined || value === "") {
    return [];
  }
  if (Array.isArray(value)) {
    return value.filter((v): v is string => typeof v === "string" && v !== "");
  }
  return typeof value === "string" ? [value] : [];
}

/** `"    "` * depth — 4 spaces per level, `renderer.py:1003`'s own indent unit, verbatim. */
function indentFor(depth: number): string {
  return "    ".repeat(Math.max(0, Math.trunc(depth)));
}

/**
 * Apply composition's OWN declared, unconditional title wrap — `composition.titleStyles`, zero
 * or more of `"italic"` / `"bold"` / `"strikethrough"`. Byte-identical to `renderer.py`'s
 * `_apply_title_style` for the SAME styles set: fixed emission order (italic innermost, then
 * bold, then strikethrough outermost) regardless of the declared array's own order, because
 * `_apply_title_style` decides by membership (`"italic" in styles`), never by list position —
 * `canonicalise_title_segment`'s ingest-side peel loop (outermost-in: `~~`, `**`, `*`) is this
 * nesting's proven inverse. `cells.title` is expected UNSTYLED by anything else — this app has no
 * per-node rule-based title-style resolver (that is `render_title_style`, engine-only), so this is
 * the ONE wrap a composed title ever receives here.
 */
function applyTitleStyles(text: string, titleStyles: readonly string[]): string {
  let styled = text;
  if (titleStyles.includes("italic")) styled = `*${styled}*`;
  if (titleStyles.includes("bold")) styled = `**${styled}**`;
  if (titleStyles.includes("strikethrough")) styled = `~~${styled}~~`;
  return styled;
}

/**
 * Compose one COMPLETE line — every cell known, including its title. Byte-identical to the real
 * renderer's own line assembly (`renderer.py`'s `_render_node_line`: declared `bullet` + " " +
 * every non-empty cell joined by `composition.separator`, the title cell wrapped by
 * `composition.titleStyles` before joining) when fed that render's own cell values, proven for
 * the fixture set by `tests/composition-agreement.test.mjs`.
 *
 * `shape` selects `composition.heads[shape]`; `composition.tail` is the one order every shape's
 * body shares after its head (see `Composition`'s own header, `resolutiontable.ts`).
 */
export function composeLine(
  shape: ChromeShape,
  cells: LineCells,
  composition: Composition,
  depth = 0,
): string {
  const order = [...composition.heads[shape], ...composition.tail];
  const parts: string[] = [];
  for (const cellClass of order) {
    if (cellClass === "title") {
      if (cells.title !== "") {
        parts.push(applyTitleStyles(cells.title, composition.titleStyles));
      }
      continue;
    }
    parts.push(...readCell(cellClass, cells));
  }
  return `${indentFor(depth)}${composition.bullet} ${parts.join(composition.separator)}`;
}

/**
 * A single character no real title, tag, marker, chrome cell or stamp can ever contain — the NUL
 * control character. Used only to locate where the not-yet-typed title slot falls once the
 * surrounding KNOWN cells are joined with the real separator, then stripped back out — never
 * written to the page, because `composeSeed` always removes it before returning `text`.
 *
 * WHY NOT A SPACE, OR ANY OTHER PRINTABLE CHARACTER: a chrome cell routinely carries one
 * (`"#requires [[Get approval]]"` has a space in it) — a sentinel that can also appear inside a
 * REAL cell would let `indexOf` find the wrong occurrence and misplace the cursor. NUL is a
 * character no vocabulary token, tag, marker or typed title can contain — `renderer.py`'s own
 * embedded-line-separator guard (`line_text` in `_render_node_line`) already refuses `\n`/`\r`/
 * `\v`/U+2028 in any rendered cell, and NUL is stricter still: no printable text produces it.
 */
const TITLE_SLOT = String.fromCharCode(0);

/**
 * Compose a SEED — the characters a new line opens with, before the operator has typed a title,
 * plus WHERE the cursor belongs. Read `newline.ts`'s own header, "THE `o` SEED", for the defect
 * this fixes: seeding declared tokens AFTER the chrome and leaving the cursor at the string's end
 * put the operator's own words AFTER the tag, where the engine's declared order (title before tags)
 * never puts them — so the very next render moved his line under him.
 *
 * DERIVED FROM THE DECLARED ORDER, NOT ASSUMED. `title`'s position inside `composition.heads
 * [shape]` decides where the cursor sits — walk the full head+tail order, join every KNOWN cell
 * (never `title`, which is not known yet) with a `TITLE_SLOT` sentinel standing in for it, then
 * report the sentinel's own offset and strip it back out. If a future declaration ever moved title
 * to the END of a shape's order (never true of `checkbox`/`plain_line` today), the cursor would
 * move with it — nothing here hardcodes "cursor after chrome".
 */
export function composeSeed(
  shape: ChromeShape,
  known: KnownCells,
  composition: Composition,
  depth = 0,
): { readonly text: string; readonly cursorOffset: number } {
  const order = [...composition.heads[shape], ...composition.tail];
  const parts: string[] = [];
  for (const cellClass of order) {
    if (cellClass === "title") {
      // Wrap the SENTINEL, not yet any title text, in the declared style — `applyTitleStyles("",
      // …)` on an as-yet-untyped title, so `*` + NUL + `*` seeds the cursor BETWEEN the wrap
      // markers. `indexOf(TITLE_SLOT)` below still finds the sentinel's own position exactly
      // (the wrap characters carry no NUL of their own), so this composes with zero change to the
      // slot-location arithmetic that follows.
      parts.push(applyTitleStyles(TITLE_SLOT, composition.titleStyles));
      continue;
    }
    parts.push(...readCell(cellClass, known));
  }
  const joined = parts.join(composition.separator);
  const prefix = `${indentFor(depth)}${composition.bullet} `;
  const slotIndex = joined.indexOf(TITLE_SLOT);
  if (slotIndex === -1) {
    // No declared "title" cell in this shape's own order — nothing to place a cursor before. Every
    // known cell, if any, still composes; the cursor falls at the end, same as a caller with no
    // declaration ever got.
    return { text: `${prefix}${joined}`, cursorOffset: (prefix + joined).length };
  }
  const bare = joined.slice(0, slotIndex) + joined.slice(slotIndex + 1);
  return { text: `${prefix}${bare}`, cursorOffset: prefix.length + slotIndex };
}
