/**
 * DOES THE BROWSER'S ORDERABLE-COMPARISON / CYCLE-VARIABLE EVALUATOR AGREE WITH THE ENGINE?
 *
 *   node --test tests/comparison-agreement.test.mjs
 *
 * `tests/qualification-agreement.test.mjs` proves agreement over the THREE-FIELD probe space
 * (`node_type`/`domain`/`status`) its own `TRIPLE_FIELDS` is built on — every one of job 1's
 * fourteen ("the last fourteen") predicates ranges over a FOURTH field
 * (`due_date`/`available_date`/`created_at`) and is correctly excluded there as
 * `fieldOutOfScopePatterns`, not verified. This file is that verification: the fourth field's own
 * VALUE, and the two cycle variables (`$cycle_today`/`$cycle_week_end`) job 1 admits, are the
 * axes here.
 *
 * ── THE EXPECTED SIDE IS NOT WRITTEN BY HAND ──
 *
 * `tests/fixtures/comparison-agreement.json` is GENERATED by `scripts/comparison-agreement.py`
 * calling `qntm_graph.patterns.engine.matches_pattern` directly, over an EMPTY in-memory graph
 * built from the operator's real, read-only config — no state.db, no cycle, no network. Nothing
 * here was transcribed; `cycle_today`/`cycle_week_end` are supplied as pattern PARAMETERS,
 * controlling the axis this fixture is actually about.
 *
 * ── WHAT IS COMPARED, AND WHY THESE FIVE PATTERNS ──
 *
 * One representative pattern per operator/value class among the fourteen — every comparison
 * operator (`gt` via `not`+`gt`'s inner test, `lt`, `gte`+`lte` as a range) and every cycle
 * expression shape (`eq` bare, `eq` with a `+` offset, `eq` with a `-` offset) job 1 admits is
 * exercised by at least one row:
 *
 *   `overdue`              due_date: {lt: $cycle_today}                        bare `lt`
 *   `due-this-week`        due_date: {gte: $cycle_today, lte: $cycle_week_end} a range, both ends
 *   `all-personal-nodes`   available_date: {not: {gt: $cycle_today}}          null-tolerant not+gt
 *   `available-tomorrow`   available_date: {eq: "$cycle_today + 1 d"}         eq, `+` offset
 *   `due-yesterday`        due_date: {eq: "$cycle_today - 1 d"}               eq, `-` offset
 *
 * Each is probed at its own boundary — equal, one day above, one day below, and (for the
 * null-tolerant case) an ABSENT field — plus one composition proving the day-boundary resolver's
 * OUTPUT (`app/present/today.ts`'s `todayFor`) feeds a comparison predicate correctly at the exact
 * 03:59/04:01 Europe/London rollover `tests/present-today.test.mjs` already proves in isolation.
 *
 * ── WHAT IT DOES NOT PROVE ──
 *
 * The same field-resolution boundary `tests/qualification-agreement.test.mjs`'s own header
 * states: this drives `matchesQualifier` with a HAND-BUILT field set, not `resolveLineFields`
 * over a typed line. `tests/present-membership.test.mjs`'s own extraction-hint cases (`due_date`'s
 * 📅 and its siblings) are what covers that half.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  readQualificationDeclaration,
  matchesQualifier,
  todayFor,
} from "../dist/present.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVED = JSON.parse(readFileSync(resolve(HERE, "..", "presentation.json"), "utf8"));
const FIXTURE = JSON.parse(readFileSync(resolve(HERE, "fixtures", "comparison-agreement.json"), "utf8"));
const { qualification: QUALIFICATION } = readQualificationDeclaration(SERVED);
const { resolution: RESOLUTION } = { resolution: JSON.parse(readFileSync(resolve(HERE, "..", "presentation.json"), "utf8")).resolution };

describe("0. the fixture is non-empty and names patterns this declaration actually published", () => {
  test("every row's pattern is a published predicate", () => {
    for (const row of FIXTURE.rows) {
      assert.ok(row.pattern in QUALIFICATION.predicates, `'${row.pattern}' was not published`);
    }
  });
  test("the fixture is not vacuous", () => {
    assert.ok(FIXTURE.rows.length >= 16, `only ${FIXTURE.rows.length} boundary rows`);
    assert.ok(FIXTURE.dayBoundaryRows.length >= 4, `only ${FIXTURE.dayBoundaryRows.length} day-boundary rows`);
  });
  test("every one of job 1's five operator/value classes is covered", () => {
    const patterns = new Set(FIXTURE.rows.map((r) => r.pattern));
    for (const name of ["overdue", "due-this-week", "all-personal-nodes", "available-tomorrow", "due-yesterday"]) {
      assert.ok(patterns.has(name), `'${name}' is not exercised by any fixture row`);
    }
  });
});

describe("1. every boundary case: the browser's matchesQualifier agrees with the engine", () => {
  for (const row of FIXTURE.rows) {
    test(row.name, () => {
      const qualifier = QUALIFICATION.predicates[row.pattern];
      assert.ok(qualifier, `'${row.pattern}' is not published`);
      const fields = { node_type: "task", domain: null, status: "open", ...row.fields };
      const today = { logicalDate: row.cycleToday, weekEnd: row.cycleWeekEnd };
      const belongs = matchesQualifier(fields, qualifier, today);
      assert.equal(belongs, row.matched, `browser said ${belongs}, engine said ${row.matched}`);
    });
  }
});

describe("2. THE DAY-BOUNDARY COMPOSITION — todayFor's output feeds a comparison predicate correctly", () => {
  const dayBoundary = RESOLUTION.dayBoundary;
  test("resolution.dayBoundary matches the fixture's own REAL_BOUNDARY (Europe/London, 4, monday)", () => {
    // A precondition, not the claim: if the served day boundary ever drifts from what the fixture
    // was generated against, every case below would be comparing two different boundaries and
    // agreeing by accident or disagreeing for the wrong reason.
    const first = FIXTURE.dayBoundaryRows[0];
    assert.equal(dayBoundary.timezone, first.boundary.timezone);
    assert.equal(dayBoundary.dayStartHour, first.boundary.day_start_hour);
    assert.equal(dayBoundary.weekStartsOn, first.boundary.week_starts_on);
  });

  for (const row of FIXTURE.dayBoundaryRows) {
    test(`${row.instant} (${row.description}) — todayFor -> overdue agrees with the engine`, () => {
      const nowUtcMs = Date.parse(row.instant);
      const reading = todayFor(nowUtcMs, dayBoundary);
      assert.equal(reading.kind, "answer", "the day boundary resolver abstained");
      assert.equal(
        reading.answer.logicalDate,
        row.resolvedCycleToday,
        "the browser's own logical date disagrees with the engine's resolve_logical_day",
      );
      const qualifier = QUALIFICATION.predicates["overdue"];
      const fields = { node_type: "task", domain: null, status: "open", due_date: row.dueDate };
      const belongs = matchesQualifier(fields, qualifier, reading.answer);
      assert.equal(belongs, row.matched, `browser said ${belongs}, engine said ${row.matched} — ${row.expect}`);
    });
  }
});
