/**
 * A NEW LINE ACQUIRES WHAT IT IS, AS HE TYPES IT — rungs 1 and 2 of the operator's own ladder.
 *
 *   node --test tests/present-seed.test.mjs
 *
 * His words are the specification: *"it gets stamped `task`. That's what the evidence would be for
 * inbox. Then the next thing would be for say `personal all` — it would get stamped `task` and
 * `personal`, as we have a default resolution here. It shouldn't be specifically wired to any
 * resolution, but should work for ANY new config the user puts in — much like the backend engine
 * does. That's how we know it's generalised."*
 *
 * Six claims, and they are the six sections.
 *
 *   1. THE HEADLINE. The exact line he would type in `personal/all`, before and after, against
 *      the SERVED declaration and his own real section ids. Nothing here is a toy view.
 *   2. THE AGREEMENT. For every one of his 219 sections, the tokens the browser seeds equal the
 *      tokens the ENGINE'S OWN `TokenResolver.source_tags_for_node` renders — the same function
 *      `FieldReconstructor` calls on every line the renderer prints. Generated by
 *      `scripts/resolution-agreement.py`, never transcribed. 219 cases, no sampling. Four are
 *      held out by name under a FILED DEFECT — see `KNOWN_CHECKBOX_SEED_DEFECT` and section 2c.
 *   3. THE ROUND TRIP. `accept ⊇ emit`: what is seeded is what the write path posts, byte for
 *      byte, and what the engine's own ingest reads back as the same fact.
 *   4. THE ACCEPTANCE TEST, BOTH HALVES, against a scratch copy of his REAL config. Add a
 *      `defaults:` block naming a field and a token this repo has never heard of, regenerate, and
 *      the browser follows WITH NO CODE CHANGE. Then the negative arm: a `defaults:` block the
 *      grammar cannot express lands in `dropped` and is visible.
 *   5. THE REFUSALS. Each one named, each one measured, none of them assumed.
 *   6. THE MUTATION PROOF. Break the seeding and a test in this file goes red — shown going red,
 *      because a guard that cannot go red is decoration.
 *
 * NOTHING HERE WRITES TO THE OPERATOR'S CONFIG OR HIS VAULT. Section 4 mutates a `cpSync` copy
 * under the runner's temp dir and removes it in a `finally`. No cycle is run anywhere.
 *
 * Everything runs against `dist/present.js`, the artifact the browser loads.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import MarkdownIt from "markdown-it";

import { makeDocument, makeBody, makeEvent, walk } from "./fixtures/dom-stub.mjs";
import {
  paint,
  seedFor,
  readConfigResolutionDeclaration,
  readQualificationDeclaration,
  resolveLineFields,
  DraftSurface,
  FocusSurface,
  PresentationContext,
} from "../dist/present.js";
import { generateResolution, DEFAULT_CONFIG_DIR } from "../scripts/generate-resolution-declaration.mjs";
import { Ledger } from "../scripts/ledger.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");
const md = new MarkdownIt("commonmark").enable("table");
const read = (path) => JSON.parse(readFileSync(resolve(HERE, path), "utf8"));

const SERVED = read("../presentation.json");
const RESOLUTION = readConfigResolutionDeclaration(SERVED).resolution;
const QUALIFICATION = readQualificationDeclaration(SERVED).qualification;
const TRUTH = read("./fixtures/resolution-agreement.json");

/**
 * A `GlobalRegistration` for one of the operator's own views, assembled the way `app/index.html`'s
 * `globalRegistrationFor` assembles it — from the SERVED declaration, not from a literal.
 */
const declaredFor = (viewId) => ({
  view: viewId,
  sectionOrder: QUALIFICATION.sectionOrder,
  sections: QUALIFICATION.sections,
  chromeShapes: RESOLUTION.chromeShapes,
  sectionRegistration: RESOLUTION.sectionRegistration,
});

// ── 1. the headline ───────────────────────────────────────────────────────────────────────────

describe("1. the exact line he would type, before and after", () => {
  // His own file, its own heading. `config/views/all-personal.yaml` declares one section, `tasks`,
  // named "All Personal", with `defaults: {domain: personal}`.
  const PERSONAL_ALL = "## All Personal\n";
  // `config/views/inbox.yaml` declares two sections and NEITHER declares a `defaults:` block, so
  // inbox is the rung-1-only case: the type, and nothing else. That is the correct answer there,
  // not a shortfall — design-the-rule-mirror.md §7.1.
  const INBOX = "## Inbox\n## Domain Empty\n";

  test("PERSONAL/ALL — it gets stamped task AND personal", () => {
    const before = seedFor(PERSONAL_ALL, 1);
    assert.deepEqual(before, null, "with no declaration the seed is what it always was");

    const after = seedFor(PERSONAL_ALL, 1, declaredFor("all-personal"));
    assert.equal(after.text, "- [ ] #task #personal ");
    assert.deepEqual(after.tokens, ["#task", "#personal"]);
  });

  test("INBOX — it gets stamped task", () => {
    for (const [lineIndex, section] of [[1, "inbox-tagged"], [2, "domain-empty"]]) {
      const seed = seedFor(INBOX, lineIndex, declaredFor("inbox"));
      assert.equal(seed.text, "- [ ] #task ", `${section} did not seed the type alone`);
      assert.deepEqual(seed.tokens, ["#task"]);
    }
  });

  test("HIS OWN FILE, UNCHANGED — the seed under a printed line is the same answer", () => {
    // The three PRINTED rungs still decide the CHROME, and the tokens still come from the SECTION.
    // A line opened under a real `personal/all.md` line inherits the chrome from the line above and
    // the tokens from the declaration, and they agree because they describe the same section.
    const printed =
      "## All Personal\n- [ ] Adam birthday present [[qntm:783]] #outcome #personal 🆕 2026-06-08\n";
    const seed = seedFor(printed, 2, declaredFor("all-personal"));
    assert.equal(seed.level, "LINE", "the printed rung stopped deciding the chrome");
    assert.equal(seed.text, "- [ ] #task #personal ");
  });

  test("IT REACHES THE PAGE, not merely the function", () => {
    globalThis.document = makeDocument();
    const body = makeBody();
    const draft = new DraftSurface();
    paint(body, "## All Personal\n", new PresentationContext(), {
      markdown: md,
      focus: new FocusSurface(),
      draft,
      declared: declaredFor("all-personal"),
      view: "all-personal",
    });
    const trailing = body.children.filter((el) => el.className === "newline");
    trailing[0].dispatch("click");
    const input = walk(body).find((el) => el.tagName === "input" && el.type === "text");
    assert.equal(input.value, "- [ ] #task #personal ", "the row on the page is not the seed");
  });

  test("THE CURSOR SITS AFTER EVERYTHING THE CONFIG SAID, so his first keystroke is his own", () => {
    // The seed ends in a space and nothing else, which is what puts the title he types AFTER the
    // tokens rather than inside them. The engine parses a token anywhere in the tail and excises it
    // from the title (`io/parser/line_parser.py`'s `_normalise_title` collapses what is left), so
    // `- [ ] #task #personal buy milk` mints a task titled "buy milk" in the personal domain.
    const seed = seedFor("## All Personal\n", 1, declaredFor("all-personal"));
    assert.ok(seed.text.endsWith(" "), "the seed does not end in a separator");
    assert.ok(!/\s\s$/.test(seed.text), "the seed ends in two spaces — the title would not join it");
    const typed = `${seed.text}buy milk`;
    assert.equal(typed, "- [ ] #task #personal buy milk");
    // And the app's OWN reader of that line resolves the fields the section declared.
    const section = { nodeType: "task", defaults: { domain: "personal" } };
    const fields = resolveLineFields(typed, section, QUALIFICATION);
    assert.equal(fields.node_type, "task");
    assert.equal(fields.domain, "personal");
    assert.equal(fields.status, "open");
  });
});

// ── 2. the agreement, against the engine's own renderer ───────────────────────────────────────

/**
 * DEFECT — `status:` IS SEEDED AS A CHECKBOX TOKEN, AND THE ENGINE DOES NOT AGREE.
 *
 * Filed 2026-08-03, exposed by regenerating from monorepo `d4c9d98`. `ec5e0b3` (program assets
 * and defects catalogues) is the FIRST config to put a `status:` default on a section, and it
 * does so on exactly these four. For each one the generator resolves that default to a checkbox
 * state and publishes it AS A TOKEN, mid-list:
 *
 *     assets-program.active-assets   browser ["#asset","[ ]","#program"]
 *                                    engine  ["#asset","#program"]
 *
 * The engine's `source_tags_for_node` answers with TAGS. A checkbox is not a tag — it is the
 * line's own marker, which the engine renders in the `- [ ] ` prefix, not in the token stream.
 * So the browser is about to write a second checkbox into the middle of a line it seeds.
 *
 * WHICH SIDE IS WRONG IS NOT DECIDED HERE, and fixing it is outside a test-suite change: either
 * `generate-resolution-declaration.mjs` must refuse `status` the way it already refuses
 * `project` (it currently counts it as SPELLED — see §5's census), or the seed must place the
 * resolved state in the marker rather than the tokens. Both are engine/generator changes.
 *
 * CONTAINED: exactly these four sections, all of them new, all in views created yesterday.
 * `all-personal`, `this-week` and `inbox` declare no `status:` default and are not affected.
 *
 * The four are excluded from the agreement sweep BY NAME, never by rule, so a FIFTH section that
 * disagrees still goes red — and §2c asserts they are all still broken in exactly this way, so
 * this exclusion cannot outlive the defect.
 */
const KNOWN_CHECKBOX_SEED_DEFECT = {
  "assets-program.active-assets": { browser: ["#asset", "[ ]", "#program"], engine: ["#asset", "#program"] },
  "assets-program.inactive-assets": { browser: ["#asset", "[x]", "#program"], engine: ["#asset", "#program"] },
  "defects-program.active-defects": { browser: ["#defect", "[ ]", "#program"], engine: ["#defect", "#program"] },
  "defects-program.inactive-defects": { browser: ["#defect", "[x]", "#program"], engine: ["#defect", "#program"] },
};

describe("2. THE AGREEMENT — the browser's seed is the engine's own rendered tags", () => {
  const published = RESOLUTION.sectionRegistration;
  const dropped = RESOLUTION.dropped;

  test("the fixture is the ENGINE's answer and it covers every section, not a sample", () => {
    assert.ok(Array.isArray(TRUTH.seeds), "the fixture carries no seeds arm — regenerate it");
    // RESTATED 2026-08-03: 186 -> 219, when the fixture was regenerated by
    // `scripts/resolution-agreement.py` against monorepo `d4c9d98`. Seven new views arrived and
    // brought their sections with them. The claim — that the fixture covers EVERY section rather
    // than a sample — is unchanged.
    assert.equal(TRUTH.seeds.length, 219, "the engine did not answer for all 219 sections");
    // POSITIVE CONTROL, the same one `scripts/resolution-agreement.py` refuses without: an
    // all-empty truth side would agree with a completely broken browser just as well.
    assert.ok(
      TRUTH.seeds.filter((s) => s.tokens.length >= 2).length > 100,
      "almost nothing in the engine's answer carries two tags — this comparison is vacuous",
    );
  });

  test("EVERY SECTION AGREES, or its type tag is withheld WITH A RECORDED REASON", () => {
    let identical = 0;
    let withheld = 0;
    const disagreements = [];
    for (const { view, section, nodeType, tokens } of TRUTH.seeds) {
      // The four sections of the filed checkbox-seed defect, excluded by name. §2c holds them.
      if (`${view}.${section}` in KNOWN_CHECKBOX_SEED_DEFECT) continue;
      const entry = published[view]?.[section];
      if (entry === undefined) {
        disagreements.push(`${view}.${section}: published nothing at all`);
        continue;
      }
      if (entry.nodeType !== nodeType) {
        disagreements.push(`${view}.${section}: nodeType ${entry.nodeType} vs engine ${nodeType}`);
        continue;
      }
      const seeded = [...entry.tokens];
      if (JSON.stringify(seeded) === JSON.stringify(tokens)) {
        identical += 1;
        continue;
      }
      // The ONE permitted difference, and it is never silent: the type tag is withheld where a
      // rule retypes the capture inside the pass that minted it (§3.3). The engine, asked what a
      // node of the DECLARED type prints, still answers with it — so the browser's answer must be
      // the engine's minus exactly that first token, AND the reason must be on the record.
      if (JSON.stringify(seeded) === JSON.stringify(tokens.slice(1))) {
        const what = `section '${view}.${section}'`;
        if (!(what in dropped) || !/type tag is not seeded/.test(dropped[what])) {
          disagreements.push(`${view}.${section}: type tag withheld with NO recorded reason`);
          continue;
        }
        withheld += 1;
        continue;
      }
      disagreements.push(
        `${view}.${section}: seeded ${JSON.stringify(seeded)} vs engine ${JSON.stringify(tokens)}`,
      );
    }
    assert.deepEqual(disagreements, [], "the browser and the engine disagree");
    // The numbers design-the-rule-mirror.md predicted, arrived at independently: 13 of 186.
    // RESTATED 2026-08-03 against monorepo `d4c9d98`: 15 withheld + 200 identical + the 4 sections
    // of the filed checkbox-seed defect = 219, the whole fixture. Nothing is unaccounted for.
    assert.equal(withheld, 15, "the type-tag refusal no longer lands on exactly 15 sections");
    assert.equal(identical, 200, "the sections that agree outright are no longer 200");
    assert.equal(
      withheld + identical + Object.keys(KNOWN_CHECKBOX_SEED_DEFECT).length,
      TRUTH.seeds.length,
      "a section fell out of every bucket — the sweep no longer covers the whole fixture",
    );
  });

  test("HIS OWN EXAMPLE is in the agreeing set, and the engine spells it the same way", () => {
    const engine = TRUTH.seeds.find((s) => s.view === "all-personal" && s.section === "tasks");
    assert.deepEqual(engine.tokens, ["#task", "#personal"], "the ENGINE does not print #task #personal");
    assert.deepEqual(published["all-personal"].tasks.tokens, engine.tokens);
  });
});

// ── 2c. the filed defect, held in place so the exclusion above cannot outlive it ───────────────

describe("2c. THE CHECKBOX SEED DEFECT — filed, named, and pinned so it cannot rot", () => {
  const published = RESOLUTION.sectionRegistration;

  test("the defect is EXACTLY these four sections, and no other section seeds a checkbox", () => {
    // This is the guard on §2's exclusion, and it fails in BOTH directions on purpose:
    //   - a FIFTH section starts seeding a checkbox   -> red, because the set grew
    //   - the defect is FIXED                         -> red, because the set shrank
    // Either way somebody has to come back and delete the exclusion rather than inherit it.
    const seedsACheckbox = [];
    for (const [view, sections] of Object.entries(published)) {
      for (const [section, entry] of Object.entries(sections)) {
        if (entry.tokens.some((t) => t === "[ ]" || t === "[x]")) seedsACheckbox.push(`${view}.${section}`);
      }
    }
    assert.deepEqual(
      seedsACheckbox.sort(),
      Object.keys(KNOWN_CHECKBOX_SEED_DEFECT).sort(),
      "the set of sections seeding a checkbox token moved — if the defect is fixed, delete the " +
        "KNOWN_CHECKBOX_SEED_DEFECT exclusion in section 2 rather than restating it here",
    );
  });

  test("none of the four is a view the operator uses daily", () => {
    // The reason this was filed rather than treated as a stop-ship. Every affected section belongs
    // to a view created on 2026-08-02; his three daily views declare no `status:` default at all.
    for (const view of ["all-personal", "this-week", "inbox"]) {
      for (const entry of Object.values(published[view] ?? {})) {
        assert.ok(
          !("status" in (entry.defaults ?? {})),
          `${view} now declares a status default — it is inside the blast radius of the filed defect`,
        );
      }
    }
  });

  test.todo(
    "DEFECT: a section's `status:` default must not be seeded as a mid-line checkbox token — " +
      "the engine renders resolved state in the line's marker, not in the tag stream, so " +
      "generate-resolution-declaration.mjs must either refuse `status` the way it refuses " +
      "`project`, or the seed must place it in the marker. Affects assets-program and " +
      "defects-program (4 sections). Exposed by regenerating from monorepo d4c9d98; not caused " +
      "by it. Un-todo this once the generator or the seed is fixed.",
  );
});

// ── 3. the round trip ─────────────────────────────────────────────────────────────────────────

describe("3. THE ROUND TRIP — accept ⊇ emit, byte for byte", () => {
  const inputs = (body) => walk(body).filter((el) => el.tagName === "input" && el.type === "text");

  function makeLine(source, viewId, title) {
    globalThis.document = makeDocument();
    const body = makeBody();
    const commits = [];
    paint(body, source, new PresentationContext(), {
      markdown: md,
      focus: new FocusSurface(),
      draft: new DraftSurface(),
      declared: declaredFor(viewId),
      view: viewId,
      onLineCommit: (commit) => commits.push(commit),
    });
    body.children.filter((el) => el.className === "newline")[0].dispatch("click");
    const input = inputs(body)[0];
    const seeded = input.value;
    input.value = `${seeded}${title}`;
    input.dispatch("blur");
    return { seeded, commits: commits.filter((c) => c.markdown !== null) };
  }

  test("what is seeded is what is POSTED — no character is added, dropped or reordered", () => {
    const source = "## All Personal\n";
    const { seeded, commits } = makeLine(source, "all-personal", "buy milk");
    assert.equal(seeded, "- [ ] #task #personal ");
    assert.equal(commits.length, 1, "the line was not posted");
    const after = commits[0].markdown.split("\n");
    const before = source.split("\n");
    assert.equal(after[1], "- [ ] #task #personal buy milk", "the posted line is not the seed plus the title");
    assert.equal(after[0], before[0], "the heading changed");
    assert.equal(after.length, before.length + 1, "the file did not gain exactly one line");
  });

  test("THE SEEDED TOKENS SURVIVE A SECOND PASS — the app reads back what it wrote", () => {
    // `accept ⊇ emit` for THIS app: the membership reader, given the line the seed produced,
    // resolves the same fields the section declared. If the app could not read its own emission,
    // the operator's next keystroke would be evaluated against a line the app does not understand.
    const { seeded } = makeLine("## All Personal\n", "all-personal", "buy milk");
    const line = `${seeded}buy milk`;
    const section = QUALIFICATION.sections["inbox"]?.["domain-empty"];
    assert.ok(section, "the operator's inbox section left the published table");
    const fields = resolveLineFields(line, { nodeType: "task", defaults: { domain: "personal" } }, QUALIFICATION);
    assert.equal(typeof fields, "object", `the app refused its own seeded line: ${fields}`);
    assert.equal(fields.domain, "personal");
  });

  test("SEEDING IS IDEMPOTENT — asking twice produces the same characters", () => {
    const a = seedFor("## All Personal\n", 1, declaredFor("all-personal"));
    const b = seedFor("## All Personal\n", 1, declaredFor("all-personal"));
    assert.deepEqual(a, b);
  });

  test("A SEEDED LINE WITH NO TITLE IS STILL REFUSED — the tokens are not content", () => {
    // The most important refusal in `newline.ts`'s own section 4: `- [ ] ` with an empty title
    // mints an `(untitled)` node and reprints it forever. Seeding tokens must not turn an empty
    // line into a committable one, because a line carrying only what the CONFIG said carries
    // nothing the operator said.
    const { commits } = makeLine("## All Personal\n", "all-personal", "");
    assert.deepEqual(commits, [], "a line with only its seed on it was posted");
  });
});

// ── 4. the acceptance test, both halves, against his real config ──────────────────────────────

const MONOREPO = existsSync(DEFAULT_CONFIG_DIR) ? false : "monorepo not checked out";

describe("4. THE ACCEPTANCE TEST — any new config, with no code change", { skip: MONOREPO }, () => {
  /** Copy his real config somewhere writable, mutate it, regenerate. Never touches the original. */
  function withConfig(mutate, use) {
    const scratch = mkdtempSync(join(tmpdir(), "present-seed-"));
    try {
      const configDir = join(scratch, "config");
      cpSync(DEFAULT_CONFIG_DIR, configDir, { recursive: true });
      mutate(configDir);
      const ledger = new Ledger();
      return use(generateResolution(configDir, ledger), configDir);
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  }

  const put = (configDir, relative, text) => writeFileSync(join(configDir, relative), text);

  test("HALF A — a defaults block naming a field and a token this repo has never heard of", () => {
    // THE STRONGEST FORM OF THE FALSIFIER. Not "a new value of a field the code knows" and not
    // "a new section using a field the code knows" — a brand new vocabulary FAMILY, a brand new
    // FIELD, a brand new TOKEN, and a `defaults:` block pointing at them. If any of the three were
    // enumerated in code rather than read, this fails.
    const generated = withConfig(
      (configDir) => {
        put(
          configDir,
          "vocabulary/mood_tags.yaml",
          'mood_tags:\n  - { token: "#serene", field: mood, value: serene }\n',
        );
        put(
          configDir,
          "views/scratch-mood.yaml",
          [
            "scratch-mood:",
            "  version: 1",
            "  path: scratch/mood.md",
            "  sections:",
            "    - id: calm",
            "      qualification: all-personal-nodes",
            '      name: "Calm"',
            "      defaults:",
            "        mood: serene",
            "",
          ].join("\n"),
        );
      },
      (resolution) => resolution,
    );
    const entry = generated.sectionRegistration["scratch-mood"].calm;
    assert.deepEqual(entry.defaults, { mood: "serene" });
    assert.deepEqual(entry.tokens, ["#task", "#serene"], "the new field's token did not reach the seed");

    // AND THE BROWSER FOLLOWS. The same reader the page uses, over the regenerated declaration,
    // with not one line of app code changed.
    const table = readConfigResolutionDeclaration({ resolution: generated }).resolution;
    const seed = seedFor("## Calm\n", 1, {
      view: "scratch-mood",
      sectionOrder: { "scratch-mood": ["calm"] },
      sections: {},
      chromeShapes: table.chromeShapes,
      sectionRegistration: table.sectionRegistration,
    });
    assert.equal(seed.text, "- [ ] #task #serene ", "the browser did not follow the config");
  });

  test("HALF A, SECOND ARM — the same config change flows through an EXISTING section too", () => {
    // `personal/all` today declares `domain: personal` and seeds `#task #personal`. Change the
    // declared value and the seed changes with it — nothing in the app knows the word `personal`.
    const generated = withConfig(
      (configDir) => {
        const path = join(configDir, "views", "all-personal.yaml");
        const before = readFileSync(path, "utf8");
        // The SECTION's default, not the sheet's `domain:` key — the file carries both, and
        // replacing the first occurrence would change the sheet and leave the seed alone, which is
        // a test that passes by measuring nothing.
        const anchor = "      defaults:\n        domain: personal";
        assert.ok(before.includes(anchor), "the mutation's anchor moved");
        writeFileSync(path, before.replace(anchor, "      defaults:\n        domain: spirit"));
      },
      (resolution) => resolution,
    );
    assert.deepEqual(
      generated.sectionRegistration["all-personal"].tasks.tokens,
      ["#task", "#spirit"],
      "the seed is wired to the value rather than reading it",
    );
  });

  test("HALF B — a defaults block the grammar CANNOT express lands in `dropped`, visibly", () => {
    // The negative arm, and it matters more. A section pointing its `defaults:` at a field no
    // vocabulary tag spells must SAY SO — the middle row of §8.4's three outcomes, never the third.
    const generated = withConfig(
      (configDir) =>
        put(
          configDir,
          "views/scratch-unspellable.yaml",
          [
            "scratch-unspellable:",
            "  version: 1",
            "  path: scratch/unspellable.md",
            "  sections:",
            "    - id: nowhere",
            "      qualification: all-personal-nodes",
            '      name: "Nowhere"',
            "      defaults:",
            "        invented_field: invented_value",
            "",
          ].join("\n"),
        ),
      (resolution) => resolution,
    );
    const what = "section 'scratch-unspellable.nowhere' default 'invented_field'";
    assert.ok(what in generated.dropped, `nothing was recorded for ${what}`);
    assert.match(generated.dropped[what], /no vocabulary tag spells invented_field="invented_value"/);
    // And the seed itself carries the type tag and NOTHING invented — refused, never guessed.
    assert.deepEqual(generated.sectionRegistration["scratch-unspellable"].nowhere.tokens, ["#task"]);
  });

  test("HALF B, SECOND ARM — a NEW RETYPE RULE refuses a type tag, with no code change", () => {
    // The generality of the §3.3 gate itself. Nothing names `routine`: declare a rule that retypes
    // an `outcome` with no cadence and every `outcome`-defaulting section stops seeding its type.
    const generated = withConfig(
      (configDir) => {
        put(
          configDir,
          "patterns/scratch_outcomes.yaml",
          "scratch-outcomes:\n  parameters: {}\n  root:\n    find:\n      node_type: outcome\n  steps: []\n",
        );
        put(
          configDir,
          "rules/scratch_outcome_retype.yaml",
          [
            "- id: scratch-outcome-becomes-task",
            "  for_each:",
            "    pattern: scratch-outcomes",
            "  when:",
            '    "null": [$current.node.fields.cadence]',
            "  actions:",
            "    - verb: set_node_type",
            "      node_id: $current.node.id",
            "      node_type: task",
            "",
          ].join("\n"),
        );
        put(
          configDir,
          "views/scratch-outcome.yaml",
          [
            "scratch-outcome:",
            "  version: 1",
            "  path: scratch/outcome.md",
            "  default_node_type: outcome",
            "  sections:",
            "    - id: all",
            "      qualification: all-personal-nodes",
            '      name: "All"',
            "      defaults:",
            "        domain: personal",
            "",
          ].join("\n"),
        );
      },
      (resolution) => resolution,
    );
    const entry = generated.sectionRegistration["scratch-outcome"].all;
    assert.equal(entry.nodeType, "outcome");
    assert.deepEqual(entry.tokens, ["#personal"], "the new rule's retype did not refuse the type tag");
    assert.match(
      generated.dropped["section 'scratch-outcome.all'"],
      /scratch-outcome-becomes-task/,
      "the refusal names no rule, so the operator cannot act on it",
    );
  });

  test("THE UNMUTATED CONFIG IS THE CONTROL — it produces exactly what is committed", () => {
    const ledger = new Ledger();
    const fresh = generateResolution(DEFAULT_CONFIG_DIR, ledger);
    assert.deepEqual(
      fresh.sectionRegistration,
      SERVED.resolution.sectionRegistration,
      "presentation.json's seed table is stale relative to the monorepo config",
    );
  });
});

// ── 5. the refusals ───────────────────────────────────────────────────────────────────────────

describe("5. THE REFUSALS — each one named, measured, and not assumed", () => {
  test("NO DECLARATION is the exact previous behaviour — the negative control", () => {
    // Every one of `tests/present-newline.test.mjs`'s own sections calls `seedFor` with no
    // declaration, and not one of them changed. Restated here because it is what makes this
    // additive rather than a new required parameter.
    const printed = "## Overdue\n- [ ] Draft the launch note [[qntm:121]] #task #work\n";
    assert.deepEqual(seedFor(printed, 2), { text: "- [ ] ", level: "LINE", tokens: [] });
  });

  test("A SECTION `sectionAt` CANNOT NAME seeds no tokens", () => {
    // Above the first heading there is no section, so there is no declaration to read. The chrome
    // still comes from printed evidence; the tokens do not appear from nowhere.
    const printed = "- [ ] a line above every heading\n## All Personal\n";
    const seed = seedFor(printed, 0, declaredFor("all-personal"));
    assert.deepEqual(seed.tokens, [], "tokens were seeded for a line in no section at all");
  });

  test("A VIEW WITH NO PUBLISHED SEED TABLE behaves exactly as it did", () => {
    const seed = seedFor("## All Personal\n", 1, { ...declaredFor("all-personal"), sectionRegistration: undefined });
    assert.deepEqual(seed, null, "the GLOBAL rung answered without a table to answer from");
  });

  test("THE 15 SECTIONS — a rule retypes the capture, so the type tag is refused", () => {
    // RESTATED 2026-08-03: 13 -> 15, when `presentation.json` was regenerated from monorepo
    // `d4c9d98`. The two added are `routines-qntm`'s own sections, from `4b5fd88` (qntm domain
    // surfaces) — the same `routine-without-cadence-becomes-task` rule, on a new domain. The
    // claim is unchanged and the per-section proof below still runs over every one of them.
    const refused = Object.entries(RESOLUTION.dropped)
      .filter(([, why]) => /type tag is not seeded/.test(why))
      .map(([what]) => what)
      .sort();
    assert.equal(refused.length, 15, "the §3.3 count moved; the gate is measuring something else");
    // APPLYING THE DEFAULTS DOES NOT FIX IT, and this is the measurement the design asked for. The
    // rule fires on the ABSENCE of `cadence`, and not one of these 15 sections declares a
    // `defaults:` block that supplies it — so the retype stands whatever the defaults say. The
    // field tags are still seeded; only the type tag is withheld.
    for (const what of refused) {
      const [, viewId, sectionId] = /^section '([^.]+)\.(.+)'$/.exec(what);
      const entry = RESOLUTION.sectionRegistration[viewId][sectionId];
      assert.ok(
        entry.defaults === undefined || !("cadence" in entry.defaults),
        `${what} declares a cadence default — the refusal should have lifted`,
      );
      const engine = TRUTH.seeds.find((s) => s.view === viewId && s.section === sectionId);
      assert.deepEqual(entry.tokens, engine.tokens.slice(1), `${what} withheld more than the type tag`);
    }
  });

  test("A `render_only` TOKEN IS NEVER A SPELLING — the engine would not read it back", () => {
    for (const token of ["☑️", "🎯"]) {
      const what = `vocabulary token '${token}'`;
      assert.ok(what in RESOLUTION.dropped, `${what} was dropped with no record`);
      assert.match(RESOLUTION.dropped[what], /render_only/);
    }
    const spelled = new Set(
      Object.values(RESOLUTION.sectionRegistration).flatMap((sections) =>
        Object.values(sections).flatMap((entry) => entry.tokens),
      ),
    );
    for (const token of ["☑️", "🎯"]) {
      assert.ok(!spelled.has(token), `${token} was seeded into a line the engine refuses to read it from`);
    }
  });

  test("THE CENSUS — which of the 9 declared default fields print, and what happens to the rest", () => {
    // THE MEASUREMENT THE DESIGN ASKED FOR, pinned so the capability record cannot drift from it.
    // SPELLABILITY IS PER (FIELD, VALUE), NOT PER FIELD — `domain` is spelled 160 times and refused
    // 5, because those 5 sections declare `domain: dojo` and no tag spells that value. A per-field
    // summary would have hidden exactly that, which is why this asserts both halves.
    //
    // RESTATED 2026-08-03 with the regeneration from monorepo `d4c9d98`. EIGHT DECLARED FIELDS
    // BECAME NINE: `ec5e0b3` (program assets and defects catalogues) is the first config to put a
    // `status:` default on a section, and it does so on four of them. `domain` went 153 -> 165 and
    // `sectionsWithDefaults` followed it, because seven new views arrived and every one of them
    // declares its domain. The refused set did NOT move — still `project` 60, `stage` 9,
    // `domain` 5 — so nothing newly became unspellable, which is the half that would have mattered.
    const declared = {};
    const spelled = {};
    const unspelled = {};
    let sectionsWithDefaults = 0;
    for (const [viewId, sections] of Object.entries(RESOLUTION.sectionRegistration)) {
      for (const [sectionId, entry] of Object.entries(sections)) {
        if (entry.defaults !== undefined) sectionsWithDefaults += 1;
        for (const field of Object.keys(entry.defaults ?? {})) {
          declared[field] = (declared[field] ?? 0) + 1;
          const what = `section '${viewId}.${sectionId}' default '${field}'`;
          if (what in RESOLUTION.dropped) {
            assert.match(RESOLUTION.dropped[what], /no vocabulary tag spells/);
            unspelled[field] = (unspelled[field] ?? 0) + 1;
          } else {
            spelled[field] = (spelled[field] ?? 0) + 1;
          }
        }
      }
    }
    assert.equal(sectionsWithDefaults, 165, "the 165-section figure moved");
    assert.deepEqual(declared, {
      domain: 165,
      project: 60,
      cap_state: 12,
      principle_state: 10,
      stage: 9,
      class_state: 8,
      package_state: 8,
      status: 4,
      god_box: 2,
    }, "the 9 declared default fields, and their counts, moved");
    assert.deepEqual(spelled, {
      domain: 160,
      cap_state: 12,
      principle_state: 10,
      class_state: 8,
      package_state: 8,
      status: 4,
      god_box: 2,
    }, "what the engine prints a tag for moved");
    // WHAT HAPPENS TO THE REST: nothing is seeded, and every one carries a reason. `project` is the
    // big one — 60 sections declare it, the engine prints no tag for it either, and a browser that
    // wrote it would invent a spelling AND freeze a value the engine goes on deciding invisibly.
    assert.deepEqual(unspelled, { project: 60, stage: 9, domain: 5 }, "what is refused moved");
  });
});

// ── 6. the mutation proof ─────────────────────────────────────────────────────────────────────

describe("6. THE MUTATION PROOF — break the seeding and this file goes red", { skip: MONOREPO }, () => {
  /**
   * Import a MUTATED copy of the generator, with its relative imports rewritten to absolute file
   * URLs so the copy can live outside `scripts/`. Nothing is written into the repository.
   */
  async function withMutatedGenerator(mutate, use) {
    const scratch = mkdtempSync(join(tmpdir(), "present-seed-mutant-"));
    try {
      const source = readFileSync(join(REPO, "scripts", "generate-resolution-declaration.mjs"), "utf8");
      const mutated = mutate(source).replace(
        /from "\.\/([a-z-]+\.mjs)"/g,
        (_, file) => `from "${new URL(`file://${join(REPO, "scripts", file)}`).href}"`,
      );
      assert.notEqual(mutated, source, "the mutation's own anchor is gone — it changed nothing");
      const path = join(scratch, "mutant.mjs");
      writeFileSync(path, mutated);
      return await use(await import(new URL(`file://${path}`).href));
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  }

  test("MUTANT 1: stop seeding the field tags — section 2's agreement goes red", async () => {
    await withMutatedGenerator(
      (source) =>
        source.replace(
          "    if (token !== undefined) tokens.push(token);",
          "    if (token !== undefined && false) tokens.push(token);",
        ),
      (mutant) => {
        const broken = mutant.generateResolution(DEFAULT_CONFIG_DIR, new Ledger());
        const engine = TRUTH.seeds.find((s) => s.view === "all-personal" && s.section === "tasks");
        assert.notDeepEqual(
          broken.sectionRegistration["all-personal"].tasks.tokens,
          engine.tokens,
          "the field tags were removed and the agreement STILL held — it is not measuring them",
        );
      },
    );
  });

  test("MUTANT 2: remove the §3.3 retype gate — section 5's 15-section refusal goes red", async () => {
    await withMutatedGenerator(
      (source) => source.replace("    if (fires) retypedBy = rule;", "    if (fires && false) retypedBy = rule;"),
      (mutant) => {
        const broken = mutant.generateResolution(DEFAULT_CONFIG_DIR, new Ledger());
        const refused = Object.values(broken.dropped).filter((why) => /type tag is not seeded/.test(why));
        assert.equal(refused.length, 0, "the gate was disabled and it still refused — it is not the gate");
        // And the browser would now say `#routine` where the engine will say `#task` — the exact
        // confident-wrong answer §3.3 exists to prevent.
        assert.ok(
          broken.sectionRegistration["routines-personal"]["personal-routines"].tokens.includes("#routine"),
          "the mutant did not reintroduce the wrong answer, so this proves nothing",
        );
      },
    );
  });

  test("MUTANT 3: spell an unspellable field anyway — section 5's refusal goes red", async () => {
    await withMutatedGenerator(
      (source) =>
        source.replace(
          "    if (spelling.fieldTokens[field]?.[String(value)] !== undefined) continue;",
          "    if (true) continue;",
        ),
      (mutant) => {
        const broken = mutant.generateResolution(DEFAULT_CONFIG_DIR, new Ledger());
        const recorded = Object.keys(broken.dropped).filter((what) => /default '/.test(what));
        assert.deepEqual(recorded, [], "the record survived its own removal — it is not the record");
      },
    );
  });
});
