/**
 * present-nodeline-agreement — does `composeNodeLine` produce the line the ENGINE produced, byte
 * for byte, from the same node?
 *
 *   node --test tests/present-nodeline-agreement.test.mjs
 *
 * ── WHY THIS IS A DIFFERENT TEST FROM `composition-agreement` ──
 *
 * That file proves the CELL ORDER: given the cell values the renderer computed, does the declared
 * `composition` reassemble them into the same line? It is handed the cells.
 *
 * This proves the CELLS. It is handed a NODE — a type, some fields, some outgoing edges — and every
 * cell the browser has to derive for itself is in scope: the checkbox glyph, the title wrap, the
 * stamp, the tags and their order, the markers and theirs, the outgoing-edge chrome and its
 * cardinality, and the continuation lines. Eight published tables, joined, against the one thing
 * they are imitating.
 *
 * Without it the composer is a join nobody has ever compared to the engine — the "90% right is
 * worse than none" failure the whole publication effort exists to avoid, because every disagreement
 * would read as a sync bug for weeks.
 *
 * ── THE EXPECTED SIDE IS THE ENGINE'S OWN OUTPUT ──
 *
 * `tests/fixtures/nodeline-agreement.json` is GENERATED by `scripts/nodeline-agreement.py`, which
 * drives the REAL `qntm_md.render.renderer._render_node_line` with the REAL contract dispatchers
 * over the operator's own config. Nothing in it is hand-written: the lines are the engine's.
 *
 * IT ALREADY CAUGHT ONE, ON ITS FIRST RUN. `_resolved_qntm_id` falls back to the node's own `id`
 * when no `qntm_id` field is set, so a node with no id field still stamps — with its uuid. The
 * composer read `fields.qntm_id` alone and emitted no stamp at all for what is most nodes. That is
 * the class of defect this file exists for, and it was invisible to every unit test.
 *
 * ── WHAT IT DELIBERATELY DOES NOT CLAIM ──
 *
 * ONE LINE AT A TIME. Section assembly, ordering between lines, headings and the tree walk are not
 * here — `computeViewMembers` owns membership and ordering, and the caller owns depth. This is the
 * per-line half and nothing more.
 *
 * AND IT NEEDS THE MONOREPO TO REGENERATE, not to run. The comparison below reads the COMMITTED
 * fixture, so it runs on every pull request; only re-deriving the expectations needs the config,
 * the same posture every `*-agreement.py` fixture in this repo already carries.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { composeNodeLine, readConfigResolutionDeclaration } from "../dist/present.js";
import { generateResolution } from "../scripts/generate-resolution-declaration.mjs";
import { MONOREPO_FOUND, DEFAULT_CONFIG_DIR, configDirDiagnostic } from "../scripts/monorepo-config.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = resolve(HERE, "fixtures", "nodeline-agreement.json");
const FIXTURE = existsSync(FIXTURE_PATH) ? JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) : null;

// THE EXPECTATIONS ARE COMMITTED; THE CONFIG THEY WERE DERIVED FROM IS NOT. Skipping is loud rather
// than silent — the first test asserts the fixture exists at all, so a deleted fixture fails here
// instead of turning every assertion below into a pass over an empty list.
const skip = MONOREPO_FOUND ? false : `no monorepo config to compile: ${configDirDiagnostic()}`;

describe("the fixture is the engine's own output, and it is not empty", () => {
  test("the committed fixture exists and covers a real spread of cells", () => {
    assert.ok(FIXTURE, `${FIXTURE_PATH} is missing — run scripts/nodeline-agreement.py`);
    assert.ok(FIXTURE.fixtures.length >= 10, `only ${FIXTURE.fixtures.length} fixtures`);
    const lines = FIXTURE.fixtures.map((f) => f.expectedLine);
    // The same positive controls the generator refuses on, restated here so a hand-edited fixture
    // cannot quietly narrow what this file proves.
    assert.ok(lines.some((l) => l.includes("[x]")), "no ticked checkbox");
    assert.ok(lines.some((l) => l.includes("[ ]")), "no open checkbox");
    assert.ok(lines.some((l) => l.includes("[[qntm:")), "no stamp");
    assert.ok(lines.some((l) => l.includes("**")), "no title wrap");
    assert.ok(lines.some((l) => /📅|⏫|🔽/u.test(l)), "no marker");
    assert.ok(FIXTURE.fixtures.some((f) => f.outgoingEdges.length > 0), "no edge chrome");
    assert.ok(FIXTURE.fixtures.some((f) => f.depth > 0), "no nesting");
  });
});

describe("composeNodeLine reproduces the engine's line, byte for byte", () => {
  test("the published config reads cleanly before anything is composed from it", { skip }, () => {
    const { resolution, problems } = readConfigResolutionDeclaration({
      resolution: generateResolution(DEFAULT_CONFIG_DIR),
    });
    assert.deepEqual(problems, [], "the reader objected to the generator's own output");
    assert.ok(resolution.composition, "no composition to compose with");
  });

  for (const fixture of FIXTURE?.fixtures ?? []) {
    test(`${fixture.id}: ${fixture.expectedLine}`, { skip }, () => {
      const { resolution } = readConfigResolutionDeclaration({
        resolution: generateResolution(DEFAULT_CONFIG_DIR),
      });
      const result = composeNodeLine(fixture.node, {
        resolution,
        writePolicy: fixture.writePolicy,
        outgoingEdges: fixture.outgoingEdges,
        depth: fixture.depth,
      });
      assert.equal(
        result.ok,
        true,
        `refused to compose: ${result.ok === false ? result.because : ""}`,
      );
      assert.equal(result.line.text, fixture.expectedLine);
      assert.deepEqual([...result.line.continuationLines], fixture.expectedContinuationLines);
    });
  }
});

describe("the refusals — a cell it cannot compute is never guessed", () => {
  const table = () =>
    readConfigResolutionDeclaration({ resolution: generateResolution(DEFAULT_CONFIG_DIR) }).resolution;

  test("a node type the config does not declare is refused, not drawn", { skip }, () => {
    const result = composeNodeLine(
      { id: "x", type: "not-a-declared-type", fields: { title: "t" } },
      { resolution: table() },
    );
    assert.equal(result.ok, false);
    assert.equal(result.because, "unknown-node-type");
  });

  test("a missing checkbox table refuses rather than drawing an empty box", { skip }, () => {
    // An invented `[ ]` over a done node is the re-opening defect `renderCheckbox` was published to
    // make impossible — so its absence must stop the line, not soften it.
    const { renderCheckbox: _dropped, ...without } = table();
    const result = composeNodeLine(
      { id: "x", type: "task", fields: { title: "t", status: "done" } },
      { resolution: { ...without, renderCheckbox: undefined } },
    );
    assert.equal(result.ok, false);
    assert.equal(result.because, "no-checkbox-table");
  });

  test("a missing identity mode refuses — both stamp answers are visibly wrong", { skip }, () => {
    const result = composeNodeLine(
      { id: "x", type: "task", fields: { title: "t" } },
      { resolution: { ...table(), identityModes: undefined } },
    );
    assert.equal(result.ok, false);
    assert.equal(result.because, "no-identity-mode");
  });
});
