/**
 * THE DAY BOUNDARY — proof for design-the-resolution-architecture.md step 8.
 *
 *   node --test tests/present-today.test.mjs
 *
 * Seven sections:
 *
 *   1. THE DESIGN DOCUMENT'S OWN FALSIFIER, verbatim, against the operator's REAL declared
 *      boundary (`Europe/London`, `day_start_hour: 4`, `week_starts_on: monday`, read off the
 *      shipped `presentation.json`, never a second-hand copy of the numbers).
 *   2. THE AGREEMENT TEST (proof standard #3) — `tests/fixtures/day-boundary-agreement.json` is
 *      GENERATED by `scripts/day-boundary-agreement.py` calling the engine's OWN
 *      `qntm_md.substrate_wiring.day_boundary.resolve_logical_day`/`resolve_week_end`, never
 *      transcribed. `todayFor` is asked the SAME instants and must agree — both DST regimes
 *      Europe/London carries, and both 2026 DST transition days, a genuine stress of the
 *      `Intl`-based zone read, not just the hour arithmetic.
 *   3. THE CLOCK-POISONING PROOF (proof standard #2, this step's own form of it) — `today.ts`
 *      never calls `Date.now()` itself; poisoning it to throw does not stop `todayFor` answering.
 *      Separately, feeding `todayFor` a POISONED clock value that straddles the boundary produces
 *      the correct pre/post-rollover answer, and the SAME poisoned instant under a DIFFERENT
 *      declared boundary produces a DIFFERENT answer — proving the result tracks the declared
 *      boundary, not a hardcoded assumption baked into the resolver.
 *   4. THE DEVICE-LOCAL-TIMEZONE DIVERGENCE — the crux, made concrete: the SAME instant resolved
 *      against the operator's declared zone and against an arbitrary device-local zone disagrees,
 *      which is exactly why this module takes `boundary.timezone` as data and never reads the
 *      device's own default zone.
 *   5. REFUSALS, NAMED — an unresolvable timezone and an unrecognised `weekStartsOn` each abstain,
 *      never throw.
 *   6. THE CONFIG-CHANGE FALSIFIER (proof standard #4) — mutate `day_boundary.yaml` in a scratch
 *      copy of the real config, regenerate, and feed the regenerated table to `todayFor`: the
 *      SAME instant now resolves to a DIFFERENT logical date.
 *   7. NOTHING LOCAL REACHES A WRITE — `today.ts`'s own imports, the same shape
 *      `tests/present-ordering.test.mjs` §6 already established for `ordering.ts`.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { resolveLogicalDate, resolveWeekEnd, todayFor } from "../dist/present.js";
import { generateResolution, DEFAULT_CONFIG_DIR } from "../scripts/generate-resolution-declaration.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVED = JSON.parse(readFileSync(resolve(HERE, "..", "presentation.json"), "utf8"));
const REAL_BOUNDARY = SERVED.resolution.dayBoundary;

const isoToMs = (iso) => new Date(iso).getTime();

describe("1. the design document's own falsifier, against the real declared boundary", () => {
  test("03:59 Europe/London returns yesterday's date", () => {
    // 2026-06-23T02:59:00Z is 03:59 BST (Europe/London is UTC+1 in June).
    const reading = todayFor(isoToMs("2026-06-23T02:59:00Z"), REAL_BOUNDARY);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.logicalDate, "2026-06-22");
  });

  test("04:01 Europe/London returns today's date", () => {
    // 2026-06-23T03:01:00Z is 04:01 BST.
    const reading = todayFor(isoToMs("2026-06-23T03:01:00Z"), REAL_BOUNDARY);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.logicalDate, "2026-06-23");
  });

  test("a Sunday resolves into the week that started the preceding Monday", () => {
    // 2026-07-05 is a Sunday. The preceding Monday is 2026-06-29; that week ends 2026-07-05.
    const reading = todayFor(isoToMs("2026-07-05T12:00:00Z"), REAL_BOUNDARY);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.logicalDate, "2026-07-05");
    assert.equal(reading.answer.weekEnd, "2026-07-05", "Sunday is the last day of its own week");
  });

  test("the exact boundary instant (04:00:00 local) belongs to the NEW day, not the old one", () => {
    const reading = todayFor(isoToMs("2026-06-23T03:00:00Z"), REAL_BOUNDARY);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.logicalDate, "2026-06-23");
  });
});

describe("2. THE AGREEMENT TEST — generated from the engine's own resolve_logical_day/resolve_week_end", () => {
  const fixturePath = resolve(HERE, "fixtures", "day-boundary-agreement.json");
  const FIXTURE = JSON.parse(readFileSync(fixturePath, "utf8"));

  test("the fixture is not empty (a positive control on the fixture itself)", () => {
    assert.ok(FIXTURE.cases.length >= 10, `only ${FIXTURE.cases.length} cases — regenerate?`);
  });

  test(`all ${FIXTURE.cases.length} engine-generated instants agree with todayFor`, () => {
    for (const c of FIXTURE.cases) {
      const boundary = {
        timezone: c.boundary.timezone,
        dayStartHour: c.boundary.dayStartHour,
        weekStartsOn: c.boundary.weekStartsOn,
      };
      const reading = todayFor(isoToMs(c.nowUtcIso), boundary);
      assert.equal(
        reading.kind,
        "answer",
        `${c.nowUtcIso} under ${JSON.stringify(boundary)} (${c.reason}): todayFor abstained`,
      );
      assert.equal(
        reading.answer.logicalDate,
        c.logicalDate,
        `${c.nowUtcIso} (${c.reason}): logicalDate ${reading.answer.logicalDate} != engine ${c.logicalDate}`,
      );
      assert.equal(
        reading.answer.weekEnd,
        c.weekEnd,
        `${c.nowUtcIso} (${c.reason}): weekEnd ${reading.answer.weekEnd} != engine ${c.weekEnd}`,
      );
    }
  });

  test("positive control: the fixture actually covers both sides of a rollover (not all-same-date)", () => {
    const realCases = FIXTURE.cases.filter(
      (c) =>
        c.boundary.timezone === "Europe/London" &&
        c.boundary.dayStartHour === 4 &&
        c.boundary.weekStartsOn === "monday",
    );
    const dates = new Set(realCases.map((c) => c.logicalDate));
    assert.ok(dates.size >= 2, "every REAL-boundary case resolved to the same date — broken fixture");
  });

  test("positive control: both 2026 DST transition days are covered", () => {
    const days = FIXTURE.cases.map((c) => c.nowUtcIso.slice(0, 10));
    assert.ok(days.includes("2026-03-29"), "spring-forward transition day missing from the fixture");
    assert.ok(days.includes("2026-10-25"), "fall-back transition day missing from the fixture");
  });
});

describe("3. THE CLOCK-POISONING PROOF — the answer moves with the declared boundary, not the raw wall clock", () => {
  test("todayFor never reads Date.now() itself — poisoning it does not stop a correct answer", () => {
    const saved = Date.now;
    Date.now = () => {
      throw new Error("todayFor reached the wall clock directly — it must take the instant as a parameter");
    };
    try {
      const reading = todayFor(isoToMs("2026-06-23T03:01:00Z"), REAL_BOUNDARY);
      assert.equal(reading.kind, "answer");
      assert.equal(reading.answer.logicalDate, "2026-06-23");
    } finally {
      Date.now = saved;
    }
  });

  test("a POISONED Date.now(), fed through the call site, tracks the declared rollover correctly", () => {
    const saved = Date.now;
    try {
      // Poison the clock to 03:59 local, then to 04:01 local — the exact falsifier instants —
      // and prove that `todayFor(Date.now(), boundary)`, the shape a real call site would use,
      // produces the pre- and post-rollover answers respectively.
      Date.now = () => isoToMs("2026-06-23T02:59:00Z");
      assert.equal(todayFor(Date.now(), REAL_BOUNDARY).answer.logicalDate, "2026-06-22");

      Date.now = () => isoToMs("2026-06-23T03:01:00Z");
      assert.equal(todayFor(Date.now(), REAL_BOUNDARY).answer.logicalDate, "2026-06-23");
    } finally {
      Date.now = saved;
    }
  });

  test("the SAME poisoned instant under a DIFFERENT declared boundary gives a DIFFERENT answer", () => {
    const saved = Date.now;
    try {
      // 02:00 BST — after UTC midnight, before the REAL config's 04:00 rollover.
      Date.now = () => isoToMs("2026-06-23T01:00:00Z");
      const withRealBoundary = todayFor(Date.now(), REAL_BOUNDARY);
      const withLegacyBoundary = todayFor(Date.now(), {
        timezone: "Europe/London",
        dayStartHour: 0,
        weekStartsOn: "monday",
      });
      assert.equal(withRealBoundary.answer.logicalDate, "2026-06-22", "still yesterday under 04:00 rollover");
      assert.equal(withLegacyBoundary.answer.logicalDate, "2026-06-23", "already today under midnight rollover");
      assert.notEqual(
        withRealBoundary.answer.logicalDate,
        withLegacyBoundary.answer.logicalDate,
        "the SAME clock reading produced the SAME answer under two different declared boundaries — " +
          "the resolver is not actually reading the boundary it was handed",
      );
    } finally {
      Date.now = saved;
    }
  });
});

describe("4. THE CRUX — a device-local timezone is not the declared one, and the answer diverges", () => {
  test("the same instant, read against the operator's declared zone vs an arbitrary device zone, disagrees", () => {
    // 2026-06-23T03:30:00Z: 04:30 in Europe/London (BST, PAST the 04:00 rollover — already
    // 06-23) but 20:30 the PREVIOUS evening in America/Los_Angeles (PDT, UTC-7, past ITS OWN
    // 04:00 rollover too, so still 06-22) — a device set to Pacific time computing "today" from
    // ITS OWN local clock disagrees with the operator's declared boundary about which CALENDAR
    // DAY it is, a full day apart, not merely a few hours either side of a shared rollover.
    const instant = isoToMs("2026-06-23T03:30:00Z");
    const declared = todayFor(instant, REAL_BOUNDARY);
    const deviceLocal = todayFor(instant, {
      timezone: "America/Los_Angeles",
      dayStartHour: 4,
      weekStartsOn: "monday",
    });
    assert.equal(declared.answer.logicalDate, "2026-06-23");
    assert.equal(deviceLocal.answer.logicalDate, "2026-06-22");
    assert.notDeepEqual(
      declared,
      deviceLocal,
      "reading the boundary against two different zones for the same instant must not silently agree",
    );
  });
});

describe("5. REFUSALS — a malformed boundary abstains, it never throws", () => {
  test("an unresolvable timezone abstains 'unresolvable-timezone'", () => {
    const reading = todayFor(isoToMs("2026-06-23T12:00:00Z"), {
      timezone: "Not/A_Real_Zone",
      dayStartHour: 4,
      weekStartsOn: "monday",
    });
    assert.deepEqual(reading, { kind: "abstains", because: "unresolvable-timezone" });
  });

  test("resolveLogicalDate alone abstains (undefined) for the same input", () => {
    assert.equal(
      resolveLogicalDate(isoToMs("2026-06-23T12:00:00Z"), {
        timezone: "Not/A_Real_Zone",
        dayStartHour: 4,
        weekStartsOn: "monday",
      }),
      undefined,
    );
  });

  test("an unrecognised weekStartsOn abstains 'unknown-week-start'", () => {
    const reading = todayFor(isoToMs("2026-06-23T12:00:00Z"), {
      timezone: "Europe/London",
      dayStartHour: 4,
      weekStartsOn: "someday",
    });
    assert.deepEqual(reading, { kind: "abstains", because: "unknown-week-start" });
  });

  test("resolveWeekEnd alone abstains (undefined) for the same input", () => {
    assert.equal(resolveWeekEnd("2026-06-23", "someday"), undefined);
  });

  test("weekStartsOn is matched case- and whitespace-insensitively, mirroring the engine", () => {
    assert.equal(resolveWeekEnd("2026-07-03", "  Monday  "), resolveWeekEnd("2026-07-03", "monday"));
  });
});

const monorepo = existsSync(DEFAULT_CONFIG_DIR);
const skip = monorepo ? false : `monorepo not checked out at ${DEFAULT_CONFIG_DIR}`;

describe("6. THE CONFIG-CHANGE FALSIFIER — mutate day_boundary.yaml in a scratch copy, the answer follows", () => {
  test("BASELINE: the real config's day_start_hour is 4", { skip }, () => {
    assert.equal(generateResolution(DEFAULT_CONFIG_DIR).dayBoundary.dayStartHour, 4);
  });

  test("MUTATE day_start_hour to 6: the SAME instant now resolves to a DIFFERENT logical date", { skip }, () => {
    const before = todayFor(isoToMs("2026-06-23T03:30:00Z"), generateResolution(DEFAULT_CONFIG_DIR).dayBoundary);
    // 03:30 UTC == 04:30 BST: past the real 04:00 rollover (today), before a 06:00 rollover (yesterday).
    assert.equal(before.answer.logicalDate, "2026-06-23");

    const scratch = mkdtempSync(join(tmpdir(), "day-boundary-falsifier-"));
    let after;
    try {
      const configDir = join(scratch, "config");
      cpSync(DEFAULT_CONFIG_DIR, configDir, { recursive: true });
      const path = join(configDir, "day_boundary.yaml");
      const original = readFileSync(path, "utf8");
      const mutated = original.replace("day_start_hour: 4", "day_start_hour: 6");
      assert.notEqual(mutated, original, "the falsifier's own edit did not apply");
      writeFileSync(path, mutated);
      const mutatedBoundary = generateResolution(configDir).dayBoundary;
      after = todayFor(isoToMs("2026-06-23T03:30:00Z"), mutatedBoundary);
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
    assert.equal(after.answer.logicalDate, "2026-06-22", "04:30 local is before a 06:00 rollover");
    assert.notEqual(
      before.answer.logicalDate,
      after.answer.logicalDate,
      "the published day_start_hour changed but todayFor's answer for the same instant did not",
    );
  });

  test("MUTATE week_starts_on to sunday: the SAME logical date now ends a different week", { skip }, () => {
    const before = generateResolution(DEFAULT_CONFIG_DIR).dayBoundary;
    assert.equal(resolveWeekEnd("2026-07-05", before.weekStartsOn), "2026-07-05");

    const scratch = mkdtempSync(join(tmpdir(), "day-boundary-falsifier-"));
    let mutatedBoundary;
    try {
      const configDir = join(scratch, "config");
      cpSync(DEFAULT_CONFIG_DIR, configDir, { recursive: true });
      const path = join(configDir, "day_boundary.yaml");
      const original = readFileSync(path, "utf8");
      const mutated = original.replace("week_starts_on: monday", "week_starts_on: sunday");
      assert.notEqual(mutated, original, "the falsifier's own edit did not apply");
      writeFileSync(path, mutated);
      mutatedBoundary = generateResolution(configDir).dayBoundary;
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
    assert.equal(resolveWeekEnd("2026-07-05", mutatedBoundary.weekStartsOn), "2026-07-11");
  });
});

describe("7. NOTHING LOCAL REACHES A WRITE — today.ts's own imports", () => {
  test("today.ts imports nothing from source.ts, context.ts, cascade.ts or the DOM", () => {
    const src = readFileSync(resolve(HERE, "..", "app", "present", "today.ts"), "utf8");
    const importLines = src.split(/\r?\n/).filter((line) => /^\s*import\b/.test(line));
    assert.ok(importLines.length > 0, "expected at least the DayBoundary type import");
    for (const line of importLines) {
      assert.doesNotMatch(
        line,
        /["']\.\/(source|context|cascade|paint)\.js["']/,
        `today.ts imports the edit, cascade or paint path: ${line.trim()}`,
      );
    }
  });

  test("today.ts's only import is resolutiontable.ts's DayBoundary TYPE — no runtime module dependency", () => {
    const src = readFileSync(resolve(HERE, "..", "app", "present", "today.ts"), "utf8");
    const importLines = src.split(/\r?\n/).filter((line) => /^\s*import\b/.test(line));
    assert.equal(importLines.length, 1);
    assert.match(importLines[0], /^import type \{ DayBoundary \} from "\.\/resolutiontable\.js";$/);
  });
});
