/**
 * present-viewmembers-agreement — does `computeViewMembers` put a node in the same VIEW SECTIONS
 * the ENGINE would?
 *
 * ── WHY THIS IS A DIFFERENT TEST FROM `qualification-agreement` ──
 *
 * That test proves one thing: for a field triple, the app's `matchesQualifier` names the same
 * PATTERNS the engine's `matches_pattern` does. It is per-pattern, and it stops there.
 *
 * A view is not a pattern. It is a section list, each section naming a pattern, in a declared order
 * — and the join from section to pattern is a second place the browser can be wrong while every
 * pattern answer is right. A section pointing at the wrong predicate, a section silently dropped, a
 * member landing in two sections that should be exclusive: none of those are visible per-pattern.
 * This file lifts the same engine truth one level up, to the thing the operator actually looks at.
 *
 * ── THE EXPECTED SIDE IS THE ENGINE'S, NOT A TRANSCRIPTION ──
 *
 * `tests/fixtures/qualification-agreement.json` is GENERATED by `scripts/qualification-agreement.py`
 * calling `qntm_graph.patterns.engine.matches_pattern` over a read-only copy of the operator's real
 * `state.db` — 1501 nodes collapsing to 61 distinct (node_type, domain, status) triples, because
 * that triple is everything the browser can resolve. Nothing here is hand-written: the triples are
 * his, the answers are the engine's, and this file only asks whether a view built from them agrees.
 *
 * ── WHAT IT DELIBERATELY DOES NOT CLAIM ──
 *
 * MEMBERSHIP ONLY, and only for self-only patterns. The fixture excludes `graphDependentPatterns`
 * (28 of them) by construction — two nodes with one triple can have different edges, so "one input,
 * one answer" fails and the generator refuses to emit a truth it cannot key. `computeViewMembers`
 * names those sections `needs-graph` rather than answering, so there is no wrong answer here to
 * catch; agreement for them needs a real graph on both sides and is a later leg's proof.
 *
 * ORDER IS NOT PROVEN HERE EITHER. A triple has no `due_date`, `priority` or `title`, so this
 * fixture cannot rank two nodes. The ordering half is proven separately, below, against the config's
 * own declared keys — and the full engine ordering differential needs a real graph, which this
 * fixture is not.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  readQualificationDeclaration,
  readConfigResolutionDeclaration,
  computeViewMembers,
} from "../dist/present.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const read = (path) => JSON.parse(readFileSync(resolve(HERE, path), "utf8"));

const SERVED = read("../presentation.json");
const TRUTH = read("./fixtures/qualification-agreement.json");
const LANGUAGE = readQualificationDeclaration(SERVED).qualification;
const RESOLUTION = readConfigResolutionDeclaration(SERVED).resolution;

const ORDERING = {
  ordering: RESOLUTION.ordering,
  orderingFields: RESOLUTION.orderingFields,
  defaultOrdering: RESOLUTION.defaultOrdering,
  priorityRank: RESOLUTION.priorityRank,
};

/** The patterns the engine answered for — self-only, so a triple determines the answer. */
const SELF_ONLY = new Set(TRUTH.patterns);

/** Every (viewId, sectionId) whose qualification is one of those, i.e. every section this fixture
 * can hold to account. */
const CHECKABLE = [];
for (const [viewId, sections] of Object.entries(LANGUAGE.sections)) {
  for (const [sectionId, section] of Object.entries(sections)) {
    if (SELF_ONLY.has(section.qualification)) {
      CHECKABLE.push({ viewId, sectionId, qualification: section.qualification });
    }
  }
}

describe("the fixture and the declaration are about the same config", () => {
  test("there are sections to hold to account, and they span many views", () => {
    // A guard against this whole file quietly becoming vacuous if the config or the fixture moves —
    // zero checkable sections would make every assertion below pass by iterating nothing.
    assert.ok(CHECKABLE.length > 20, `only ${CHECKABLE.length} checkable sections`);
    const views = new Set(CHECKABLE.map((c) => c.viewId));
    assert.ok(views.size > 5, `only ${views.size} views covered`);
  });

  test("the engine answered over real triples, not a toy set", () => {
    assert.ok(TRUTH.rows.length > 20, `only ${TRUTH.rows.length} triples`);
    assert.equal(typeof TRUTH.nodes, "number");
    assert.ok(TRUTH.nodes > 1000, "the fixture should come from the operator's real graph");
  });
});

describe("a node lands in exactly the sections the engine says it qualifies for", () => {
  for (const [index, row] of TRUTH.rows.entries()) {
    const matched = new Set(TRUTH.matchSets[row.matches] ?? []);
    const fields = row.fields;

    test(`triple ${index}: ${JSON.stringify(fields)}`, () => {
      // `node_type` is the node's TYPE on the wire, not a field — `candidateFieldsOf` puts it back
      // as `node_type`, so the node is built the way the graph actually carries it.
      const { node_type: nodeType, ...rest } = fields;
      const node = { id: "probe", type: nodeType, fields: { ...rest, title: "probe" } };

      const computedByView = new Map();
      for (const viewId of new Set(CHECKABLE.map((c) => c.viewId))) {
        computedByView.set(viewId, computeViewMembers(viewId, [node], LANGUAGE, ORDERING));
      }

      for (const { viewId, sectionId, qualification } of CHECKABLE) {
        const computed = computedByView.get(viewId);
        const section = computed?.sections.find((s) => s.sectionId === sectionId);
        if (section === undefined) continue; // named in `uncomputed` with a reason; not this test's subject

        const present = section.members.some((m) => m.id === "probe");
        const expected = matched.has(qualification);
        assert.equal(
          present,
          expected,
          expected
            ? `the engine says this node qualifies for '${qualification}' but ${viewId}/${sectionId} left it out`
            : `the engine says this node does NOT qualify for '${qualification}' but ${viewId}/${sectionId} included it`,
        );
      }
    });
  }
});

describe("the declared-ordering path actually sorts, not just resolves", () => {
  // THE THINNEST PATH IN THE CONFIG AND THEREFORE THE EASIEST PLACE FOR A WRONG COMPARATOR TO HIDE:
  // 6 views of 83 declare an ordering, so 77 exercise the default and this branch is barely walked.
  // The earlier suite asserted the config JOIN here (the key is published, the predicate exists) and
  // stopped short of asserting a sorted RESULT. This does the sort.
  const declaredSections = [];
  for (const [viewId, sections] of Object.entries(ORDERING.ordering)) {
    for (const [sectionId, declared] of Object.entries(sections)) {
      const keys = declared.ordering;
      if (!keys || keys.length === 0) continue; // insertion_order and friends: no field sort to prove
      const qualification = LANGUAGE.sections[viewId]?.[sectionId]?.qualification;
      const qualifier = qualification ? LANGUAGE.predicates[qualification] : undefined;
      if (qualifier === undefined) continue;
      declaredSections.push({ viewId, sectionId, keys, qualifier });
    }
  }

  test("there is at least one declared-ordering section to prove", () => {
    assert.ok(declaredSections.length > 0, "no declared ordering in this config — nothing proven");
  });

  for (const { viewId, sectionId, keys, qualifier } of declaredSections) {
    test(`${viewId}/${sectionId} sorts by ${keys.map((k) => `${k.field} ${k.direction}`).join(", ")}`, () => {
      // Build nodes that satisfy the section's own predicate, so they genuinely qualify rather than
      // being forced into the section — the sort is only meaningful over real members.
      const find = qualifier.find ?? {};
      const base = { title: "probe" };
      for (const [field, clause] of Object.entries(find.fields ?? {})) {
        if (clause && typeof clause === "object" && "eq" in clause) base[field] = clause.eq;
      }
      const type = find.nodeType?.[0];
      if (type === undefined) return; // predicate does not pin a type; cannot build a qualifying node

      const key = keys[0];
      const marker = ORDERING.orderingFields[key.field];
      if (marker === undefined || marker.kind === "enum") return; // compareTuples never learned priorityRank

      const low = marker.kind === "date" ? "2026-01-01" : 1;
      const high = marker.kind === "date" ? "2026-12-31" : 99;
      const nodes = [
        { id: "high", type, fields: { ...base, [key.field]: high } },
        { id: "low", type, fields: { ...base, [key.field]: low } },
      ];

      const computed = computeViewMembers(viewId, nodes, LANGUAGE, ORDERING);
      const section = computed?.sections.find((s) => s.sectionId === sectionId);
      if (section === undefined || section.members.length !== 2) return; // needs-graph or needs-clock; named elsewhere

      assert.equal(section.ordered, true, "a declared ordering that resolved must report ordered");
      const expected = key.direction === "desc" ? ["high", "low"] : ["low", "high"];
      assert.deepEqual(
        section.members.map((m) => m.id),
        expected,
        `declared ${key.field} ${key.direction} did not sort`,
      );
    });
  }
});

describe("the only `desc` in the whole config", () => {
  // MEASURED, not assumed: every DECLARED ordering key in this config is `asc`
  // (available_date, due_date, queue_position). The single `desc` anywhere is `priority desc` in
  // `defaultOrdering`, and `priority` is the one ENUM field — resolved through `priorityRank`
  // rather than compared as a value. So this branch is reachable, is walked by 77 of 83 views, and
  // was covered by nothing until this test. A direction bug and a rank-table bug both live here.
  test("every declared ordering key in this config is asc — so desc is only reachable by default", () => {
    for (const sections of Object.values(ORDERING.ordering)) {
      for (const declared of Object.values(sections)) {
        for (const key of declared.ordering ?? []) {
          assert.equal(key.direction, "asc", `a declared key is now ${key.direction} — cover it above`);
        }
      }
    }
    assert.ok(
      ORDERING.defaultOrdering.some((k) => k.direction === "desc"),
      "the default ordering no longer carries a desc key — this test has nothing left to prove",
    );
  });

  test("priority desc puts the higher rank first, through priorityRank", () => {
    const ranks = ORDERING.priorityRank;
    const entries = Object.entries(ranks).sort((a, b) => a[1] - b[1]);
    const lowest = entries[0];
    const highest = entries[entries.length - 1];
    assert.ok(highest[1] > lowest[1], "priorityRank has no spread to sort by");

    // Neither carries a due_date, so key 0 ties at tier 1 and the comparison falls to priority.
    const nodes = [
      { id: "low", type: "task", fields: { domain: "arts", title: "a", priority: lowest[0] } },
      { id: "high", type: "task", fields: { domain: "arts", title: "z", priority: highest[0] } },
    ];
    const computed = computeViewMembers("all-arts", nodes, LANGUAGE, ORDERING);
    const section = computed.sections.find((s) => s.sectionId === "tasks");
    assert.equal(section.members.length, 2, "both probes should qualify for all-arts/tasks");
    assert.deepEqual(
      section.members.map((m) => m.id),
      ["high", "low"],
      `${highest[0]} (rank ${highest[1]}) must sort before ${lowest[0]} (rank ${lowest[1]}) under priority desc — ` +
        "and note the titles say the opposite, so a fallthrough to title would fail this",
    );
  });

  test("an unranked priority value is absent, not rank zero", () => {
    // tier 1 (absent) vs tier 0 (present): a value `priorityRank` does not know must sort AFTER a
    // known one regardless of direction, never be silently treated as the lowest rank.
    const known = Object.entries(ORDERING.priorityRank).sort((a, b) => a[1] - b[1])[0];
    const nodes = [
      { id: "unknown", type: "task", fields: { domain: "arts", title: "a", priority: "not-a-real-priority" } },
      { id: "known", type: "task", fields: { domain: "arts", title: "z", priority: known[0] } },
    ];
    const computed = computeViewMembers("all-arts", nodes, LANGUAGE, ORDERING);
    const section = computed.sections.find((s) => s.sectionId === "tasks");
    assert.deepEqual(section.members.map((m) => m.id), ["known", "unknown"]);
  });
});
