/**
 * ORDERING PREVIEW — proof for design-the-resolution-architecture.md step 7.
 *
 *   node --test tests/present-ordering.test.mjs
 *
 * ── SEVEN SECTIONS ──
 *
 *   1. THE DESIGN DOCUMENT'S OWN FALSIFIER, ADAPTED ON MEASURED EVIDENCE, ARGUED RATHER THAN
 *      SILENTLY NARROWED. It reads: "for `this-week`'s four sections, assert the browser's sort of
 *      the currently painted rows equals the order those rows appear in the served markdown." Run
 *      literally against the three FLAT `queue` sections, it holds — proven below, against real
 *      content, with `queue_position` reaching two digits as a positive control against a STRING-
 *      comparison bug. Run literally against `this-week`'s four sections it does NOT hold, and
 *      §1b proves why with a citation rather than an assumption: the engine's own
 *      `_order_children` (`section_builder.py:337-341`) places every ANCESTOR/context row ahead of
 *      every ordering-sorted QUALIFYING row at each tree level, so a flat whole-section rank is
 *      the wrong model the moment a section prints any nested row — which all four `this-week`
 *      sections do (they pull in `#outcome` ancestors). `orderingFor`'s adapted falsifier is
 *      therefore: it refuses (`nested-section`) for exactly the shape that broke the literal one,
 *      proven against the SAME real content that broke it.
 *   2. A TEST AGAINST HIS REAL CONFIG: an edit that changes the ordered field in a flat one of the
 *      9 sections says so; an edit in one of the other 177 is silent.
 *   3. EVERY REFUSAL PATH PRODUCES SILENCE — all five `OrderingAbstention` values.
 *   4. THE CONFIG-CHANGE FALSIFIER (proof standard #5) lives in `tests/present-resolution.test.mjs`
 *      §4 (`generateResolution`'s own scratch-copy mutations) — restated here is only the SHAPE the
 *      published table takes when `direction` flips, proving `orderingFor` itself (not just the
 *      generator) follows a declaration whose direction changed.
 *   5. THE MEASUREMENT THAT DECIDES THE STEP-8 DEPENDENCY — restated as a runnable claim: an
 *      ordering answer needs no clock. `Date.now` is poisoned for the whole file's "answer" path.
 *   6. THE NOTHING-LOCAL-REACHES-A-WRITE PROOF for this module specifically — no import of
 *      `source.ts`, no `Contribution` produced.
 *   7-9. `orderingPlacementFor` — roadmap-the-road-ahead.md step 3's "make it place the row" —
 *      §7 proves agreement with an INDEPENDENTLY built stable-sort expectation over his real
 *      config, and that `moved` never disagrees with `orderingFor`'s own answer, over every
 *      declared section; §8 proves the two functions abstain for the IDENTICAL reason, always;
 *      §9 proves the tie-break claim (a stable sort's guarantee, not an assumption) over invented
 *      config his real sections do not currently exercise.
 *
 * WHAT THIS FILE DOES NOT COVER: no DOM, no `app/index.html` wiring (that is
 * `tests/app-ordering-note.test.mjs`), no browser.
 *
 * ── ONE DEPENDENCY THIS FILE HAS THAT NO OTHER TEST FILE HAS ──
 *
 * §1 and §1b read the operator's LIVE VAULT — `~/qntm/this_week.md` and `~/qntm/dev/qntm/queue.md`
 * — read-only, guarded by `existsSync`, so they SKIP on CI and RUN only on his own machine. That
 * is deliberate: "against real content" is the whole evidentiary claim, and a committed fixture
 * would prove something weaker.
 *
 * The cost is that those files are regenerated by the engine every cycle from whatever his week
 * actually contains, so the SHAPES these tests measure are not guaranteed to exist on the day the
 * suite runs. On 2026-08-03 two of them went red for exactly that reason and for no other: one
 * section had emptied, another had gone flat. Both reported an engine finding when nothing about
 * the engine had moved.
 *
 * So every claim here that needs a particular shape now CHECKS FOR THAT SHAPE FIRST and, when the
 * content cannot answer, prints a `PRECONDITION NOT MET` diagnostic and measures nothing. None of
 * the assertions were relaxed. If you are reading a green run of this file, read its diagnostics
 * too — a claim that did not measure is not a claim that passed.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  orderingFor,
  orderingPlacementFor,
  defaultOrderingFor,
  defaultOrderingPlacementFor,
  resolveOrderingFor,
  resolveOrderingPlacementFor,
  markerValue,
  classifyLine,
} from "../dist/present.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVED = JSON.parse(readFileSync(resolve(HERE, "..", "presentation.json"), "utf8"));
const ORDERING = SERVED.resolution.ordering;
const ORDERING_FIELDS = SERVED.resolution.orderingFields;
const DEFAULT_ORDERING = SERVED.resolution.defaultOrdering;
const PRIORITY_RANK = SERVED.resolution.priorityRank;

const vaultDir = join(homedir(), "qntm");
const vaultAvailable = existsSync(vaultDir);
const skipVault = vaultAvailable ? false : `vault not checked out at ${vaultDir}`;

/**
 * Every content line's marker value for `field`, in DOCUMENT ORDER, SCOPED TO ONE SECTION (the
 * lines strictly between the heading whose text is `heading` and the next heading) and skipping
 * lines without a value. Scoping matters because `this_week.md` carries FOUR headings.
 */
function markerValuesInDocumentOrder(source, heading, field) {
  const marker = ORDERING_FIELDS[field];
  assert.ok(marker, `no published marker for '${field}' — the fixture this test reads is wrong`);
  const lines = source.split("\n");
  const startAt = lines.findIndex((l) => classifyLine(l).kind === "heading" && classifyLine(l).text === heading);
  assert.ok(startAt !== -1, `no '## ${heading}' heading found — the fixture no longer matches`);
  const values = [];
  for (let at = startAt + 1; at < lines.length; at += 1) {
    if (classifyLine(lines[at]).kind === "heading") break;
    const value = markerValue(lines[at], marker);
    if (value !== undefined) values.push(value);
  }
  return values;
}

/**
 * The non-blank content lines under `heading`, each with its indent depth.
 *
 * This exists for ONE purpose: to let a test state out loud whether the live vault currently
 * carries the SHAPE that test measures, instead of asserting into content that cannot answer.
 */
function contentLinesUnder(source, heading) {
  const lines = source.split("\n");
  const startAt = lines.findIndex(
    (l) => classifyLine(l).kind === "heading" && classifyLine(l).text === heading,
  );
  if (startAt === -1) return [];
  const under = [];
  for (let at = startAt + 1; at < lines.length; at += 1) {
    if (classifyLine(lines[at]).kind === "heading") break;
    if (lines[at].trim() === "") continue;
    under.push({ line: lines[at], indent: lines[at].length - lines[at].trimStart().length });
  }
  return under;
}

/** Whether the section currently prints at least one row indented under another row. */
function hasNestedRow(source, heading) {
  const under = contentLinesUnder(source, heading);
  if (under.length === 0) return false;
  const shallowest = Math.min(...under.map((u) => u.indent));
  return under.some((u) => u.indent > shallowest);
}

function sortedAscending(values, kind) {
  const copy = [...values];
  if (kind === "int") copy.sort((a, b) => Number(a) - Number(b));
  else copy.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  return copy;
}

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 1a. THE FLAT CASE — the design falsifier holds exactly as written, against real content
// ══════════════════════════════════════════════════════════════════════════════════════════════

const QUEUE_CASES = [
  { view: "flowtrace-queue", section: "queue", path: "dev/flow-trace/queue.md" },
  { view: "qntm-queue", section: "queue", path: "dev/qntm/queue.md" },
  { view: "trace-orchestration-queue", section: "queue", path: "dev/trace-orchestration/queue.md" },
];

describe("1a. THE FALSIFIER, LITERALLY, ON THE THREE `queue` SECTIONS' DOCUMENT ORDER", () => {
  // This claim ("printed order already matches ascending queue_position") does not need a section
  // to be perfectly flat — a prose "#summary" child carries no 🔢 and is excluded from the value
  // sequence either way (the same exclusion §3's "marker-less sibling" test proves). Whether
  // `orderingFor` will PREVIEW an edit in a section is a stricter, separate question — measured
  // right after this block, because it turned out NOT all three are flat.
  for (const { view, section, path } of QUEUE_CASES) {
    test(`${view}.${section}: printed rows are already queue_position order, ascending`, { skip: skipVault }, () => {
      assert.equal(ORDERING[view]?.[section]?.name, "Queue");
      const source = readFileSync(join(vaultDir, path), "utf8");
      const documentOrder = markerValuesInDocumentOrder(source, "Queue", "queue_position");
      assert.ok(documentOrder.length > 1, `positive control failed — ${path} yielded < 2 values`);
      const sorted = sortedAscending(documentOrder, "int");
      assert.deepEqual(documentOrder, sorted, `${path}'s printed order does not match ascending queue_position`);
    });
  }

  test("POSITIVE CONTROL: queue_position genuinely reaches two digits in real content", { skip: skipVault }, () => {
    // Without this, a STRING comparison ("10" < "2") could pass every case above by accident.
    const source = readFileSync(join(vaultDir, "dev/flow-trace/queue.md"), "utf8");
    const values = markerValuesInDocumentOrder(source, "Queue", "queue_position").map(Number);
    assert.ok(Math.max(...values) >= 10, "no real queue reached two digits — the trap was not exercised");
  });

  test("MEASURED: exactly 2 of the 3 queue sections are FLAT (zero indentation) today", { skip: skipVault }, () => {
    // qntm-queue.md interleaves a prose "#summary" child under some items (found while writing
    // this test, not assumed) — harmless to the document-order claim above, but it DOES mean
    // `orderingFor`'s conservative nested-section refusal fires there too, same as this-week's
    // sections, for the same reason: this module cannot be sure a summary child could never
    // confuse a rank comparison without the deeper analysis it declines to attempt.
    const flatness = {};
    for (const { view, path } of QUEUE_CASES) {
      const source = readFileSync(join(vaultDir, path), "utf8");
      const lines = source.split("\n");
      const startAt = lines.findIndex((l) => classifyLine(l).kind === "heading");
      flatness[view] = lines.slice(startAt + 1).every((l) => !/^\s+\S/.test(l));
    }
    assert.deepEqual(flatness, {
      "flowtrace-queue": true,
      "qntm-queue": false,
      "trace-orchestration-queue": true,
    });
  });

  test("orderingFor itself agrees, on the genuinely flat flow-trace queue: rank 4 to rank 1", { skip: skipVault }, () => {
    const source = readFileSync(join(vaultDir, "dev/flow-trace/queue.md"), "utf8");
    const lines = source.split("\n");
    const fourthIndex = lines.findIndex((l) => l.includes("🔢 4"));
    assert.ok(fourthIndex !== -1, "no '🔢 4' row found — fixture assumption broken");
    const after = lines[fourthIndex].replace("🔢 4", "🔢 1");
    const reading = orderingFor("flowtrace-queue", "queue", source, fourthIndex, after, ORDERING, ORDERING_FIELDS);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.moved, true);
    assert.equal(reading.answer.afterRank, 1);
  });

  test("orderingFor refuses on qntm-queue's real content — its own summary child trips nested-section", { skip: skipVault }, () => {
    const source = readFileSync(join(vaultDir, "dev/qntm/queue.md"), "utf8");
    const lines = source.split("\n");
    const firstIndex = lines.findIndex((l) => l.includes("🔢 1"));
    assert.ok(firstIndex !== -1, "no '🔢 1' row found — fixture assumption broken");
    const reading = orderingFor("qntm-queue", "queue", source, firstIndex, lines[firstIndex], ORDERING, ORDERING_FIELDS);
    assert.deepEqual(reading, { kind: "abstains", because: "nested-section" });
  });
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 1b. THE NESTED CASE — the literal falsifier does NOT hold, measured; orderingFor refuses instead
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("1b. THE ADAPTED FALSIFIER — this_week.md's own nesting breaks the flat assumption", () => {
  test("MEASURED: available-overdue's printed order does NOT match ascending available_date", { skip: skipVault }, (t) => {
    // THE FINDING THAT CHANGED THIS MODULE'S DESIGN. "Check personal outcomes" (available_date
    // 2026-07-27, the earliest in the section) prints LAST — after two #outcome ancestor roots
    // whose own subtrees carry the later 2026-07-28 — because section_builder.py's
    // `_order_children` sorts `ordering:` only within same-parent qualifying siblings and places
    // every context/ancestor row ahead of every qualifying row at each tree level, unconditionally.
    // If this assertion ever starts PASSING, the engine's own behaviour changed and `ordering.ts`'s
    // `nested-section` refusal may be safe to narrow — it should not be deleted on faith alone.
    const source = readFileSync(join(vaultDir, "this_week.md"), "utf8");
    const documentOrder = markerValuesInDocumentOrder(source, "Overdue to Start", "available_date");
    // ── THE PRECONDITION, STATED OUT LOUD (added 2026-08-03) ──────────────────────────────────
    // THIS TEST READS THE OPERATOR'S LIVE VAULT. `~/qntm/this_week.md` is regenerated by the
    // engine every cycle from whatever his week actually contains, so the SHAPE this measurement
    // needs — two or more dated rows, at least one of them nested — is not guaranteed to be there
    // on the day the suite runs. On 2026-08-03 '## Overdue to Start' was EMPTY, `documentOrder`
    // came back `[]`, and `notDeepEqual([], [])` failed VACUOUSLY: it reported an engine finding
    // when the only thing that had changed was that he had no overdue items. A suite that goes red
    // because the operator finished his work is a suite that cannot warn anybody about anything.
    //
    // So the dependency is now named rather than assumed. When the content cannot answer, the test
    // says so on stdout and measures nothing. It does NOT relax the assertion — the moment the
    // section carries the shape again, the original claim is asserted exactly as before.
    if (documentOrder.length < 2 || !hasNestedRow(source, "Overdue to Start")) {
      t.diagnostic(
        `PRECONDITION NOT MET, SO NOTHING WAS MEASURED — '## Overdue to Start' in ${join(vaultDir, "this_week.md")} ` +
          `currently prints ${documentOrder.length} dated row(s) and ` +
          `${hasNestedRow(source, "Overdue to Start") ? "does" : "does NOT"} nest. ` +
          `This claim needs 2+ dated rows AND nesting. It is his week's shape today, not an engine change.`,
      );
      return;
    }
    const sorted = sortedAscending(documentOrder, "date");
    assert.notDeepEqual(
      documentOrder,
      sorted,
      "this_week.md's nesting no longer breaks flat ordering — re-examine whether nested-section " +
        "can be narrowed, but do not remove it without re-measuring section_builder.py's own rule",
    );
  });

  for (const { section, heading } of [
    { section: "overdue", heading: "Overdue" },
    { section: "due-this-week", heading: "Due This Week" },
    { section: "available-overdue", heading: "Overdue to Start" },
    { section: "available-this-week", heading: "Scheduled This Week" },
  ]) {
    test(`orderingFor abstains 'nested-section' for this-week.${section}, against real content`, { skip: skipVault }, (t) => {
      const source = readFileSync(join(vaultDir, "this_week.md"), "utf8");
      const lines = source.split("\n");
      const headingAt = lines.findIndex((l) => classifyLine(l).kind === "heading" && classifyLine(l).text === heading);
      assert.ok(headingAt !== -1, `no '## ${heading}' heading found`);
      // The first content line under the heading — whatever it is, editing it must refuse, because
      // the refusal is a property of the SECTION'S shape, not of which line inside it is touched.
      const firstContentAt = headingAt + 1;
      const reading = orderingFor(
        "this-week",
        section,
        source,
        firstContentAt,
        lines[firstContentAt] ?? "",
        ORDERING,
        ORDERING_FIELDS,
      );
      // A section with genuinely nothing printed under it (measured earlier in this arc: "Overdue"
      // is currently empty) has no line to test — skip that one case rather than fail on an empty
      // fixture, while every section that DOES have content must show the refusal.
      if ((lines[firstContentAt] ?? "").trim() === "" || classifyLine(lines[firstContentAt]).kind === "heading") {
        t.diagnostic(`'## ${heading}' is empty today — no line to test, nothing measured.`);
        return;
      }
      // ── THE SECOND PRECONDITION, MADE EXPLICIT (added 2026-08-03) ────────────────────────────
      // The paragraph above already conceded that this claim depends on live vault content; it
      // only conceded the EMPTY case. The FLAT case is the same dependency and was not guarded.
      // On 2026-08-03 '## Due This Week' held two flat `#task` rows and pulled in no `#outcome`
      // ancestor, so `orderingFor` correctly ANSWERED (siblingCount 1) instead of abstaining, and
      // the suite reported an engine defect that did not exist. `nested-section` is a refusal
      // about a section that NESTS; a section with nothing nested in it has nothing to refuse.
      //
      // The claim is not weakened. `available-this-week` still nests today and still asserts, so
      // the refusal remains proven against real content on every run — just not claimed of a
      // section whose content cannot support it.
      if (!hasNestedRow(source, heading)) {
        t.diagnostic(
          `PRECONDITION NOT MET, SO NOTHING WAS MEASURED — '## ${heading}' prints only flat rows in ` +
            `${join(vaultDir, "this_week.md")} today, so there is no nesting for 'nested-section' to refuse. ` +
            `This is his week's shape, not an engine change.`,
        );
        return;
      }
      assert.deepEqual(reading, { kind: "abstains", because: "nested-section" });
    });
  }
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 2. A TEST AGAINST HIS REAL CONFIG — the 9 sections say something; the other 177 are silent
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("2. against the real published table", () => {
  test("flowtrace-queue.queue: moving queue_position from 4 to 1 says the rank changed", () => {
    const source = [
      "## Queue",
      "- [ ] a [[qntm:1]] #chore #dev 🔢 1",
      "- [ ] b [[qntm:2]] #chore #dev 🔢 2",
      "- [ ] c [[qntm:3]] #chore #dev 🔢 3",
      "- [ ] d [[qntm:4]] #chore #dev 🔢 4",
    ].join("\n");
    const reading = orderingFor(
      "flowtrace-queue",
      "queue",
      source,
      4,
      "- [ ] d [[qntm:4]] #chore #dev 🔢 1",
      ORDERING,
      ORDERING_FIELDS,
    );
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.moved, true);
    assert.equal(reading.answer.beforeRank, 4);
    assert.equal(reading.answer.afterRank, 1);
  });

  test("a FLAT this-week-shaped fixture: an edit that does not change the sort key says nothing", () => {
    // Deliberately flat (no #outcome ancestor) — this-week's real content is never flat (§1b), so
    // this proves orderingFor's OWN "unchanged answer is silence" logic independent of the nested
    // refusal that would otherwise mask it.
    const source = [
      "## Due This Week",
      "- [ ] a [[qntm:1]] #task #work 📅 2026-08-01",
      "- [ ] b [[qntm:2]] #task #work 📅 2026-08-05",
    ].join("\n");
    const reading = orderingFor(
      "this-week",
      "due-this-week",
      source,
      1,
      "- [ ] a renamed [[qntm:1]] #task #work 📅 2026-08-01",
      ORDERING,
      ORDERING_FIELDS,
    );
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.moved, false);
  });

  test("one of the OTHER 177 sections — inbox's domain-empty — is silent, always", () => {
    const reading = orderingFor(
      "inbox",
      "domain-empty",
      "## Domain Empty\n- [ ] Ring the dentist",
      1,
      "- [ ] Ring the dentist #work",
      ORDERING,
      ORDERING_FIELDS,
    );
    assert.equal(reading.kind, "abstains");
    assert.equal(reading.because, "no-section-declaration");
  });
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 3. EVERY REFUSAL PATH PRODUCES SILENCE — all five `OrderingAbstention` values
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("3. every abstention, named", () => {
  test('1/5 — "no-section-declaration": a section outside the published 9', () => {
    const reading = orderingFor("inbox", "not-a-section", "## H\n- [ ] x", 1, "- [ ] x", ORDERING, ORDERING_FIELDS);
    assert.deepEqual(reading, { kind: "abstains", because: "no-section-declaration" });
  });

  test('2/5 — "insertion-order": daily-work.capture has a mode, not a field', () => {
    const reading = orderingFor(
      "daily-work",
      "capture",
      "## Work Capture\n- [ ] x",
      1,
      "- [ ] x #work",
      ORDERING,
      ORDERING_FIELDS,
    );
    assert.deepEqual(reading, { kind: "abstains", because: "insertion-order" });
  });

  test('3/5 — "field-not-published": a hand-built section ordering by an unmapped field', () => {
    const fakeOrdering = { v: { s: { ordering: [{ field: "mystery", direction: "asc" }] } } };
    const reading = orderingFor("v", "s", "## H\n- [ ] x", 1, "- [ ] x", fakeOrdering, ORDERING_FIELDS);
    assert.deepEqual(reading, { kind: "abstains", because: "field-not-published" });
  });

  test('4/5 — "nested-section": an indented sibling anywhere in the section refuses the whole edit', () => {
    const fakeOrdering = { v: { s: { ordering: [{ field: "queue_position", direction: "asc" }] } } };
    const source = ["## H", "- [ ] a [[qntm:1]] 🔢 1", "    - [ ] child, indented, no marker"].join("\n");
    const reading = orderingFor("v", "s", source, 1, "- [ ] a [[qntm:1]] 🔢 2", fakeOrdering, ORDERING_FIELDS);
    assert.deepEqual(reading, { kind: "abstains", because: "nested-section" });
  });

  test('5/5 — "no-value": the AFTER text carries no marker at all', () => {
    const source = "## Queue\n- [ ] a [[qntm:1]] #dev 🔢 1";
    const reading = orderingFor("flowtrace-queue", "queue", source, 1, "- [ ] a [[qntm:1]] #dev", ORDERING, ORDERING_FIELDS);
    assert.deepEqual(reading, { kind: "abstains", because: "no-value" });
  });

  test('"no-value" the other way — the BEFORE text carried no marker (a fresh row acquiring one)', () => {
    const source = "## Queue\n- [ ] a [[qntm:1]] #dev";
    const reading = orderingFor("flowtrace-queue", "queue", source, 1, "- [ ] a [[qntm:1]] #dev 🔢 1", ORDERING, ORDERING_FIELDS);
    assert.deepEqual(reading, { kind: "abstains", because: "no-value" });
  });

  test("a FLAT section with a marker-less sibling excludes it from the ranking, not from the refusal", () => {
    // The flow-trace queue.md real trap: a DONE item with no 🔢 sits flat (no indent) beside active
    // items. Flat means no nested-section refusal; the marker-less sibling is simply excluded from
    // the ranked set (siblingCount reflects it), matching real content §1a already proves works.
    const source = [
      "## Queue",
      "- [ ] a [[qntm:1]] 🔢 1",
      "- [ ] b [[qntm:2]] 🔢 2",
      "- [x] done, no marker [[qntm:3]]",
    ].join("\n");
    const reading = orderingFor("flowtrace-queue", "queue", source, 1, "- [ ] a [[qntm:1]] 🔢 3", ORDERING, ORDERING_FIELDS);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.siblingCount, 1, "the marker-less done item should not count as a sibling");
  });
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 4. THE DIRECTION FOLLOWS THE DECLARATION — restated with orderingFor itself, not just the generator
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("4. orderingFor follows a flipped direction, not a hardcoded ascending assumption", () => {
  const ascOrdering = { v: { s: { ordering: [{ field: "due_date", direction: "asc" }] } } };
  const descOrdering = { v: { s: { ordering: [{ field: "due_date", direction: "desc" }] } } };
  const source = [
    "## H",
    "- [ ] a [[qntm:1]] 📅 2026-08-01",
    "- [ ] b [[qntm:2]] 📅 2026-08-10",
  ].join("\n");
  const moveEarlier = "- [ ] b [[qntm:2]] 📅 2026-07-01"; // now EARLIER than a's 2026-08-01

  test("ascending: making b earlier than a moves it from rank 2 to rank 1", () => {
    const reading = orderingFor("v", "s", source, 2, moveEarlier, ascOrdering, ORDERING_FIELDS);
    assert.equal(reading.answer.moved, true);
    assert.equal(reading.answer.beforeRank, 2);
    assert.equal(reading.answer.afterRank, 1);
  });

  test("descending: the SAME edit moves b the OTHER way, from rank 1 to rank 2", () => {
    const reading = orderingFor("v", "s", source, 2, moveEarlier, descOrdering, ORDERING_FIELDS);
    assert.equal(reading.answer.moved, true);
    assert.equal(reading.answer.beforeRank, 1);
    assert.equal(reading.answer.afterRank, 2);
  });
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 5. NO CLOCK — the whole "answer" path never calls Date.now
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("5. orderingFor reaches the clock zero times", () => {
  test("Date.now poisoned, every real section still answers or abstains cleanly", () => {
    const saved = Date.now;
    Date.now = () => {
      throw new Error("orderingFor reached the clock — the day-boundary dependency was NOT refuted");
    };
    try {
      for (const [view, sections] of Object.entries(ORDERING)) {
        for (const sectionId of Object.keys(sections)) {
          // A minimal one-line section is enough to drive every branch up to (and past) the
          // declaration lookup; the clock, if reached at all, would be reached here.
          orderingFor(view, sectionId, "## H\n- [ ] x", 1, "- [ ] x", ORDERING, ORDERING_FIELDS);
          orderingPlacementFor(view, sectionId, "## H\n- [ ] x", 1, "- [ ] x", ORDERING, ORDERING_FIELDS);
        }
      }
    } finally {
      Date.now = saved;
    }
  });
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 6. NOTHING LOCAL REACHES A WRITE — this module specifically
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("6. NOTHING LOCAL REACHES A WRITE — ordering.ts's own imports", () => {
  test("ordering.ts imports nothing from source.ts, context.ts or cascade.ts", () => {
    const src = readFileSync(resolve(HERE, "..", "app", "present", "ordering.ts"), "utf8");
    for (const line of src.split(/\r?\n/)) {
      if (!/^\s*import\b/.test(line)) continue;
      assert.doesNotMatch(
        line,
        /["']\.\/(source|context|cascade)\.js["']/,
        `ordering.ts imports the edit or cascade path: ${line.trim()}`,
      );
    }
  });
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 7. orderingPlacementFor — WHERE the row belongs, proven to agree, not merely to answer
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("7. orderingPlacementFor agrees with an independently-built expectation and with orderingFor", () => {
  test(
    "flowtrace-queue.queue, real content: beforeLineIndex matches an INDEPENDENTLY stable-sorted expectation",
    { skip: skipVault },
    () => {
      const source = readFileSync(join(vaultDir, "dev/flow-trace/queue.md"), "utf8");
      const lines = source.split("\n");
      const fourthIndex = lines.findIndex((l) => l.includes("🔢 4"));
      assert.ok(fourthIndex !== -1, "no '🔢 4' row found — fixture assumption broken");
      const after = lines[fourthIndex].replace("🔢 4", "🔢 1");

      const reading = orderingPlacementFor(
        "flowtrace-queue",
        "queue",
        source,
        fourthIndex,
        after,
        ORDERING,
        ORDERING_FIELDS,
      );
      assert.equal(reading.kind, "answer");
      assert.equal(reading.placement.moved, true);

      // THE INDEPENDENT EXPECTATION — built without calling `orderingPlacementFor` or anything it
      // calls, so this is not the module checking its own homework. Every 🔢-bearing line in the
      // section, in FILE ORDER, the edited line's own value substituted in at its own position,
      // then `Array.prototype.sort` — the same stability guarantee `orderingPlacementFor` itself
      // relies on (ECMA-262 2019), applied here by a completely separate call site.
      const marker = ORDERING_FIELDS.queue_position;
      const startAt = lines.findIndex((l) => classifyLine(l).kind === "heading");
      const entries = [];
      for (let at = startAt + 1; at < lines.length; at += 1) {
        if (classifyLine(lines[at]).kind === "heading") break;
        const text = at === fourthIndex ? after : lines[at];
        const value = markerValue(text, marker);
        if (value !== undefined) entries.push({ at, value: Number(value) });
      }
      const sorted = [...entries].sort((a, b) => a.value - b.value);
      const pos = sorted.findIndex((e) => e.at === fourthIndex);
      const expectedBefore = sorted[pos + 1]?.at ?? null;
      assert.equal(reading.placement.beforeLineIndex, expectedBefore);
    },
  );

  test("orderingFor.moved and orderingPlacementFor.moved never disagree, over every declared section", () => {
    // One minimal edit per declared section that HAS a field to move by (insertion-order sections
    // have none and are covered by §8's abstention-parity proof instead) — driven through BOTH
    // functions with IDENTICAL arguments, asserting the two either both abstain for the same
    // reason or both answer with the same `moved`.
    let exercised = 0;
    for (const [view, sections] of Object.entries(ORDERING)) {
      for (const [sectionId, declared] of Object.entries(sections)) {
        const keys = declared.ordering;
        if (keys === undefined || keys.length === 0) continue; // insertion-order — §8 covers it
        const key = keys[0];
        const marker = ORDERING_FIELDS[key.field];
        if (marker === undefined) continue; // field-not-published — §8 covers it
        const low = marker.kind === "date" ? "2026-01-01" : marker.kind === "int" ? "1" : "1.0";
        const high = marker.kind === "date" ? "2026-06-01" : marker.kind === "int" ? "9" : "9.0";
        const higher = marker.kind === "date" ? "2026-12-31" : marker.kind === "int" ? "99" : "99.0";
        const source = [
          "## H",
          `- [ ] a [[qntm:1]] ${marker.token} ${low}`,
          `- [ ] b [[qntm:2]] ${marker.token} ${high}`,
        ].join("\n");
        const after = `- [ ] a [[qntm:1]] ${marker.token} ${higher}`;
        const noteReading = orderingFor(view, sectionId, source, 1, after, ORDERING, ORDERING_FIELDS);
        const placeReading = orderingPlacementFor(view, sectionId, source, 1, after, ORDERING, ORDERING_FIELDS);
        exercised += 1;
        assert.equal(noteReading.kind, placeReading.kind, `${view}.${sectionId}: kind disagreement`);
        if (noteReading.kind === "answer") {
          assert.equal(
            noteReading.answer.moved,
            placeReading.placement.moved,
            `${view}.${sectionId}: moved disagreement`,
          );
        } else {
          assert.equal(noteReading.because, placeReading.because, `${view}.${sectionId}: abstention disagreement`);
        }
      }
    }
    // POSITIVE CONTROL: the sweep above must have actually exercised his real declared sections,
    // not silently iterated zero of them because the published table changed shape.
    assert.ok(exercised >= 9, `expected to exercise all 9 field-ordered sections, exercised ${exercised}`);
  });
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 8. orderingPlacementFor abstains for the IDENTICAL reason orderingFor does, every time
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("8. orderingPlacementFor's abstentions match orderingFor's, reason for reason", () => {
  const cases = [
    {
      label: "no-section-declaration",
      args: ["inbox", "not-a-section", "## H\n- [ ] x", 1, "- [ ] x", ORDERING, ORDERING_FIELDS],
    },
    {
      label: "insertion-order",
      args: ["daily-work", "capture", "## Work Capture\n- [ ] x", 1, "- [ ] x #work", ORDERING, ORDERING_FIELDS],
    },
    {
      label: "field-not-published",
      args: [
        "v",
        "s",
        "## H\n- [ ] x",
        1,
        "- [ ] x",
        { v: { s: { ordering: [{ field: "mystery", direction: "asc" }] } } },
        ORDERING_FIELDS,
      ],
    },
    {
      label: "nested-section",
      args: [
        "v",
        "s",
        ["## H", "- [ ] a [[qntm:1]] 🔢 1", "    - [ ] child, indented, no marker"].join("\n"),
        1,
        "- [ ] a [[qntm:1]] 🔢 2",
        { v: { s: { ordering: [{ field: "queue_position", direction: "asc" }] } } },
        ORDERING_FIELDS,
      ],
    },
    {
      label: "no-value",
      args: [
        "flowtrace-queue",
        "queue",
        "## Queue\n- [ ] a [[qntm:1]] #dev 🔢 1",
        1,
        "- [ ] a [[qntm:1]] #dev",
        ORDERING,
        ORDERING_FIELDS,
      ],
    },
  ];
  for (const { label, args } of cases) {
    test(`${label}: orderingFor and orderingPlacementFor abstain identically`, () => {
      const noteReading = orderingFor(...args);
      const placeReading = orderingPlacementFor(...args);
      assert.equal(noteReading.kind, "abstains", `orderingFor did not abstain for ${label}`);
      assert.equal(placeReading.kind, "abstains", `orderingPlacementFor did not abstain for ${label}`);
      assert.equal(noteReading.because, label);
      assert.equal(placeReading.because, label);
    });
  }
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 9. THE STABLE-SORT PROOF — the tie-break is a documented guarantee, proven over invented config
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("9. orderingPlacementFor's tie-break agrees with a stable sort, over config his real sections do not exercise", () => {
  const fakeOrdering = { v: { s: { ordering: [{ field: "due_date", direction: "asc" }] } } };
  const fakeMarker = { due_date: { token: "📅", kind: "date" } };

  test("a genuine tie: the edited line settles immediately AFTER the sibling it ties with, in file order", () => {
    // a (01), b (05), c (10) — c moves down to TIE with a's 01. A stable sort of the pre-sort list
    // [a, b, c-edited] by date keeps a ahead of the tied c (a came first in FILE order), so c
    // belongs immediately before b — never before a, which an unstable or naively-appended sort
    // could produce instead.
    const source = [
      "## H",
      "- [ ] a [[qntm:1]] 📅 2026-08-01",
      "- [ ] b [[qntm:2]] 📅 2026-08-05",
      "- [ ] c [[qntm:3]] 📅 2026-08-10",
    ].join("\n");
    const reading = orderingPlacementFor(
      "v",
      "s",
      source,
      3,
      "- [ ] c [[qntm:3]] 📅 2026-08-01",
      fakeOrdering,
      fakeMarker,
    );
    assert.equal(reading.kind, "answer");
    assert.equal(reading.placement.moved, true);
    assert.equal(reading.placement.beforeLineIndex, 2, "c should settle before b, sorting after the tied a");
  });

  test("a tie with a LATER sibling, crossed past an earlier one — the case a naive append gets wrong", () => {
    // z (01), x (EDITED, starts 15, moves down to 10 — TYING with y), w (05), y (10). Moving x
    // crosses w on the way down (a genuine rank change, `moved` must be true) and lands exactly on
    // y's value — and x's own file position (idx2) sits BEFORE y's (idx4), so a correct stable
    // sort must keep x ahead of the tied y.
    //
    // A NAIVE IMPLEMENTATION THAT APPENDS THE EDITED LINE AT THE END OF THE PRE-SORT LIST — rather
    // than reinserting it at its own file position — puts x AFTER y in that list, and a stable
    // sort then preserves THAT (wrong) relative order for the tied pair: y before x, so x would be
    // reported as sorting LAST (`beforeLineIndex: null`) instead of immediately before y. This is
    // the mutation this test is written to catch — the two earlier tie tests above were both
    // insensitive to it, because in both of them the edited line's tie partner already sat WHERE
    // an end-appended entry would also land relative to it; this shape does not have that
    // coincidence.
    const source = [
      "## H",
      "- [ ] z [[qntm:1]] 📅 2026-08-01",
      "- [ ] x [[qntm:2]] 📅 2026-08-15",
      "- [ ] w [[qntm:3]] 📅 2026-08-05",
      "- [ ] y [[qntm:4]] 📅 2026-08-10",
    ].join("\n");
    const reading = orderingPlacementFor(
      "v",
      "s",
      source,
      2,
      "- [ ] x [[qntm:2]] 📅 2026-08-10",
      fakeOrdering,
      fakeMarker,
    );
    assert.equal(reading.kind, "answer");
    assert.equal(reading.placement.moved, true, "x crossed w on the way down — this must register as a move");
    assert.equal(reading.placement.beforeLineIndex, 4, "x ties with y but sat EARLIER in the file, so settles before y");
  });

  test("the LAST position: moving a row past every sibling's value returns beforeLineIndex null", () => {
    const source = [
      "## H",
      "- [ ] a [[qntm:1]] 📅 2026-08-01",
      "- [ ] b [[qntm:2]] 📅 2026-08-05",
    ].join("\n");
    const reading = orderingPlacementFor(
      "v",
      "s",
      source,
      1,
      "- [ ] a [[qntm:1]] 📅 2026-12-31",
      fakeOrdering,
      fakeMarker,
    );
    assert.equal(reading.kind, "answer");
    assert.equal(reading.placement.moved, true);
    assert.equal(reading.placement.beforeLineIndex, null);
  });

  test("no motion: a row that already sits in the slot its (tied) value implies reports moved:false", () => {
    const source = [
      "## H",
      "- [ ] a [[qntm:1]] 📅 2026-08-01",
      "- [ ] b [[qntm:2]] 📅 2026-08-05",
    ].join("\n");
    const reading = orderingPlacementFor(
      "v",
      "s",
      source,
      1,
      "- [ ] a renamed [[qntm:1]] 📅 2026-08-01",
      fakeOrdering,
      fakeMarker,
    );
    assert.equal(reading.kind, "answer");
    assert.equal(reading.placement.moved, false);
  });

  test("a lone row with no siblings never moves — nothing to rank it against", () => {
    const source = ["## H", "- [ ] a [[qntm:1]] 📅 2026-08-01"].join("\n");
    const reading = orderingPlacementFor(
      "v",
      "s",
      source,
      1,
      "- [ ] a [[qntm:1]] 📅 2020-01-01",
      fakeOrdering,
      fakeMarker,
    );
    assert.equal(reading.kind, "answer");
    assert.equal(reading.placement.moved, false);
  });
});

// ══════════════════════════════════════════════════════════════════════════════════════════════
// 10. THE DEFAULT ORDERING — `defaultOrderingFor`/`defaultOrderingPlacementFor`/
//     `resolveOrderingFor`/`resolveOrderingPlacementFor`, 2026-08-04's own step: the engine's own
//     fallback for the 171 (of 186) sections `orderingFor` itself always abstains
//     `no-section-declaration` for, made explicit. `DEFAULT_ORDERING`/`PRIORITY_RANK` above are
//     read from the SERVED declaration, never invented by this file — the same posture §2 already
//     takes for `ORDERING`/`ORDERING_FIELDS`. `tests/resolution-default-ordering-agreement.test.mjs`
//     is the proof that `DEFAULT_ORDERING`/`PRIORITY_RANK` themselves agree with the ENGINE; this
//     file proves the COMPARATOR built on top of them agrees with what those two facts imply.
// ══════════════════════════════════════════════════════════════════════════════════════════════

describe("10a. THE TIERED RULE — a missing due_date/priority sorts LAST, regardless of direction", () => {
  test("due_date present beats due_date absent, even though the absent row's TITLE would sort first", () => {
    // "AAA" would win on title alone (the final tiebreak) — but "AAA" has no due_date, and "ZZZ"
    // does, so "ZZZ" (present, tier 0) outranks "AAA" (absent, tier 1) on the FIRST key.
    const source = ["## H", "- [ ] AAA", "- [ ] ZZZ 📅 2026-08-10"].join("\n");
    const reading = defaultOrderingFor("v", "s", source, 1, "- [ ] AAA edited", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.beforeRank, 2, "AAA (no due_date) should rank BEHIND ZZZ (has one)");
  });

  test("HIS OWN DEGENERATE CASE, REPRODUCED: neither due_date nor priority set anywhere — pure title, ascending, case-sensitive", () => {
    // The operator's own measured inbox order, verbatim (report's own six lines), rebuilt as a
    // fixture: "Family domain" / "Micu lunch" / "Open day close day" / "account opening form per
    // ca" / "zzTEST fast one" / "zzTEST inbox ordering test one". Uppercase sorts before lowercase
    // in codepoint order ('F'=70 < 'a'=97), which is why 'account' sorts after 'Open' and the two
    // 'zzTEST' rows sort last, tied on their shared prefix until 'fast' vs 'inbox'.
    const rows = [
      "Family domain",
      "Micu lunch",
      "Open day close day",
      "account opening form per ca",
      "zzTEST fast one",
      "zzTEST inbox ordering test one",
    ];
    const source = ["## Inbox", ...rows.map((r) => `- [ ] ${r}`)].join("\n");
    // Rank EVERY row by editing it to itself (a no-op edit) and reading its OWN afterRank — proves
    // the comparator's ranking of the whole set, not just one pairwise comparison.
    const ranks = rows.map((row, i) => {
      const reading = defaultOrderingFor("v", "s", source, i + 1, `- [ ] ${row}`, {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
      assert.equal(reading.kind, "answer", `row '${row}' should answer, not abstain`);
      return { row, rank: reading.answer.beforeRank };
    });
    const sorted = [...ranks].sort((a, b) => a.rank - b.rank).map((r) => r.row);
    assert.deepEqual(sorted, rows, "the fixture is already in the operator's own measured order — ranks should reproduce it exactly");
  });
});

describe("10b. PRIORITY — the enum marker, and the engine's own rank table, DESCENDING", () => {
  const source = ["## H", "- [ ] low 🔽", "- [ ] high ⏫", "- [ ] none"].join("\n");

  test("high (rank 3) outranks low (rank 1) outranks none (tier 1, absent)", () => {
    const rankOf = (lineIndex, text) => {
      const reading = defaultOrderingFor("v", "s", source, lineIndex, text, {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
      assert.equal(reading.kind, "answer");
      return reading.answer.beforeRank;
    };
    assert.equal(rankOf(2, "- [ ] high ⏫"), 1, "high should rank first");
    assert.equal(rankOf(1, "- [ ] low 🔽"), 2, "low should rank second");
    assert.equal(rankOf(3, "- [ ] none"), 3, "no priority marker at all should rank last");
  });

  test("moving a row from low to high crosses the middle rank — a real, provable move", () => {
    // Distinct titles on purpose: "low"/"high"/"none" above only needed to prove the RANK table;
    // this needs a case where priority TIES after the edit, so title (the third key) is what
    // decides the tie — "alpha" [[qntm's]] own title sorts before "beta"'s alphabetically, so once
    // alpha's priority rises to tie beta's, alpha settles AHEAD of beta, not merely "after the
    // sibling it used to trail" the way an unrelated-title fixture would obscure.
    const titled = ["## H", "- [ ] alpha 🔽", "- [ ] beta ⏫", "- [ ] gamma"].join("\n");
    const before = defaultOrderingFor("v", "s", titled, 1, "- [ ] alpha 🔽", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    assert.equal(before.kind, "answer");
    assert.equal(before.answer.beforeRank, 2, "alpha (low) starts behind beta (high), ahead of gamma (no priority)");

    const reading = defaultOrderingPlacementFor("v", "s", titled, 1, "- [ ] alpha ⏫", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.placement.moved, true, "alpha crosses beta on the way from low to high — a real rank change");
    assert.equal(reading.placement.beforeLineIndex, 2, "alpha now TIES beta's rank, and 'alpha' < 'beta' alphabetically, so it settles immediately before beta");
  });
});

describe("10c. TITLE — codepoint comparison, NOT JavaScript's native `<`, over an ASTRAL character", () => {
  // U+FFFF (a lone BMP code point, one UTF-16 code unit: 0xFFFF) vs U+10000 (the first astral code
  // point, a SURROGATE PAIR: high surrogate 0xD800, low surrogate 0xDC00). TRUE code-point order:
  // 0xFFFF < 0x10000, so the BMP title sorts FIRST. JavaScript's native `a < b` compares UTF-16
  // CODE UNITS instead: the astral title's FIRST code unit is 0xD800, which is LESS than 0xFFFF,
  // so naive `<` would rank the astral title first — the exact wrong answer this module's own
  // header names as a real risk ("locale collation" / codepoint-vs-code-unit) and `compareCodepoints`
  // (ordering.ts) exists to avoid. Neither of these titles carries a marker glyph — a genuinely
  // exotic character an operator could still type into a title.
  const bmp = "￿-title";
  const astral = "\u{10000}-title";

  test("the BMP title (U+FFFF) ranks BEFORE the astral title (U+10000) — true code-point order", () => {
    const source = ["## H", `- [ ] ${astral}`, `- [ ] ${bmp}`].join("\n");
    const reading = defaultOrderingFor("v", "s", source, 2, `- [ ] ${bmp}`, {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    assert.equal(reading.kind, "answer");
    assert.equal(reading.answer.beforeRank, 1, "U+FFFF should sort before U+10000 in TRUE code-point order");
  });

  test("POSITIVE CONTROL: native `<` really would get this backwards, so the test above is not vacuous", () => {
    assert.ok(bmp < astral === false, "if native `<` ever agrees with code-point order here, this fixture stopped proving anything — pick a new pair");
    assert.ok(astral < bmp, "native code-UNIT comparison ranks the astral title first — the wrong answer this module avoids");
  });
});

describe("10d. ABSTENTIONS — the three NEW reasons, plus the reused ones, all reachable through the default path", () => {
  test("field-not-published: neither due_date nor priority has a marker in this (invented) config", () => {
    const reading = defaultOrderingFor("v", "s", "## H\n- [ ] x", 1, "- [ ] x edited", {}, DEFAULT_ORDERING, {}, PRIORITY_RANK);
    assert.equal(reading.kind, "abstains");
    assert.equal(reading.because, "field-not-published");
  });

  test("nested-section: the SAME refusal orderingFor already has, reachable for an undeclared section too", () => {
    const source = ["## H", "- [ ] a", "    - [ ] indented child"].join("\n");
    const reading = defaultOrderingFor("v", "s", source, 1, "- [ ] a edited", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    assert.equal(reading.kind, "abstains");
    assert.equal(reading.because, "nested-section");
  });

  test("container-ordering-directive: the section's OWN heading carries a live #order: directive", () => {
    const source = ["## H #order:queue_position:asc", "- [ ] a", "- [ ] b"].join("\n");
    const reading = defaultOrderingFor("v", "s", source, 1, "- [ ] a edited", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    assert.equal(reading.kind, "abstains");
    assert.equal(reading.because, "container-ordering-directive");
  });

  test("style-ambiguous-title: a title wrapped in ** could disagree with the engine's own stripped title", () => {
    const source = ["## H", "- [ ] **Ship it**", "- [ ] plain"].join("\n");
    const reading = defaultOrderingFor("v", "s", source, 1, "- [ ] **Ship it now**", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    assert.equal(reading.kind, "abstains");
    assert.equal(reading.because, "style-ambiguous-title");
  });

  test("has-declared-ordering: calling the default path directly on a section that DID declare ordering refuses, defensively", () => {
    const declared = { v: { s: { ordering: [{ field: "due_date", direction: "asc" }] } } };
    const reading = defaultOrderingFor("v", "s", "## H\n- [ ] x", 1, "- [ ] x edited", declared, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    assert.equal(reading.kind, "abstains");
    assert.equal(reading.because, "has-declared-ordering");
  });

  test("defaultOrderingFor and defaultOrderingPlacementFor abstain identically, reason for reason (mirrors §8 for the declared path)", () => {
    const cases = [
      ["field-not-published", "## H\n- [ ] x", {}],
      ["nested-section", ["## H", "- [ ] a", "    - [ ] b"].join("\n"), ORDERING_FIELDS],
      ["container-ordering-directive", "## H #order:x:asc\n- [ ] a", ORDERING_FIELDS],
    ];
    for (const [label, source, fields] of cases) {
      const noteReading = defaultOrderingFor("v", "s", source, 1, "- [ ] a edited", {}, DEFAULT_ORDERING, fields, PRIORITY_RANK);
      const placeReading = defaultOrderingPlacementFor("v", "s", source, 1, "- [ ] a edited", {}, DEFAULT_ORDERING, fields, PRIORITY_RANK);
      assert.equal(noteReading.kind, "abstains", `defaultOrderingFor did not abstain for ${label}`);
      assert.equal(placeReading.kind, "abstains", `defaultOrderingPlacementFor did not abstain for ${label}`);
      assert.equal(noteReading.because, label);
      assert.equal(placeReading.because, label);
    }
  });
});

describe("10e. THE DISPATCHER — resolveOrderingFor/resolveOrderingPlacementFor route by declaration, not guess", () => {
  test("a DECLARED section routes to orderingFor unchanged — identical answer, over his real config", () => {
    const source = ["## Queue", "- [ ] a [[qntm:1]] 🔢 1", "- [ ] b [[qntm:2]] 🔢 2"].join("\n");
    const direct = orderingFor("flowtrace-queue", "queue", source, 1, "- [ ] a [[qntm:1]] 🔢 5", ORDERING, ORDERING_FIELDS);
    const dispatched = resolveOrderingFor(
      "flowtrace-queue", "queue", source, 1, "- [ ] a [[qntm:1]] 🔢 5", ORDERING, ORDERING_FIELDS, DEFAULT_ORDERING, PRIORITY_RANK,
    );
    assert.deepEqual(dispatched, direct);
    assert.equal(direct.kind, "answer", "positive control — this pair must actually answer, not merely agree while abstaining");
  });

  test("an UNDECLARED section routes to defaultOrderingFor — identical answer", () => {
    const source = ["## H", "- [ ] AAA", "- [ ] ZZZ 📅 2026-08-10"].join("\n");
    const direct = defaultOrderingFor("v", "s", source, 1, "- [ ] AAA edited", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    const dispatched = resolveOrderingFor("v", "s", source, 1, "- [ ] AAA edited", {}, ORDERING_FIELDS, DEFAULT_ORDERING, PRIORITY_RANK);
    assert.deepEqual(dispatched, direct);
    assert.equal(direct.kind, "answer");
  });

  test("the placement twin dispatches the same way, for both declared and undeclared sections", () => {
    const declaredSource = ["## Queue", "- [ ] a [[qntm:1]] 🔢 1", "- [ ] b [[qntm:2]] 🔢 2"].join("\n");
    const declaredDirect = orderingPlacementFor("flowtrace-queue", "queue", declaredSource, 1, "- [ ] a [[qntm:1]] 🔢 5", ORDERING, ORDERING_FIELDS);
    const declaredDispatched = resolveOrderingPlacementFor(
      "flowtrace-queue", "queue", declaredSource, 1, "- [ ] a [[qntm:1]] 🔢 5", ORDERING, ORDERING_FIELDS, DEFAULT_ORDERING, PRIORITY_RANK,
    );
    assert.deepEqual(declaredDispatched, declaredDirect);

    const undeclaredSource = ["## H", "- [ ] AAA", "- [ ] ZZZ 📅 2026-08-10"].join("\n");
    const undeclaredDirect = defaultOrderingPlacementFor("v", "s", undeclaredSource, 1, "- [ ] AAA edited", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
    const undeclaredDispatched = resolveOrderingPlacementFor("v", "s", undeclaredSource, 1, "- [ ] AAA edited", {}, ORDERING_FIELDS, DEFAULT_ORDERING, PRIORITY_RANK);
    assert.deepEqual(undeclaredDispatched, undeclaredDirect);
  });
});

describe("10f. NOTHING LOCAL REACHES A WRITE — the default-ordering path's own imports, mirroring §6", () => {
  test("ordering.ts still imports nothing from source.ts", () => {
    const ORDERING_SOURCE = readFileSync(resolve(HERE, "..", "app", "present", "ordering.ts"), "utf8");
    for (const line of ORDERING_SOURCE.split(/\r?\n/)) {
      if (!/^\s*import\b/.test(line)) continue;
      assert.doesNotMatch(line, /["']\.\/source\.js["']/, `ordering.ts imports the edit path: ${line.trim()}`);
    }
  });

  test("defaultOrderingFor reaches the clock zero times — the same claim §5 makes for orderingFor", () => {
    const realNow = Date.now;
    Date.now = () => {
      throw new Error("defaultOrderingFor read the clock");
    };
    try {
      const source = ["## H", "- [ ] AAA", "- [ ] ZZZ 📅 2026-08-10"].join("\n");
      const reading = defaultOrderingFor("v", "s", source, 1, "- [ ] AAA edited", {}, DEFAULT_ORDERING, ORDERING_FIELDS, PRIORITY_RANK);
      assert.equal(reading.kind, "answer");
    } finally {
      Date.now = realNow;
    }
  });
});
