/**
 * L3 ADDRESSING — `sectionAt` NAMES THE `(view, section)` A PRINTED ROW SITS IN, BY CONFIG ID.
 *
 *   node --test tests/present-address.test.mjs
 *
 * `docs/implementation-artifacts/design-the-resolution-architecture.md` step 2: the app already
 * knows a section by its POSITIONAL ORDINAL; the declaration is keyed on the config's `id:` string.
 * Nothing joined them, so `membership.ts` — proven correct, `tests/present-membership.test.mjs` and
 * `tests/qualification-agreement.test.mjs`, 2,184 reachable triples — could not be called. This file
 * proves the join, and proves it closes THE TRAP rather than merely avoiding it: the naive
 * `Object.keys(sections[view])[ordinal]` works on 25 of 27 published views and is silently wrong on
 * the operator's two daily surfaces, because the published predicate table is a proper SUBSET of
 * the declared sections there (`daily-work` 1 of 5, `daily-personal` 3 of 8).
 *
 * Four sections:
 *
 *   1. THE ORDINAL, against small hand-built fixtures — the counting rule alone.
 *   2. THE JOIN, against the operator's REAL `presentation.json` (already regenerated by this
 *      change) and REAL markdown transcribed from his vault — `inbox`, and THE TRAP CASES,
 *      `daily-work` and `daily-personal`, addressed correctly on every one of their un-published
 *      ordinals, not only the published one.
 *   3. THE FALSIFIER: a config change (rename, reorder) moves the answer, proven against a scratch
 *      copy of the real config — skipped, loudly, when the monorepo is not checked out.
 *   4. THE SWEEP, against every one of the 72 real views this instance declares — skipped, loudly,
 *      when either the monorepo or the vault (`~/qntm`) is not present, since it needs both.
 *
 * WHAT THIS DOES NOT PROVE: agreement with the engine's own `RenderedLineRecord.section_id`, which
 * needs a running cycle and none is run here (see this repo's report on why). What section 4 proves
 * instead is the fact `design-presentation-instance-identity.md` §2.3(c) already measured and
 * `instance.ts`'s own shipped ordinal already trusts: the Nth heading in the rendered file IS the
 * Nth entry in the config's declared `sections:` list, positionally, for all 72 views.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { cpSync, existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { sectionAt, sectionOrderFor, sectionOrdinalAt } from "../dist/present.js";
import {
  generateQualification,
  DEFAULT_CONFIG_DIR,
} from "../scripts/generate-qualification-declaration.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVED = JSON.parse(readFileSync(resolve(HERE, "..", "presentation.json"), "utf8"));
const SECTION_ORDER = SERVED.qualification.sectionOrder;

describe("1. sectionOrdinalAt — counting rule alone, small fixtures", () => {
  const SOURCE = [
    "- [ ] above any heading",
    "## First",
    "- [ ] a line in First",
    "",
    "## Second",
    "- [ ] a line in Second",
    "  - [ ] an indented line, still Second",
    "## Third",
  ].join("\n");

  test("above the first heading is null", () => {
    assert.equal(sectionOrdinalAt(SOURCE, 0), null);
  });

  test("a heading line belongs to the section it OPENS, not the one before", () => {
    assert.equal(sectionOrdinalAt(SOURCE, 1), 0, "## First");
    assert.equal(sectionOrdinalAt(SOURCE, 4), 1, "## Second");
    assert.equal(sectionOrdinalAt(SOURCE, 7), 2, "## Third");
  });

  test("every line under a heading, including a blank one, carries that heading's ordinal", () => {
    assert.equal(sectionOrdinalAt(SOURCE, 2), 0);
    assert.equal(sectionOrdinalAt(SOURCE, 3), 0, "a blank line still sits inside its section");
    assert.equal(sectionOrdinalAt(SOURCE, 5), 1);
    assert.equal(sectionOrdinalAt(SOURCE, 6), 1, "indentation does not open a new section");
  });

  test("out of range or a non-integer index is null, not a crash", () => {
    assert.equal(sectionOrdinalAt(SOURCE, -1), null);
    assert.equal(sectionOrdinalAt(SOURCE, 999), null);
    assert.equal(sectionOrdinalAt(SOURCE, 1.5), null);
  });

  test("a file with no heading at all is null everywhere", () => {
    assert.equal(sectionOrdinalAt("- [ ] just one line", 0), null);
  });
});

describe("2. sectionAt — the join, against the REAL declaration and REAL vault content", () => {
  test("inbox: two headings, two real section ids, in the declared order", () => {
    // `~/qntm/inbox.md`, verbatim (read-only, 2026-08-01) — the same fixture
    // tests/present-instance.test.mjs uses for the same reason: a live vault must not be read at
    // test time, so it is transcribed once, with a citation.
    const INBOX = [
      "## Inbox",
      "## Domain Empty",
      "- [ ] Ring the dentist",
    ].join("\n");
    assert.equal(sectionAt(INBOX, 0, "inbox", SECTION_ORDER), "inbox-tagged");
    assert.equal(sectionAt(INBOX, 1, "inbox", SECTION_ORDER), "domain-empty");
    assert.equal(sectionAt(INBOX, 2, "inbox", SECTION_ORDER), "domain-empty");
  });

  test("an unknown view addresses nothing — refused, not guessed", () => {
    assert.equal(sectionAt("## Only Heading", 0, "not-a-real-view", SECTION_ORDER), null);
  });

  describe("THE TRAP CASES — every declared ordinal addresses, not only the published one", () => {
    // `~/qntm/work/daily.md`, headings verbatim (read-only, 2026-08-01). Only "In Progress" (ordinal
    // 0) is in `SERVED.qualification.sections['daily-work']` — 4 of these 5 headings sit under a
    // section this instance publishes NO predicate for. `sectionAt` must still name all five,
    // because it indexes `sectionOrder`, never `sections`.
    const DAILY_WORK = [
      "## In Progress",
      "## Urgent",
      "## Due Today",
      "## Work Waiting",
      "- [~] Andrew to come back having spoken to them",
      "## Work Capture",
    ].join("\n");

    test("daily-work: published subset is 3 of 5 — asserted as the precondition for this test", () => {
      // RESTATED 2026-08-04: `waiting` (ordinal 3) joined `in-progress` (ordinal 0) —
      // `compile-qualification.mjs`'s one-hop `children:`/`parents:` widening resolved its
      // qualification, which used to be refused for "traverses an edge".
      //
      // RESTATED AGAIN 2026-08-06: `urgent` (ordinal 1) joined too — `deriveResolvableFields`
      // (`compile-qualification.mjs`'s header) admits `priority`, which `urgent`'s own
      // qualification predicate ranges over.
      const published = Object.keys(SERVED.qualification.sections["daily-work"] ?? {});
      assert.deepEqual(
        published,
        ["in-progress", "urgent", "waiting"],
        "the trap's own precondition changed underfoot",
      );
      assert.equal(SECTION_ORDER["daily-work"].length, 5);
    });

    test("all five ordinals address correctly, including the four unpublished ones", () => {
      assert.equal(sectionAt(DAILY_WORK, 0, "daily-work", SECTION_ORDER), "in-progress");
      assert.equal(sectionAt(DAILY_WORK, 1, "daily-work", SECTION_ORDER), "urgent");
      assert.equal(sectionAt(DAILY_WORK, 2, "daily-work", SECTION_ORDER), "due-today");
      assert.equal(sectionAt(DAILY_WORK, 3, "daily-work", SECTION_ORDER), "waiting");
      assert.equal(
        sectionAt(DAILY_WORK, 4, "daily-work", SECTION_ORDER),
        "waiting",
        "a body line under an unpublished section still addresses",
      );
      assert.equal(sectionAt(DAILY_WORK, 5, "daily-work", SECTION_ORDER), "capture");
    });

    test("THE FAILING VERSION OF THIS TEST — indexing the published subset gets it wrong from ordinal 2", () => {
      // Not what this module does; written out so the trap is legible as a concrete, checkable
      // claim rather than only prose. `Object.keys(sections[view])[ordinal]` on daily-work:
      //
      // RESTATED 2026-08-04: with a SECOND published section (`waiting`, real ordinal 3), the naive
      // version does not merely go blank at ordinal 1 — it returns a WRONG, non-empty answer.
      //
      // RESTATED AGAIN 2026-08-06: with a THIRD published section (`urgent`, real ordinal 1 — see
      // the precondition test above), the naive version now agrees with the real answer at ordinal
      // 1 TOO, by coincidence (`urgent` sits at both index 1 of the published subset AND real
      // ordinal 1 — the unpublished `due-today` between `urgent` and `waiting` is what the naive
      // version cannot see). The first ordinal it gets WRONG moves to 2: `Object.keys` preserves
      // the view's own declared order among the PUBLISHED subset, so index 2 of that subset is
      // `waiting` — a confidently wrong answer for "what heading is ordinal 2", which is really
      // `due-today`, an unpublished section. Sharper proof of the same trap: the naive version does
      // not fail loud, it fails quiet and wrong, and WHERE it first fails depends on which sections
      // happen to be published — the exact reason `sectionAt` must never be built this way.
      const naive = Object.keys(SERVED.qualification.sections["daily-work"]);
      assert.equal(naive[0], "in-progress", "ordinal 0 happens to agree");
      assert.equal(naive[1], "urgent", "ordinal 1 also happens to agree, by coincidence");
      assert.equal(naive[2], "waiting", "ordinal 2 ('due-today') is where the naive version silently returns the WRONG section");
      assert.notEqual(
        naive[2],
        sectionAt(DAILY_WORK, 2, "daily-work", SECTION_ORDER),
        "the naive index and the real answer for ordinal 2 must disagree — that IS the trap",
      );
    });

    // `~/qntm/personal/daily.md`, headings verbatim (read-only, 2026-08-01). 3 of 8 published.
    const DAILY_PERSONAL = [
      "## High Priority",
      "## Due Soon",
      "## Personal Waiting",
      "- [~] Kev to let me know",
      "## Routine Drift",
      "## Personal Capture",
      "## Orphans",
      "## Backlog",
      "## Done",
    ].join("\n");

    test("daily-personal: published subset is 6 of 8 — asserted as the precondition for this test", () => {
      // RESTATED 2026-08-04: `waiting` and `orphans` joined the previously-published three — the
      // same one-hop widening noted on `daily-work` above.
      //
      // RESTATED AGAIN 2026-08-06: `high-priority` joined too — the same `priority` widening
      // `daily-work`'s own restated comment names.
      const published = Object.keys(SERVED.qualification.sections["daily-personal"] ?? {}).sort();
      assert.deepEqual(published, ["backlog", "done", "high-priority", "orphans", "routine-drift", "waiting"]);
      assert.equal(SECTION_ORDER["daily-personal"].length, 8);
    });

    test("all eight ordinals address correctly, including the five unpublished ones", () => {
      assert.equal(sectionAt(DAILY_PERSONAL, 0, "daily-personal", SECTION_ORDER), "high-priority");
      assert.equal(sectionAt(DAILY_PERSONAL, 1, "daily-personal", SECTION_ORDER), "due-soon");
      assert.equal(sectionAt(DAILY_PERSONAL, 2, "daily-personal", SECTION_ORDER), "waiting");
      assert.equal(
        sectionAt(DAILY_PERSONAL, 3, "daily-personal", SECTION_ORDER),
        "waiting",
        "a body line under an unpublished section still addresses",
      );
      assert.equal(sectionAt(DAILY_PERSONAL, 4, "daily-personal", SECTION_ORDER), "routine-drift");
      assert.equal(sectionAt(DAILY_PERSONAL, 5, "daily-personal", SECTION_ORDER), "capture");
      assert.equal(sectionAt(DAILY_PERSONAL, 6, "daily-personal", SECTION_ORDER), "orphans");
      assert.equal(sectionAt(DAILY_PERSONAL, 7, "daily-personal", SECTION_ORDER), "backlog");
      assert.equal(sectionAt(DAILY_PERSONAL, 8, "daily-personal", SECTION_ORDER), "done");
    });
  });
});

const monorepoAvailable = existsSync(DEFAULT_CONFIG_DIR);
const vaultDir = join(homedir(), "qntm");
const vaultAvailable = existsSync(vaultDir);

describe("3. THE FALSIFIER — a config change (rename, reorder) moves the answer", () => {
  const skip = monorepoAvailable
    ? false
    : `monorepo not checked out at ${DEFAULT_CONFIG_DIR} — this section runs locally and is ` +
      "skipped in CI, which does not clone it (same posture as tests/present-qualification.test.mjs)";

  const withMutatedConfig = (mutate) => {
    const scratch = mkdtempSync(join(tmpdir(), "address-falsifier-"));
    try {
      const configDir = join(scratch, "config");
      cpSync(DEFAULT_CONFIG_DIR, configDir, { recursive: true });
      mutate(configDir);
      return generateQualification(configDir).sectionOrder;
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  };

  test("BASELINE: the real config's inbox order is what section 2 assumed", { skip }, () => {
    const order = generateQualification(DEFAULT_CONFIG_DIR).sectionOrder;
    assert.deepEqual(order["inbox"], ["inbox-tagged", "domain-empty"]);
  });

  test("RENAME: renaming a section id in the config changes what sectionAt returns for its ordinal", { skip }, () => {
    const order = withMutatedConfig((configDir) => {
      const path = join(configDir, "views", "inbox.yaml");
      const mutated = readFileSync(path, "utf8").replace("id: domain-empty", "id: untriaged");
      assert.ok(mutated.includes("id: untriaged"), "the falsifier's own edit did not apply");
      writeFileSync(path, mutated);
    });
    const source = ["## Inbox", "## Domain Empty"].join("\n");
    assert.equal(sectionAt(source, 1, "inbox", order), "untriaged");
    assert.notEqual(sectionAt(source, 1, "inbox", order), "domain-empty");
  });

  test("REORDER: swapping two sections' declared order swaps sectionAt's answer at their ordinals", { skip }, () => {
    const order = withMutatedConfig((configDir) => {
      const path = join(configDir, "views", "inbox.yaml");
      const lines = readFileSync(path, "utf8").split("\n");
      // Swap the two `- id:` BLOCKS whole, by line range, rather than reconstructing their text —
      // preserves indentation and any trailing comment exactly, so the only thing that changes is
      // which block comes first.
      const startOf = (id) => lines.findIndex((l) => l.trim() === `- id: ${id}`);
      const first = startOf("inbox-tagged");
      const second = startOf("domain-empty");
      assert.ok(first !== -1 && second !== -1 && first < second, "unexpected inbox.yaml shape");
      const blockA = lines.slice(first, second); // inbox-tagged's 3 lines
      const blockB = lines.slice(second, second + (second - first)); // domain-empty's 3 lines
      const reordered = [...lines.slice(0, first), ...blockB, ...blockA, ...lines.slice(second + blockA.length)];
      writeFileSync(path, reordered.join("\n"));
    });
    assert.deepEqual(order["inbox"], ["domain-empty", "inbox-tagged"], "the declared order followed the edit");
    const source = ["## Domain Empty", "## Inbox"].join("\n");
    assert.equal(sectionAt(source, 0, "inbox", order), "domain-empty");
    assert.equal(sectionAt(source, 1, "inbox", order), "inbox-tagged");
  });
});

describe("4. THE SWEEP — every one of the 72 real views this instance declares", () => {
  const skip =
    monorepoAvailable && vaultAvailable
      ? false
      : `needs both the monorepo (${DEFAULT_CONFIG_DIR}) and the vault (${vaultDir}) — this ` +
        "section runs locally and is skipped in CI, which has neither";

  test(
    "for every view, sectionOrder's length equals the real markdown's heading count, and every " +
      "heading addresses to the declared id at its own ordinal — step 1's falsifier and step 2's, together",
    { skip },
    () => {
      const generated = generateQualification(DEFAULT_CONFIG_DIR);
      const viewsDir = join(DEFAULT_CONFIG_DIR, "views");
      const files = readdirSync(viewsDir).filter(
        (f) => f.endsWith(".yaml") && f !== "default_registration.yaml",
      );

      // Minimal, test-local extraction of each view's `path:` — mirrors the generator's own
      // "targeted line scan, not a general YAML parser" posture (see that script's header), used
      // here only to locate the rendered markdown file, never to decide anything the app ships.
      const pathOf = (file) => {
        const text = readFileSync(join(viewsDir, file), "utf8");
        const match = text.match(/^\s*path:\s*(\S+)\s*$/m);
        return match ? match[1].replace(/^["']|["']$/g, "") : null;
      };

      let viewsChecked = 0;
      let headingsChecked = 0;
      for (const file of files) {
        const path = pathOf(file);
        if (path === null) continue;
        const mdPath = join(vaultDir, path);
        if (!existsSync(mdPath)) continue;
        const markdown = readFileSync(mdPath, "utf8");
        const lines = markdown.split(/\r?\n/);

        const headingIndexes = [];
        lines.forEach((line, i) => {
          if (/^#{1,6} /.test(line)) headingIndexes.push(i);
        });

        // The view id is the file's own top-level key, which is not always the filename — checked
        // directly rather than assumed, the same guard the generator itself applies.
        const text = readFileSync(join(viewsDir, file), "utf8");
        const idMatch = text.match(/^([A-Za-z0-9_-]+):\s*$/m);
        const declaredViewId = idMatch ? idMatch[1] : null;
        const order = declaredViewId ? generated.sectionOrder[declaredViewId] : undefined;
        if (order === undefined) continue; // a view with no sections: nothing to address

        assert.equal(
          order.length,
          headingIndexes.length,
          `${file}: sectionOrder has ${order.length} entries but ${path} has ` +
            `${headingIndexes.length} headings`,
        );

        headingIndexes.forEach((lineIndex, ordinal) => {
          assert.equal(
            sectionAt(markdown, lineIndex, declaredViewId, generated.sectionOrder),
            order[ordinal],
            `${file}:${lineIndex} (ordinal ${ordinal}) did not address to '${order[ordinal]}'`,
          );
          headingsChecked += 1;
        });
        viewsChecked += 1;
      }

      assert.ok(viewsChecked >= 60, `only checked ${viewsChecked} views — expected close to 72`);
      assert.ok(headingsChecked >= 150, `only checked ${headingsChecked} headings — expected close to 186`);
    },
  );
});

/**
 * ── STEP 11 — `sectionOrderFor`, AND ITS OWN FALSIFIER, SIMULATED ──
 *
 * `server/app.py` does not serve a `sections` field today (design doc §5.9, address.ts's own
 * header), so there is nothing live to compare against. What can be proven here, honestly:
 *
 *   5. IGNORING THE FIELD REPRODUCES TODAY'S BEHAVIOUR EXACTLY — proof standard #3. A served view
 *      shaped exactly as `server/app.py:_read_views` emits it today (`{id, path, title, domain,
 *      markdown}`, no `sections` key) makes `sectionOrderFor` return `declared` BY REFERENCE, and
 *      `sectionAt` through it agrees with `sectionAt` through `declared` directly, over the full
 *      72-view sweep.
 *   6. THE DESIGN DOCUMENT'S OWN FALSIFIER, SIMULATED — "the envelope's section order for every
 *      view equals the generator's, for all 72." An INDEPENDENT scanner (deliberately NOT
 *      `generateQualification`/`parseYamlSubset` — a flat regex walk over `sections:` / `- id:`
 *      lines, the same posture `server/app.py`'s own `_parse_view_meta` already takes for
 *      `id:`/`path:`/`domain:`) stands in for what a widened `_read_views` would publish. Compared
 *      against `SECTION_ORDER` (the generator's own answer, a different code path over the same
 *      config) for every one of the real views.
 *   7. THE POSITIVE CONTROL for #6 — a scratch config mutation moves the independent scanner's
 *      answer, proving it is not vacuously always equal (proof standard #4, reused from section 3).
 *   8. NO FORK — when a served view's order genuinely disagrees with the declared one (synthetic),
 *      `sectionOrderFor` picks the served order WHOLESALE, never a per-element merge of the two.
 */
describe("5. sectionOrderFor — ignoring the field reproduces today's behaviour exactly", () => {
  test("a view shaped exactly as server/app.py emits it today returns `declared` BY REFERENCE", () => {
    const servedView = { id: "inbox", path: "inbox.md", title: "Inbox", domain: "all", markdown: "" };
    const result = sectionOrderFor(servedView, SECTION_ORDER);
    assert.equal(result, SECTION_ORDER, "no `sections` key present — nothing to prefer over `declared`");
  });

  const skip = monorepoAvailable && vaultAvailable
    ? false
    : "needs both the monorepo and the vault — see section 4's own skip condition";

  test(
    "over the full 72-view sweep, sectionAt through sectionOrderFor(todaysShapedView, declared) " +
      "agrees with sectionAt through declared directly, for every heading",
    { skip },
    () => {
      const generated = generateQualification(DEFAULT_CONFIG_DIR);
      const viewsDir = join(DEFAULT_CONFIG_DIR, "views");
      const files = readdirSync(viewsDir).filter(
        (f) => f.endsWith(".yaml") && f !== "default_registration.yaml",
      );
      let headingsChecked = 0;
      for (const file of files) {
        const text = readFileSync(join(viewsDir, file), "utf8");
        const pathMatch = text.match(/^\s*path:\s*(\S+)\s*$/m);
        const idMatch = text.match(/^([A-Za-z0-9_-]+):\s*$/m);
        if (!pathMatch || !idMatch) continue;
        const path = pathMatch[1].replace(/^["']|["']$/g, "");
        const viewId = idMatch[1];
        const mdPath = join(vaultDir, path);
        if (!existsSync(mdPath)) continue;
        const markdown = readFileSync(mdPath, "utf8");
        const order = generated.sectionOrder[viewId];
        if (order === undefined) continue;

        const servedView = { id: viewId, path, title: viewId, domain: null, markdown };
        const merged = sectionOrderFor(servedView, generated.sectionOrder);
        assert.equal(merged, generated.sectionOrder, `${file}: unexpected preference over declared`);

        markdown.split(/\r?\n/).forEach((line, lineIndex) => {
          if (!/^#{1,6} /.test(line)) return;
          assert.equal(
            sectionAt(markdown, lineIndex, viewId, merged),
            sectionAt(markdown, lineIndex, viewId, generated.sectionOrder),
            `${file}:${lineIndex} diverged when routed through sectionOrderFor`,
          );
          headingsChecked += 1;
        });
      }
      assert.ok(headingsChecked >= 150, `only checked ${headingsChecked} headings — expected close to 186`);
    },
  );
});

/**
 * An independent stand-in for what a widened `server/app.py:_read_views` would publish — a flat
 * regex walk, never the generator's own `parseYamlSubset`. Two-space `sections:`, four-space
 * `- id: <value>` — the shape every one of the operator's 72 real view files uses (verified by
 * section 4's own sweep passing over all of them with this same indentation assumption baked into
 * the generator it compares against). Returns `null` when the file declares no `sections:` block.
 */
function scanDeclaredSectionOrder(text) {
  const lines = text.split(/\r?\n/);
  const start = lines.findIndex((l) => l === "  sections:");
  if (start === -1) return null;
  const order = [];
  for (let i = start + 1; i < lines.length; i += 1) {
    const line = lines[i];
    const idLine = line.match(/^ {4}- id:\s*(\S+)\s*$/);
    if (idLine) {
      order.push(idLine[1]);
      continue;
    }
    // A line at or below `sections:`'s own indentation, that is not a `- id:` line, ends the block.
    if (/^ {0,2}\S/.test(line)) break;
  }
  return order;
}

describe("6. THE DESIGN DOCUMENT'S OWN FALSIFIER, SIMULATED — envelope order == generator order, all 72", () => {
  const skip = monorepoAvailable
    ? false
    : `monorepo not checked out at ${DEFAULT_CONFIG_DIR} — skipped in CI, same posture as section 3`;

  test(
    "an INDEPENDENT scanner over the real config agrees with the generator's sectionOrder, per view",
    { skip },
    () => {
      const generated = generateQualification(DEFAULT_CONFIG_DIR);
      const viewsDir = join(DEFAULT_CONFIG_DIR, "views");
      const files = readdirSync(viewsDir).filter(
        (f) => f.endsWith(".yaml") && f !== "default_registration.yaml",
      );
      let viewsChecked = 0;
      for (const file of files) {
        const text = readFileSync(join(viewsDir, file), "utf8");
        const idMatch = text.match(/^([A-Za-z0-9_-]+):\s*$/m);
        if (!idMatch) continue;
        const viewId = idMatch[1];
        const declaredOrder = generated.sectionOrder[viewId];
        if (declaredOrder === undefined) continue; // no published sections for this view — nothing to compare

        const scanned = scanDeclaredSectionOrder(text);
        assert.ok(scanned !== null, `${file}: independent scanner found no sections: block`);
        assert.deepEqual(
          scanned,
          declaredOrder,
          `${file}: independent scan disagrees with the generator's own sectionOrder`,
        );
        viewsChecked += 1;
      }
      assert.ok(viewsChecked >= 60, `only checked ${viewsChecked} views — expected close to 72`);
    },
  );

  test(
    "POSITIVE CONTROL: a scratch reorder moves the independent scanner's answer — proof it is not vacuous",
    { skip },
    () => {
      const scratch = mkdtempSync(join(tmpdir(), "address-scanner-control-"));
      try {
        const configDir = join(scratch, "config");
        cpSync(DEFAULT_CONFIG_DIR, configDir, { recursive: true });
        const path = join(configDir, "views", "inbox.yaml");
        const before = scanDeclaredSectionOrder(readFileSync(path, "utf8"));
        assert.deepEqual(before, ["inbox-tagged", "domain-empty"]);

        const lines = readFileSync(path, "utf8").split("\n");
        const startOf = (id) => lines.findIndex((l) => l.trim() === `- id: ${id}`);
        const first = startOf("inbox-tagged");
        const second = startOf("domain-empty");
        const blockA = lines.slice(first, second);
        const blockB = lines.slice(second, second + (second - first));
        const reordered = [...lines.slice(0, first), ...blockB, ...blockA, ...lines.slice(second + blockA.length)];
        writeFileSync(path, reordered.join("\n"));

        const after = scanDeclaredSectionOrder(readFileSync(path, "utf8"));
        assert.deepEqual(after, ["domain-empty", "inbox-tagged"], "the scanner did not track the edit");
      } finally {
        rmSync(scratch, { recursive: true, force: true });
      }
    },
  );
});

describe("7. sectionOrderFor — no fork: a disagreeing served order wins WHOLESALE, never merged element-by-element", () => {
  const DECLARED = { inbox: ["inbox-tagged", "domain-empty"], "this-week": ["a", "b", "c"] };

  test("a served view's own order replaces its view's declared entry entirely", () => {
    const servedView = { id: "inbox", sections: ["domain-empty", "inbox-tagged"] };
    const merged = sectionOrderFor(servedView, DECLARED);
    assert.deepEqual(merged.inbox, ["domain-empty", "inbox-tagged"], "served order wins for this view");
    assert.equal(merged["this-week"], DECLARED["this-week"], "an untouched view's declared order is unchanged");
  });

  test("sectionAt through the merged table names the SERVED id at each ordinal, never a mix of the two", () => {
    const servedView = { id: "inbox", sections: ["domain-empty", "inbox-tagged"] };
    const merged = sectionOrderFor(servedView, DECLARED);
    const source = ["## Anything", "## Anything Else"].join("\n");
    assert.equal(sectionAt(source, 0, "inbox", merged), "domain-empty");
    assert.equal(sectionAt(source, 1, "inbox", merged), "inbox-tagged");
  });

  test("an empty served order is still a WHOLESALE replacement, not treated as absent", () => {
    const servedView = { id: "inbox", sections: [] };
    const merged = sectionOrderFor(servedView, DECLARED);
    assert.deepEqual(merged.inbox, []);
    assert.equal(sectionAt("## Anything", 0, "inbox", merged), null, "nothing to address into an empty order");
  });
});
