/**
 * L3 ADDRESSING — `sectionAt` NAMES THE `(view, section)` A PRINTED ROW SITS IN, BY CONFIG ID.
 *
 *   node --test tests/present-address.test.mjs
 *
 * `docs/implementation-artifacts/design-the-resolution-architecture.md` step 2: the app already
 * knows a section by its POSITIONAL ORDINAL; the declaration is keyed on the config's `id:` string.
 * Nothing joined them, so `membership.ts` — proven correct, `tests/present-membership.test.mjs` and
 * `tests/qualification-agreement.test.mjs`, 2,184 reachable triples — could not be called. This file
 * proves the join, and proves it closes THE TRAP rather than merely avoiding it: the naive
 * `Object.keys(sections[view])[ordinal]` works on 25 of 27 published views and is silently wrong on
 * the operator's two daily surfaces, because the published predicate table is a proper SUBSET of
 * the declared sections there (`daily-work` 1 of 5, `daily-personal` 3 of 8).
 *
 * Four sections:
 *
 *   1. THE ORDINAL, against small hand-built fixtures — the counting rule alone.
 *   2. THE JOIN, against the operator's REAL `presentation.json` (already regenerated by this
 *      change) and REAL markdown transcribed from his vault — `inbox`, and THE TRAP CASES,
 *      `daily-work` and `daily-personal`, addressed correctly on every one of their un-published
 *      ordinals, not only the published one.
 *   3. THE FALSIFIER: a config change (rename, reorder) moves the answer, proven against a scratch
 *      copy of the real config — skipped, loudly, when the monorepo is not checked out.
 *   4. THE SWEEP, against every one of the 72 real views this instance declares — skipped, loudly,
 *      when either the monorepo or the vault (`~/qntm`) is not present, since it needs both.
 *
 * WHAT THIS DOES NOT PROVE: agreement with the engine's own `RenderedLineRecord.section_id`, which
 * needs a running cycle and none is run here (see this repo's report on why). What section 4 proves
 * instead is the fact `design-presentation-instance-identity.md` §2.3(c) already measured and
 * `instance.ts`'s own shipped ordinal already trusts: the Nth heading in the rendered file IS the
 * Nth entry in the config's declared `sections:` list, positionally, for all 72 views.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { cpSync, existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { sectionAt, sectionOrdinalAt } from "../dist/present.js";
import {
  generateQualification,
  DEFAULT_CONFIG_DIR,
} from "../scripts/generate-qualification-declaration.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVED = JSON.parse(readFileSync(resolve(HERE, "..", "presentation.json"), "utf8"));
const SECTION_ORDER = SERVED.qualification.sectionOrder;

describe("1. sectionOrdinalAt — counting rule alone, small fixtures", () => {
  const SOURCE = [
    "- [ ] above any heading",
    "## First",
    "- [ ] a line in First",
    "",
    "## Second",
    "- [ ] a line in Second",
    "  - [ ] an indented line, still Second",
    "## Third",
  ].join("\n");

  test("above the first heading is null", () => {
    assert.equal(sectionOrdinalAt(SOURCE, 0), null);
  });

  test("a heading line belongs to the section it OPENS, not the one before", () => {
    assert.equal(sectionOrdinalAt(SOURCE, 1), 0, "## First");
    assert.equal(sectionOrdinalAt(SOURCE, 4), 1, "## Second");
    assert.equal(sectionOrdinalAt(SOURCE, 7), 2, "## Third");
  });

  test("every line under a heading, including a blank one, carries that heading's ordinal", () => {
    assert.equal(sectionOrdinalAt(SOURCE, 2), 0);
    assert.equal(sectionOrdinalAt(SOURCE, 3), 0, "a blank line still sits inside its section");
    assert.equal(sectionOrdinalAt(SOURCE, 5), 1);
    assert.equal(sectionOrdinalAt(SOURCE, 6), 1, "indentation does not open a new section");
  });

  test("out of range or a non-integer index is null, not a crash", () => {
    assert.equal(sectionOrdinalAt(SOURCE, -1), null);
    assert.equal(sectionOrdinalAt(SOURCE, 999), null);
    assert.equal(sectionOrdinalAt(SOURCE, 1.5), null);
  });

  test("a file with no heading at all is null everywhere", () => {
    assert.equal(sectionOrdinalAt("- [ ] just one line", 0), null);
  });
});

describe("2. sectionAt — the join, against the REAL declaration and REAL vault content", () => {
  test("inbox: two headings, two real section ids, in the declared order", () => {
    // `~/qntm/inbox.md`, verbatim (read-only, 2026-08-01) — the same fixture
    // tests/present-instance.test.mjs uses for the same reason: a live vault must not be read at
    // test time, so it is transcribed once, with a citation.
    const INBOX = [
      "## Inbox",
      "## Domain Empty",
      "- [ ] Ring the dentist",
    ].join("\n");
    assert.equal(sectionAt(INBOX, 0, "inbox", SECTION_ORDER), "inbox-tagged");
    assert.equal(sectionAt(INBOX, 1, "inbox", SECTION_ORDER), "domain-empty");
    assert.equal(sectionAt(INBOX, 2, "inbox", SECTION_ORDER), "domain-empty");
  });

  test("an unknown view addresses nothing — refused, not guessed", () => {
    assert.equal(sectionAt("## Only Heading", 0, "not-a-real-view", SECTION_ORDER), null);
  });

  describe("THE TRAP CASES — every declared ordinal addresses, not only the published one", () => {
    // `~/qntm/work/daily.md`, headings verbatim (read-only, 2026-08-01). Only "In Progress" (ordinal
    // 0) is in `SERVED.qualification.sections['daily-work']` — 4 of these 5 headings sit under a
    // section this instance publishes NO predicate for. `sectionAt` must still name all five,
    // because it indexes `sectionOrder`, never `sections`.
    const DAILY_WORK = [
      "## In Progress",
      "## Urgent",
      "## Due Today",
      "## Work Waiting",
      "- [~] Andrew to come back having spoken to them",
      "## Work Capture",
    ].join("\n");

    test("daily-work: published subset is 1 of 5 — asserted as the precondition for this test", () => {
      const published = Object.keys(SERVED.qualification.sections["daily-work"] ?? {});
      assert.deepEqual(published, ["in-progress"], "the trap's own precondition changed underfoot");
      assert.equal(SECTION_ORDER["daily-work"].length, 5);
    });

    test("all five ordinals address correctly, including the four unpublished ones", () => {
      assert.equal(sectionAt(DAILY_WORK, 0, "daily-work", SECTION_ORDER), "in-progress");
      assert.equal(sectionAt(DAILY_WORK, 1, "daily-work", SECTION_ORDER), "urgent");
      assert.equal(sectionAt(DAILY_WORK, 2, "daily-work", SECTION_ORDER), "due-today");
      assert.equal(sectionAt(DAILY_WORK, 3, "daily-work", SECTION_ORDER), "waiting");
      assert.equal(
        sectionAt(DAILY_WORK, 4, "daily-work", SECTION_ORDER),
        "waiting",
        "a body line under an unpublished section still addresses",
      );
      assert.equal(sectionAt(DAILY_WORK, 5, "daily-work", SECTION_ORDER), "capture");
    });

    test("THE FAILING VERSION OF THIS TEST — indexing the published subset gets it wrong from ordinal 1", () => {
      // Not what this module does; written out so the trap is legible as a concrete, checkable
      // claim rather than only prose. `Object.keys(sections[view])[ordinal]` on daily-work:
      const naive = Object.keys(SERVED.qualification.sections["daily-work"]);
      assert.equal(naive[0], "in-progress", "ordinal 0 happens to agree");
      assert.equal(naive[1], undefined, "ordinal 1 ('urgent') is where the naive version breaks");
    });

    // `~/qntm/personal/daily.md`, headings verbatim (read-only, 2026-08-01). 3 of 8 published.
    const DAILY_PERSONAL = [
      "## High Priority",
      "## Due Soon",
      "## Personal Waiting",
      "- [~] Kev to let me know",
      "## Routine Drift",
      "## Personal Capture",
      "## Orphans",
      "## Backlog",
      "## Done",
    ].join("\n");

    test("daily-personal: published subset is 3 of 8 — asserted as the precondition for this test", () => {
      const published = Object.keys(SERVED.qualification.sections["daily-personal"] ?? {}).sort();
      assert.deepEqual(published, ["backlog", "done", "routine-drift"]);
      assert.equal(SECTION_ORDER["daily-personal"].length, 8);
    });

    test("all eight ordinals address correctly, including the five unpublished ones", () => {
      assert.equal(sectionAt(DAILY_PERSONAL, 0, "daily-personal", SECTION_ORDER), "high-priority");
      assert.equal(sectionAt(DAILY_PERSONAL, 1, "daily-personal", SECTION_ORDER), "due-soon");
      assert.equal(sectionAt(DAILY_PERSONAL, 2, "daily-personal", SECTION_ORDER), "waiting");
      assert.equal(
        sectionAt(DAILY_PERSONAL, 3, "daily-personal", SECTION_ORDER),
        "waiting",
        "a body line under an unpublished section still addresses",
      );
      assert.equal(sectionAt(DAILY_PERSONAL, 4, "daily-personal", SECTION_ORDER), "routine-drift");
      assert.equal(sectionAt(DAILY_PERSONAL, 5, "daily-personal", SECTION_ORDER), "capture");
      assert.equal(sectionAt(DAILY_PERSONAL, 6, "daily-personal", SECTION_ORDER), "orphans");
      assert.equal(sectionAt(DAILY_PERSONAL, 7, "daily-personal", SECTION_ORDER), "backlog");
      assert.equal(sectionAt(DAILY_PERSONAL, 8, "daily-personal", SECTION_ORDER), "done");
    });
  });
});

const monorepoAvailable = existsSync(DEFAULT_CONFIG_DIR);
const vaultDir = join(homedir(), "qntm");
const vaultAvailable = existsSync(vaultDir);

describe("3. THE FALSIFIER — a config change (rename, reorder) moves the answer", () => {
  const skip = monorepoAvailable
    ? false
    : `monorepo not checked out at ${DEFAULT_CONFIG_DIR} — this section runs locally and is ` +
      "skipped in CI, which does not clone it (same posture as tests/present-qualification.test.mjs)";

  const withMutatedConfig = (mutate) => {
    const scratch = mkdtempSync(join(tmpdir(), "address-falsifier-"));
    try {
      const configDir = join(scratch, "config");
      cpSync(DEFAULT_CONFIG_DIR, configDir, { recursive: true });
      mutate(configDir);
      return generateQualification(configDir).sectionOrder;
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  };

  test("BASELINE: the real config's inbox order is what section 2 assumed", { skip }, () => {
    const order = generateQualification(DEFAULT_CONFIG_DIR).sectionOrder;
    assert.deepEqual(order["inbox"], ["inbox-tagged", "domain-empty"]);
  });

  test("RENAME: renaming a section id in the config changes what sectionAt returns for its ordinal", { skip }, () => {
    const order = withMutatedConfig((configDir) => {
      const path = join(configDir, "views", "inbox.yaml");
      const mutated = readFileSync(path, "utf8").replace("id: domain-empty", "id: untriaged");
      assert.ok(mutated.includes("id: untriaged"), "the falsifier's own edit did not apply");
      writeFileSync(path, mutated);
    });
    const source = ["## Inbox", "## Domain Empty"].join("\n");
    assert.equal(sectionAt(source, 1, "inbox", order), "untriaged");
    assert.notEqual(sectionAt(source, 1, "inbox", order), "domain-empty");
  });

  test("REORDER: swapping two sections' declared order swaps sectionAt's answer at their ordinals", { skip }, () => {
    const order = withMutatedConfig((configDir) => {
      const path = join(configDir, "views", "inbox.yaml");
      const lines = readFileSync(path, "utf8").split("\n");
      // Swap the two `- id:` BLOCKS whole, by line range, rather than reconstructing their text —
      // preserves indentation and any trailing comment exactly, so the only thing that changes is
      // which block comes first.
      const startOf = (id) => lines.findIndex((l) => l.trim() === `- id: ${id}`);
      const first = startOf("inbox-tagged");
      const second = startOf("domain-empty");
      assert.ok(first !== -1 && second !== -1 && first < second, "unexpected inbox.yaml shape");
      const blockA = lines.slice(first, second); // inbox-tagged's 3 lines
      const blockB = lines.slice(second, second + (second - first)); // domain-empty's 3 lines
      const reordered = [...lines.slice(0, first), ...blockB, ...blockA, ...lines.slice(second + blockA.length)];
      writeFileSync(path, reordered.join("\n"));
    });
    assert.deepEqual(order["inbox"], ["domain-empty", "inbox-tagged"], "the declared order followed the edit");
    const source = ["## Domain Empty", "## Inbox"].join("\n");
    assert.equal(sectionAt(source, 0, "inbox", order), "domain-empty");
    assert.equal(sectionAt(source, 1, "inbox", order), "inbox-tagged");
  });
});

describe("4. THE SWEEP — every one of the 72 real views this instance declares", () => {
  const skip =
    monorepoAvailable && vaultAvailable
      ? false
      : `needs both the monorepo (${DEFAULT_CONFIG_DIR}) and the vault (${vaultDir}) — this ` +
        "section runs locally and is skipped in CI, which has neither";

  test(
    "for every view, sectionOrder's length equals the real markdown's heading count, and every " +
      "heading addresses to the declared id at its own ordinal — step 1's falsifier and step 2's, together",
    { skip },
    () => {
      const generated = generateQualification(DEFAULT_CONFIG_DIR);
      const viewsDir = join(DEFAULT_CONFIG_DIR, "views");
      const files = readdirSync(viewsDir).filter(
        (f) => f.endsWith(".yaml") && f !== "default_registration.yaml",
      );

      // Minimal, test-local extraction of each view's `path:` — mirrors the generator's own
      // "targeted line scan, not a general YAML parser" posture (see that script's header), used
      // here only to locate the rendered markdown file, never to decide anything the app ships.
      const pathOf = (file) => {
        const text = readFileSync(join(viewsDir, file), "utf8");
        const match = text.match(/^\s*path:\s*(\S+)\s*$/m);
        return match ? match[1].replace(/^["']|["']$/g, "") : null;
      };

      let viewsChecked = 0;
      let headingsChecked = 0;
      for (const file of files) {
        const path = pathOf(file);
        if (path === null) continue;
        const mdPath = join(vaultDir, path);
        if (!existsSync(mdPath)) continue;
        const markdown = readFileSync(mdPath, "utf8");
        const lines = markdown.split(/\r?\n/);

        const headingIndexes = [];
        lines.forEach((line, i) => {
          if (/^#{1,6} /.test(line)) headingIndexes.push(i);
        });

        // The view id is the file's own top-level key, which is not always the filename — checked
        // directly rather than assumed, the same guard the generator itself applies.
        const text = readFileSync(join(viewsDir, file), "utf8");
        const idMatch = text.match(/^([A-Za-z0-9_-]+):\s*$/m);
        const declaredViewId = idMatch ? idMatch[1] : null;
        const order = declaredViewId ? generated.sectionOrder[declaredViewId] : undefined;
        if (order === undefined) continue; // a view with no sections: nothing to address

        assert.equal(
          order.length,
          headingIndexes.length,
          `${file}: sectionOrder has ${order.length} entries but ${path} has ` +
            `${headingIndexes.length} headings`,
        );

        headingIndexes.forEach((lineIndex, ordinal) => {
          assert.equal(
            sectionAt(markdown, lineIndex, declaredViewId, generated.sectionOrder),
            order[ordinal],
            `${file}:${lineIndex} (ordinal ${ordinal}) did not address to '${order[ordinal]}'`,
          );
          headingsChecked += 1;
        });
        viewsChecked += 1;
      }

      assert.ok(viewsChecked >= 60, `only checked ${viewsChecked} views — expected close to 72`);
      assert.ok(headingsChecked >= 150, `only checked ${headingsChecked} headings — expected close to 186`);
    },
  );
});
