/**
 * DOES THE BROWSER AGREE WITH THE ENGINE?
 *
 *   node --test tests/qualification-agreement.test.mjs
 *
 * This is the test that matters, because divergence here is SILENT: a browser that quietly
 * disagrees with the engine tells the operator his line is staying when the next cycle is about to
 * move it, and nothing anywhere reports a fault. Every other test in this change proves the app is
 * self-consistent. This one proves it is right.
 *
 * ── THE EXPECTED SIDE IS NOT WRITTEN BY HAND ──
 *
 * `tests/fixtures/qualification-agreement.json` is GENERATED by `scripts/qualification-agreement.py`
 * calling `qntm_graph.patterns.engine.matches_pattern` — the engine's own single-node membership
 * test — over the operator's real config bundle and a read-only copy of his real graph. Nothing in
 * it was transcribed. A hand-written expectation would only prove that the person who wrote the
 * test and the person who wrote the evaluator made the same mistake.
 *
 * ── WHAT IS COMPARED ──
 *
 *   rows    every distinct (node_type, domain, status) triple that OCCURS in the real graph — 61
 *           of them, covering all 1501 nodes. The generator additionally proved, while producing
 *           this, that every node sharing a triple gets the SAME answer from the engine; that is
 *           what makes a triple a complete input and this comparison exhaustive rather than
 *           sampled.
 *   probes  the full cross product of triples a line being TYPED can reach — every node type a
 *           type token or a section default can produce, every domain a domain token can produce
 *           plus none, every status a declared checkbox can produce. 2184 of them. The real graph
 *           is a sample of history, not of what the operator can type: only one of its 61 triples
 *           matches `domain-empty` and none matches `inbox-items`, so the probes are where the
 *           cases this work is actually about get covered.
 *
 * ── WHAT IT DOES NOT PROVE ──
 *
 * It proves the PREDICATE half — given a field set, does the app reach the engine's verdict. It
 * does not prove the FIELD-RESOLUTION half: that a given line resolves to a given field set is
 * `tests/present-membership.test.mjs`'s claim, and it is checked against the config's declared
 * registration cascade and token tables, not against a running engine. Minting a node to measure
 * that would mean running a cycle, which no test here does.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { readQualificationDeclaration, matchesQualifier, qualifierNeedsGraph } from "../dist/present.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const read = (path) => JSON.parse(readFileSync(resolve(HERE, path), "utf8"));

const SERVED = read("../presentation.json");
const TRUTH = read("./fixtures/qualification-agreement.json");
const LANGUAGE = readQualificationDeclaration(SERVED).qualification;

/** Every qualification the app says this field set belongs to, sorted to match the fixture. */
function appAnswer(fields) {
  return TRUTH.patterns
    .filter((name) => matchesQualifier(fields, LANGUAGE.predicates[name]))
    .sort();
}

describe("0. the fixture is about the declaration that actually shipped", () => {
  // RESTATED 2026-08-04: `compile-qualification.mjs`'s one-hop `children:`/`parents:` widening
  // publishes patterns whose answer for a node depends on that node's NEIGHBOURS, not only its own
  // (node_type, domain, status) triple — `scripts/qualification-agreement.py`'s own method (key on
  // the triple, prove one triple gets one answer) is invalid for those by construction, so it
  // EXCLUDES them from `TRUTH.patterns` and names them, separately, in `TRUTH.graphDependentPatterns`
  // (that script's own header, "RESTATED 2026-08-04"). `LANGUAGE.predicates` still carries ALL of
  // them — `TRUTH.patterns` is a proper SUBSET now, not the same set.
  const published = Object.keys(LANGUAGE.predicates).sort();

  test("every SELF-ONLY pattern the engine answered for is a pattern the app published", () => {
    // A fixture generated against a different declaration would compare two unrelated things and
    // could pass while proving nothing.
    for (const name of TRUTH.patterns) {
      assert.ok(
        published.includes(name),
        `'${name}' is in the engine's fixture but not in the app's published predicates — ` +
          "the agreement fixture is STALE, regenerate it with scripts/qualification-agreement.py",
      );
    }
  });

  test(
    "THE HEADLINE PROOF FOR THIS LEG'S OWN CLASSIFICATION: the engine's own script and the app's " +
      "own qualifierNeedsGraph agree, pattern for pattern, on which predicates are graph-dependent",
    () => {
      // `TRUTH.graphDependentPatterns` was computed PYTHON-SIDE, by reading `edgeSteps` off the SAME
      // served `presentation.json` this test reads — not derived from this test's own opinion, and
      // not re-derived from `qualifierNeedsGraph` here either. Two independent readings of one fact,
      // compared, is what makes this an agreement proof rather than a tautology.
      const appGraphDependent = published.filter((name) => qualifierNeedsGraph(LANGUAGE.predicates[name])).sort();
      assert.deepEqual(TRUTH.graphDependentPatterns.slice().sort(), appGraphDependent);
      assert.ok(appGraphDependent.length > 0, "no graph-dependent pattern published — this widening did not widen");
      // AND every self-only pattern the engine verified is published, is NOT flagged graph-dependent
      // by the app — the two classifications must partition `published`, not overlap.
      for (const name of TRUTH.patterns) {
        assert.ok(
          !appGraphDependent.includes(name),
          `'${name}' is in both TRUTH.patterns (self-only, engine-verified) and the app's ` +
            "graph-dependent set — the two must be disjoint",
        );
      }
    },
  );

  test("the fixture is not empty in either direction", () => {
    assert.ok(TRUTH.rows.length > 0 && TRUTH.probeCells.length > 0);
    assert.ok(
      TRUTH.matchSets.some((set) => set.length > 0),
      "no triple matched anything — the comparison would pass vacuously",
    );
  });
});

describe("1. over every field triple in the operator's real graph", () => {
  test(`all ${TRUTH.rows.length} triples (covering ${TRUTH.nodes} nodes) agree with the engine`, () => {
    for (const row of TRUTH.rows) {
      assert.deepEqual(
        appAnswer(row.fields),
        TRUTH.matchSets[row.matches],
        `the app and the engine disagree for ${JSON.stringify(row.fields)} ` +
          `(${row.nodes} real node(s) have it)`,
      );
    }
  });

  test("structural chrome is excluded, the way the engine's own desugarer excludes it", () => {
    // `domain-empty`'s `find:` names no node_type, so bundle load synthesises one exclusion per
    // identity-unique type. A header has no domain and is not done, so WITHOUT those synthesised
    // exclusions it would match — this asserts the generator reproduced them.
    const header = TRUTH.rows.find((row) => row.fields.node_type === "header");
    assert.ok(header, "no header node in the real graph to check the exclusion against");
    assert.deepEqual(TRUTH.matchSets[header.matches], [], "the engine matched a header");
    assert.deepEqual(appAnswer(header.fields), [], "the app matched a header");
    for (const nodeType of LANGUAGE.structuralNodeTypes) {
      assert.deepEqual(
        appAnswer({ node_type: nodeType, domain: null, status: "open" }),
        [],
        `'${nodeType}' is identity-unique chrome but the app placed it in a section`,
      );
    }
  });
});

describe("2. over the whole space a line being typed can reach", () => {
  const { node_type: types, domain: domains, status: statuses } = TRUTH.probeAxes;

  test(`all ${TRUTH.probeCells.length} reachable triples agree with the engine`, () => {
    let cell = 0;
    let checked = 0;
    for (const node_type of types) {
      for (const domain of domains) {
        for (const status of statuses) {
          const fields = { node_type, domain, status };
          assert.deepEqual(
            appAnswer(fields),
            TRUTH.matchSets[TRUTH.probeCells[cell]],
            `the app and the engine disagree for ${JSON.stringify(fields)}`,
          );
          cell += 1;
          checked += 1;
        }
      }
    }
    assert.equal(cell, TRUTH.probeCells.length, "the dense probe array was not fully consumed");
    assert.equal(checked, types.length * domains.length * statuses.length);
  });

  test("THE OPERATOR'S OWN TWO CASES, decided by the engine, reproduced by the app", () => {
    // Read out of the fixture by position rather than asserted as literals, so these two lines are
    // the ENGINE's answers, not this test's opinion of them.
    const at = (node_type, domain, status) => {
      const i =
        (types.indexOf(node_type) * domains.length + domains.indexOf(domain)) * statuses.length +
        statuses.indexOf(status);
      return TRUTH.matchSets[TRUTH.probeCells[i]];
    };
    // A bare line under Domain Empty: task, no domain, open.
    assert.ok(at("task", null, "open").includes("domain-empty"), "the engine moved the bare line");
    assert.ok(appAnswer({ node_type: "task", domain: null, status: "open" }).includes("domain-empty"));
    // The same line with #work: task, domain work, open.
    assert.ok(!at("task", "work", "open").includes("domain-empty"), "the engine kept the #work line");
    assert.ok(
      !appAnswer({ node_type: "task", domain: "work", status: "open" }).includes("domain-empty"),
    );
  });
});
