/**
 * DOES THE BROWSER AGREE WITH THE ENGINE'S OWN RESOLUTION CASCADE?
 *
 *   node --test tests/resolution-agreement.test.mjs
 *
 * The operator's proof standard #2, run exactly as the design document's own falsifier states it
 * (design-the-resolution-architecture.md step 5): "a test that the published value equals what the
 * engine's own resolver returns, for defaults and registration, over his real config… run the
 * engine's resolution machinery against a read-only copy to get the truth side."
 *
 * `tests/fixtures/resolution-agreement.json` is GENERATED by `scripts/resolution-agreement.py`
 * calling the engine's OWN `qntm_md.resolution.cascade.ResolutionCascade` and
 * `qntm_md.resolution.registration.resolve_registration_keys` / `resolve_base_node_type` — never
 * transcribed. It answers for every (view, section) pair `presentation.json`'s `qualification.
 * sections` publishes: 49 pairs, 27 views.
 *
 * ── WHAT IS COMPARED, AND WHERE EACH HALF LIVES ──
 *
 *   nodeType / defaults   already published on `qualification.sections[view][section]` by
 *                         `scripts/generate-qualification-declaration.mjs`, and already the value
 *                         `app/present/membership.ts` reads on every line typed. This is the first
 *                         time that value has been checked against the engine's OWN resolver
 *                         rather than only against a re-read of the same YAML the generator itself
 *                         parsed — divergence between "the generator's idea of the cascade" and
 *                         "the engine's idea of the cascade" would be silent without this.
 *   registration.*        the four GLOBAL registration facts this branch newly publishes on
 *                         `resolution.registration` — checked against `resolve_base_node_type`
 *                         (the REVERT target, GLOBAL only) and `resolve_registration_keys` (the
 *                         MINTING default).
 *
 * ── WHAT IT DOES NOT PROVE ──
 *
 * The Python side calls `ResolutionCascade().resolve({STRUCTURAL_NODE: section_defaults})` —
 * exactly the design document's own falsifier, not a stronger reproduction of the applier's full
 * five-level merge. `scripts/resolution-agreement.py`'s header explains why that is not a weaker
 * test than it looks: three positive controls (GLOBAL defaults empty, no section declares
 * `default_fields`, `default_tags` empty everywhere) are asserted BEFORE the fixture is trusted,
 * and the script refuses to write a fixture if any of them ever stops holding.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { readQualificationDeclaration, readConfigResolutionDeclaration } from "../dist/present.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const read = (path) => JSON.parse(readFileSync(resolve(HERE, path), "utf8"));

const SERVED = read("../presentation.json");
const TRUTH = read("./fixtures/resolution-agreement.json");
const QUALIFICATION = readQualificationDeclaration(SERVED).qualification;
const RESOLUTION = readConfigResolutionDeclaration(SERVED).resolution;

describe("0. the fixture is about the declaration that actually shipped", () => {
  test("every (view, section) the engine answered for is published in qualification.sections", () => {
    for (const row of TRUTH.sections) {
      assert.ok(
        QUALIFICATION.sections[row.view]?.[row.section],
        `${row.view}.${row.section} is in the fixture but not in the served declaration`,
      );
    }
  });

  test("the fixture is not empty, and covers every published section (not a subset)", () => {
    const publishedCount = Object.values(QUALIFICATION.sections).reduce(
      (n, s) => n + Object.keys(s).length,
      0,
    );
    assert.ok(TRUTH.sections.length > 0);
    assert.equal(
      TRUTH.sections.length,
      publishedCount,
      "the fixture covers a different section count than the served declaration — regenerate it",
    );
  });
});

describe("1. REGISTRATION — the two names for one key agree with the engine", () => {
  test("baseNodeType == resolve_base_node_type(GLOBAL declaration)", () => {
    assert.equal(RESOLUTION.registration.baseNodeType, TRUTH.global.baseNodeType);
  });

  test("defaultNodeType / inputGrammar == resolve_registration_keys at GLOBAL", () => {
    assert.equal(RESOLUTION.registration.defaultNodeType, TRUTH.global.defaultNodeType);
    assert.equal(RESOLUTION.registration.inputGrammar, TRUTH.global.inputGrammar);
    assert.deepEqual(RESOLUTION.registration.defaultTags, TRUTH.global.defaultTags);
  });

  test("the two names really do carry the same value today, which is the trap's whole shape", () => {
    // Not a redundant assertion: this is the fact §5.5 of the design document warns is easy to
    // get away with checking casually, because the two are equal in THIS config. Published under
    // separate names anyway — see resolutiontable.ts's header for why that must not change.
    assert.equal(RESOLUTION.registration.defaultNodeType, RESOLUTION.registration.baseNodeType);
  });
});

describe("2. DEFAULTS + per-section REGISTRATION — every published section agrees with the engine", () => {
  test(`all ${TRUTH.sections.length} published (view, section) pairs agree with ResolutionCascade`, () => {
    for (const row of TRUTH.sections) {
      const published = QUALIFICATION.sections[row.view][row.section];
      assert.equal(
        published.nodeType,
        row.nodeType,
        `${row.view}.${row.section}: published nodeType '${published.nodeType}' != engine ` +
          `'${row.nodeType}'`,
      );
      assert.deepEqual(
        published.defaults ?? null,
        row.defaults,
        `${row.view}.${row.section}: published defaults ${JSON.stringify(published.defaults)} != ` +
          `engine ${JSON.stringify(row.defaults)}`,
      );
    }
  });

  test("at least one section resolves a non-empty defaults map (a positive control)", () => {
    // A measurement of "everything agrees" is worthless if every row compared was `null == null`.
    assert.ok(
      TRUTH.sections.some((row) => row.defaults !== null),
      "every published section's engine-resolved defaults were empty — this comparison would " +
        "pass even if the defaults-reading half of the generator were completely broken",
    );
  });

  test("the operator's own two inbox sections are in the comparison and agree", () => {
    const inbox = TRUTH.sections.filter((row) => row.view === "inbox");
    assert.equal(inbox.length, 2);
    const domainEmpty = inbox.find((row) => row.section === "domain-empty");
    assert.equal(domainEmpty.nodeType, "task");
    assert.equal(domainEmpty.defaults, null, "domain-empty declares no defaults: block");
  });
});
