/**
 * retype-agreement — EXHAUSTIVE cross-engine proof that `renderRuleEffects`'s `retype` swap lands
 * the BYTE-IDENTICAL line the real engine renders, for EVERY member of the declared node_type token
 * family (`presentation.json`'s own `qualification.tokens.node_type`) — not a hand-picked sample.
 *
 *   node --test tests/retype-agreement.test.mjs
 *
 * ── WHY EXHAUSTIVE, AND WHY GENERATED FROM THE DECLARATION RATHER THAN HAND-WRITTEN ──
 *
 * Two defects shipped in one day (2026-08-07) from tests that each proved ONE retype
 * (`#task` -> `#outcome`, nothing trailing the tag) and called the family covered. The operator's
 * own words after the second: "there is a limited deterministic set — no guessing." This file reads
 * `presentation.json`'s real, closed, 32-member `node_type` family directly — the SAME artifact the
 * browser itself serves — and `tests/fixtures/retype-agreement.json` (generated by
 * `scripts/retype-agreement.py` against a LIVE import of the real engine renderer) supplies the
 * expected byte-exact line for each member. A future node type added to the vocabulary makes the
 * fixture stale (this file's own precondition check refuses to run against a mismatched family)
 * rather than leaving the new member silently untested.
 *
 * ── TWO SCENARIOS PER TYPE — WHY BOTH ──
 *
 * APPEND — the line carries NO existing type tag (the operator's bare/default-typed line) before
 * the retype. Exercises the fix this leg makes: `renderRuleEffects`'s fallback used to write
 * `text += ' ' + token'` unconditionally, landing a fresh type tag AFTER a trailing marker/tag the
 * engine's own declared `tagOrder`/composition puts it BEFORE.
 *
 * SWAP — the line ALREADY carries `#task` (canonically positioned, first among its own tags) before
 * the retype. Exercises the in-place splice PR #149 added, now reordered via the SAME declared
 * `canonicalOrder` the engine's `OrderTagsActionDispatcher` applies, not merely spliced at the old
 * token's own offset.
 *
 * Both scenarios carry a stamp, a domain tag AND a due_date marker on every fixture line — never a
 * bare title, which would pass by construction (nothing trailing to misplace the tag ahead of).
 *
 * ── "task" ITSELF IS EXCLUDED FROM THE GENERIC LOOP, NAMED RATHER THAN SILENT ──
 *
 * Both scenarios below start from a line whose CURRENT type is `task` (the family's own default —
 * `presentation.json`'s `qualification.defaultNodeType`). Retyping `task` to `task` is not a retype
 * at all (`renderRuleEffects`'s own "already spelled — nothing to add" branch, `kind: "unchanged"`),
 * so it is asserted SEPARATELY, once, rather than folded into the byte-identity loop every other
 * entry runs through.
 *
 * ── "explainer" IS ALSO EXCLUDED FROM THE GENERIC LOOP — A REAL FINDING, NOT A DODGE ──
 *
 * Running the exhaustive loop against the real engine found ONE genuine divergence in 31: retyping
 * to `explainer` renders `*Renew passport*` in the engine, `Renew passport` (unstyled) in the
 * browser — everything else on the line (stamp, tag position/order, marker) is BYTE-IDENTICAL. This
 * is `apps/qntm-md/src/qntm_md/render/contracts/render_title_style.yaml` — "THIS FILE IS THE SOURCE
 * OF TRUTH FOR TITLE STYLE" — a PER-NODE-TYPE rule-based title wrap (`node.type == "explainer" ->
 * italic`), entirely distinct from `composition.titleStyles` (`resolution.composition`, a single
 * UNCONDITIONAL wrap applied to every title regardless of type, already read by
 * `express/composition.ts`). `express/composition.ts`'s own header already names this exact
 * boundary: "this app has no per-node rule-based title-style resolver (that is
 * `render_title_style`, engine-only)". Publishing that axis is separately-scoped, real work — not
 * attempted here — so `explainer` is excluded from the byte-identity assertion, WITH a narrower
 * assertion proving the divergence is exactly the title wrap and nothing this leg touches.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { renderRuleEffects } from "../dist/present.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");

const PRESENTATION = JSON.parse(readFileSync(resolve(REPO, "presentation.json"), "utf8"));
const NODE_TYPE_TOKENS = PRESENTATION.qualification.tokens.node_type;
const TAG_ORDER = PRESENTATION.resolution.tagOrder;

const FIXTURE = JSON.parse(readFileSync(resolve(HERE, "fixtures", "retype-agreement.json"), "utf8"));

// ── PRECONDITIONS — refuse to run a weakened proof rather than silently pass one ──
assert.ok(Object.keys(NODE_TYPE_TOKENS).length >= 10, "presentation.json's node_type family looks too small — regenerate it first");
assert.ok(TAG_ORDER !== undefined, "presentation.json carries no resolution.tagOrder — regenerate it (npm run generate:resolution)");
assert.equal(
  FIXTURE.entries.length,
  Object.keys(NODE_TYPE_TOKENS).length,
  "tests/fixtures/retype-agreement.json is stale against presentation.json's OWN node_type family — " +
    "regenerate with: apps/qntm-md/.venv/bin/python scripts/retype-agreement.py (run from the monorepo checkout)",
);
for (const entry of FIXTURE.entries) {
  assert.equal(
    NODE_TYPE_TOKENS[entry.token],
    entry.nodeType,
    `fixture entry '${entry.token}' names node type '${entry.nodeType}', but presentation.json maps it to ` +
      `'${NODE_TYPE_TOKENS[entry.token]}' — the fixture is stale, regenerate it`,
  );
}

/** The line BEFORE a retype — stamp, domain tag, due_date marker, and (if `withTaskTag`) an
 * explicit `#task` canonically positioned first among its own tags — the SAME shape
 * `scripts/retype-agreement.py` rendered `expectedLine` from, minus the type tag itself. */
function sourceLineFor(nodeType, withTaskTag) {
  const stamp = `[[qntm:n-${nodeType}]]`;
  const tags = withTaskTag ? "#task #work" : "#work";
  return `- [ ] Renew passport ${stamp} ${tags} 📅 2026-09-01`;
}

/** `nodeType`s the generic byte-identity loop skips, each with the reason named at this file's own
 * header — never a silent omission. */
const EXCLUDED = new Set(["task", "explainer"]);

describe("EXHAUSTIVE — every declared node_type token, APPEND scenario (no existing type tag)", () => {
  for (const entry of FIXTURE.entries) {
    if (EXCLUDED.has(entry.nodeType)) continue;
    test(`#${entry.token} -> byte-identical to the real engine's own render`, () => {
      const source = sourceLineFor(entry.nodeType, false);
      const outcome = renderRuleEffects(
        source,
        [{ verb: "retype", to: entry.nodeType, ruleId: "retype-agreement" }],
        NODE_TYPE_TOKENS,
        {},
        {},
        TAG_ORDER,
      );
      assert.equal(outcome.kind, "rendered", `abstained instead of rendering ${entry.token}`);
      assert.equal(outcome.text, entry.expectedLine);
    });
  }
});

describe("EXHAUSTIVE — every declared node_type token, SWAP scenario (#task already present)", () => {
  for (const entry of FIXTURE.entries) {
    if (EXCLUDED.has(entry.nodeType)) continue;
    test(`#task -> #${entry.token} — the swap, byte-identical to the real engine's own render`, () => {
      const source = sourceLineFor(entry.nodeType, true);
      const outcome = renderRuleEffects(
        source,
        [{ verb: "retype", to: entry.nodeType, ruleId: "retype-agreement" }],
        NODE_TYPE_TOKENS,
        {},
        {},
        TAG_ORDER,
      );
      assert.equal(outcome.kind, "rendered", `abstained instead of rendering ${entry.token}`);
      assert.equal(outcome.text, entry.expectedLine);
    });
  }
});

describe("explainer — the ONE real divergence found, proven to be EXACTLY the title-style axis", () => {
  test("everything this leg touches (stamp, tag position, tag order, marker) still matches; only the italic title wrap does not", () => {
    const entry = FIXTURE.entries.find((e) => e.nodeType === "explainer");
    assert.ok(entry, "precondition: the fixture carries an 'explainer' entry");
    const outcome = renderRuleEffects(
      sourceLineFor(entry.nodeType, false),
      [{ verb: "retype", to: entry.nodeType, ruleId: "retype-agreement" }],
      NODE_TYPE_TOKENS,
      {},
      {},
      TAG_ORDER,
    );
    assert.equal(outcome.kind, "rendered");
    // The engine's own line wrapped in `*...*` — strip exactly that wrap (never a looser
    // normalisation) and the two must agree on every other byte: stamp, tag position, tag order,
    // marker. If they did not, this would be a SECOND, real divergence this leg's own fix caused —
    // it is not: `entry.expectedLine` is `"- [ ] *Renew passport* [[qntm:n-explainer]] #work ` +
    // `#explainer 📅 2026-09-01"`.
    const unstyled = entry.expectedLine.replace("*Renew passport*", "Renew passport");
    assert.equal(outcome.text, unstyled, "the ONLY difference from the engine's own line must be the title's italic wrap");
    assert.notEqual(outcome.text, entry.expectedLine, "precondition: the browser genuinely does not apply the title wrap — this is the named gap, not a false pass");
  });
});

describe("task -> task is not a retype at all", () => {
  test("already spelled — 'unchanged', never 'rendered', for either starting shape", () => {
    const bare = renderRuleEffects(
      sourceLineFor("task", false),
      [{ verb: "retype", to: "task", ruleId: "retype-agreement" }],
      NODE_TYPE_TOKENS,
      {},
      {},
      TAG_ORDER,
    );
    assert.equal(bare.kind, "rendered", "the bare line still gains its OWN #task tag — that IS a real change");
    assert.equal(bare.text, FIXTURE.entries.find((e) => e.nodeType === "task").expectedLine);

    const tagged = renderRuleEffects(
      sourceLineFor("task", true),
      [{ verb: "retype", to: "task", ruleId: "retype-agreement" }],
      NODE_TYPE_TOKENS,
      {},
      {},
      TAG_ORDER,
    );
    assert.equal(tagged.kind, "unchanged", "#task retyped to task, already spelled, is genuinely no change");
  });
});

describe("MUTATION PROOF — this file's own byte-identity check is not vacuously green", () => {
  test("a single mismatched byte in one fixture entry is caught", () => {
    const entry = FIXTURE.entries.find((e) => e.nodeType === "outcome");
    assert.ok(entry, "precondition: the fixture carries an 'outcome' entry");
    const source = sourceLineFor(entry.nodeType, false);
    const outcome = renderRuleEffects(
      source,
      [{ verb: "retype", to: entry.nodeType, ruleId: "retype-agreement" }],
      NODE_TYPE_TOKENS,
      {},
      {},
      TAG_ORDER,
    );
    const corrupted = entry.expectedLine.replace("#outcome", "#outcomeX");
    assert.notEqual(outcome.text, corrupted, "MUTATION: a corrupted expectation must not equal the real answer");
    assert.throws(() => assert.equal(outcome.text, corrupted), assert.AssertionError, "the harness itself must be capable of failing this check");
  });
});
